Repository shopinvader/odoo-shopinvader, pull requests merged in 2018-12, with the labels that each got.

#249 [10.0] fix demo data in backend for Locomotive
  shopinvader_locomotive/demo/backend_demo.xml
  shopinvader_locomotive/tests/test_backend.py
Labels: needs fixing

#166 [ADD] module 'shopinvader_import_image'
  requirements.txt
  shopinvader_image/models/shopinvader_image_mixin.py
  shopinvader_import_image/README.rst
  shopinvader_import_image/__init__.py
  shopinvader_import_image/__manifest__.py
  shopinvader_import_image/models/__init__.py
  shopinvader_import_image/models/import_image.py
  shopinvader_import_image/readme/CONTRIBUTORS.rst
  shopinvader_import_image/readme/DESCRIPTION.rst
  shopinvader_import_image/static/description/index.html
  shopinvader_import_image/views/import_product_image_view.xml
Labels: Mergeable

#209 [FIX] fix 'is_company' that was hardcoded
  shopinvader/services/customer.py
  shopinvader/tests/test_customer.py
  shopinvader_sale_profile/tests/test_customer_service.py
Labels: Mergeable

#218 [MIG] 10.0 shopinvader_lead (from 8.0)
  shopinvader_lead/README.rst
  shopinvader_lead/__init__.py
  shopinvader_lead/__manifest__.py
  shopinvader_lead/controllers/__init__.py
  shopinvader_lead/controllers/main.py
  shopinvader_lead/demo/email_demo.xml
  shopinvader_lead/demo/notification_demo.xml
  shopinvader_lead/models/__init__.py
  shopinvader_lead/models/lead.py
  shopinvader_lead/models/notification.py
  shopinvader_lead/readme/CONFIGURATION.rst
  shopinvader_lead/readme/CONTRIBUTORS.rst
  shopinvader_lead/readme/CREDITS.rst
  shopinvader_lead/readme/DESCRIPTION.rst
  shopinvader_lead/readme/ROADMAP.rst
  shopinvader_lead/services/__init__.py
  shopinvader_lead/services/lead.py
  shopinvader_lead/static/description/index.html
  shopinvader_lead/tests/__init__.py
  shopinvader_lead/tests/test_lead.py
Labels: Mergeable

#255 [IMP] reorganize shopinvader backend view (renamed to website view)
  shopinvader/__manifest__.py
  shopinvader/demo/backend_demo.xml
  shopinvader/models/shopinvader_backend.py
  shopinvader/views/shopinvader_backend_view.xml
  shopinvader_assortment/__manifest__.py
  shopinvader_assortment/views/shopinvader_backend.xml
  shopinvader_delivery_carrier/__manifest__.py
  shopinvader_delivery_carrier/views/backend_view.xml
  shopinvader_image/__manifest__.py
  shopinvader_image/models/shopinvader_backend.py
  shopinvader_image/views/shopinvader_backend_view.xml
  shopinvader_locomotive/__manifest__.py
  shopinvader_locomotive/views/shopinvader_backend_view.xml
  shopinvader_payment/__manifest__.py
  shopinvader_payment/views/backend_view.xml
  shopinvader_product_stock/__manifest__.py
  shopinvader_product_stock/views/shopinvader_backend.xml
  shopinvader_sale_profile/__manifest__.py
  shopinvader_search_engine/__manifest__.py
  shopinvader_search_engine/views/shopinvader_backend_view.xml
Labels: Mergeable

#175 WIP TODO 10.0 mig shopinvader reset password
  shopinvader_locomotive_reset_password/README.rst
  shopinvader_locomotive_reset_password/__init__.py
  shopinvader_locomotive_reset_password/__manifest__.py
  shopinvader_locomotive_reset_password/models/__init__.py
  shopinvader_locomotive_reset_password/models/partner.py
  shopinvader_locomotive_reset_password/readme/CONTRIBUTORS.rst
  shopinvader_locomotive_reset_password/readme/DESCRIPTION.rst
  shopinvader_locomotive_reset_password/services/__init__.py
  shopinvader_locomotive_reset_password/services/customer.py
  shopinvader_locomotive_reset_password/static/description/index.html
  shopinvader_locomotive_reset_password/views/partner_view.xml
  shopinvader_locomotive_reset_password/wizards/__init__.py
  shopinvader_locomotive_reset_password/wizards/reset_password.py
  shopinvader_locomotive_reset_password/wizards/reset_password_view.xml
Labels: Mergeable

#246 10.0 acsone paypal lmi
  setup/shopinvader_payment_paypal/odoo/__init__.py
  setup/shopinvader_payment_paypal/odoo/addons/__init__.py
  setup/shopinvader_payment_paypal/odoo/addons/shopinvader_payment_paypal
  setup/shopinvader_payment_paypal/setup.py
  shopinvader_payment_paypal/README.rst
  shopinvader_payment_paypal/__init__.py
  shopinvader_payment_paypal/__manifest__.py
  shopinvader_payment_paypal/demo/shopinvader_payment_demo.xml
  shopinvader_payment_paypal/models/__init__.py
  shopinvader_payment_paypal/models/shopinvader_payment.py
  shopinvader_payment_paypal/services/__init__.py
  shopinvader_payment_paypal/services/payment_service.py
  shopinvader_payment_paypal/static/description/icon.png
  shopinvader_payment_paypal/tests/__init__.py
  shopinvader_payment_paypal/tests/test_payment.py
  shopinvader_payment_paypal/views/shopinvader_payment.xml
Labels: WIP
