Repository shopinvader/odoo-shopinvader, pull requests merged in 2019-12, with the labels that each got.

#524 [10.0][FIX] shopinvader_delivery_carrier should returns only outgoing pickings
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_delivery_carrier/tests/test_delivery_service.py
Labels: approved, enhancement, needs review

#520 [12.0] Add server env support
  oca_dependencies.txt
  shopinvader/__manifest__.py
  shopinvader/migrations/12.0.3.3.0/post-migrate.py
  shopinvader/models/shopinvader_backend.py
  shopinvader/views/shopinvader_backend_view.xml
  shopinvader_locomotive/models/shopinvader_backend.py
Labels: 12.0, enhancement

#529 [10.0][FIX] shopinvader.partner force email in lower case
  shopinvader/tests/test_shopinvader_partner_binding.py
  shopinvader/wizards/shopinvader_partner_binding_line.py
Labels: approved, ready to merge
