Repository shopinvader/odoo-shopinvader, pull requests merged in 2019-05, with the labels that each got.

#242 [10.0][ADD] Fill the seo_title (of products)
  shopinvader/models/__init__.py
  shopinvader/models/seo_title_mixin.py
  shopinvader/models/shopinvader_backend.py
  shopinvader/models/shopinvader_category.py
  shopinvader/models/shopinvader_product.py
  shopinvader/models/shopinvader_variant.py
  shopinvader/tests/__init__.py
  shopinvader/tests/test_shopinvader_variant_seo_title.py
  shopinvader/views/shopinvader_backend_view.xml
  shopinvader_search_engine/models/shopinvader_variant.py
Labels: needs fixing

#318 [12.0][MIG] base_url
  base_url/README.rst
  base_url/__init__.py
  base_url/__manifest__.py
  base_url/models/__init__.py
  base_url/models/abstract_url.py
  base_url/models/url_url.py
  base_url/tests/models.py
  base_url/tests/models_mixin.py
  base_url/tests/test_abstract_url.py
  requirements.txt
  setup/base_url/setup.py
Labels: needs review

#319 [10.0][IMP] Improve view about delivery carrier
  shopinvader_delivery_carrier/views/backend_view.xml
Labels: needs review

#326 [10.0][FIX] automatic_url_key should be computed in sudo
  base_url/models/abstract_url.py
Labels: enhancement
