Repository shopinvader/odoo-shopinvader, pull requests merged in 2019-11, with the labels that each got.

#497 Customer validation: fix non valid handling
  shopinvader/components/partner_validator.py
Labels: bug

#500 Customer title: fix m2o handling
  shopinvader/services/address.py
Labels: bug

#511 [12.0] Cart add item: make sure product is allowed
  shopinvader/models/product_product.py
  shopinvader/services/cart.py
  shopinvader/tests/test_cart_item.py
Labels: 12.0, needs review

#499 [10.0][FIX] cart/search create empty cart in some case
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
Labels: approved, enhancement, needs review, ready to merge
