Repository shopinvader/odoo-shopinvader, pull requests merged in 2019-10, with the labels that each got.

#443 [12.0][FIX] The account analytic account is not correctly filled during cart creation
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
Labels: 12.0, approved, ready to merge

#448 [10.0][ADD] shopinvader_cart_expiry: add new feature to manage cart expiry delay
  shopinvader_cart_expiry/__init__.py
  shopinvader_cart_expiry/__manifest__.py
  shopinvader_cart_expiry/data/ir_cron.xml
  shopinvader_cart_expiry/models/__init__.py
  shopinvader_cart_expiry/models/shopinvader_backend.py
  shopinvader_cart_expiry/readme/CONTRIBUTORS.rst
  shopinvader_cart_expiry/readme/DESCRIPTION.rst
  shopinvader_cart_expiry/tests/__init__.py
  shopinvader_cart_expiry/tests/test_cart_expiry.py
  shopinvader_cart_expiry/views/shopinvader_backend.xml
Labels: 10.0, approved, ready to merge

#450 [12.0][IMP] add currencies to shopinvader's demo data
  shopinvader_locomotive/demo/backend_demo.xml
Labels: 12.0, approved, ready to merge

#397 [12.0][REF] clean shopinvader_quotation
  shopinvader_quotation/README.rst
  shopinvader_quotation/readme/CONTRIBUTORS.rst
  shopinvader_quotation/readme/CREDITS.rst
  shopinvader_quotation/readme/DESCRIPTION.rst
  shopinvader_quotation/tests/test_quotation.py
Labels: approved, needs review, ready to merge

#453 [10.0][REF] clean shopinvader_quotation
  shopinvader_quotation/README.rst
  shopinvader_quotation/readme/CONTRIBUTORS.rst
  shopinvader_quotation/readme/CREDITS.rst
  shopinvader_quotation/readme/DESCRIPTION.rst
  shopinvader_quotation/tests/test_quotation.py
Labels: 10.0

#461 [12.0][FIX] shopinvader: Don't create cart on customer login or creation
  shopinvader/services/cart.py
  shopinvader/services/customer.py
  shopinvader/tests/test_customer.py
Labels: 12.0, bug

#460 [10.0][FIX] shopinvader: Don't create cart on customer login or creation
  shopinvader/services/cart.py
  shopinvader/services/customer.py
  shopinvader/tests/test_customer.py
Labels: 10.0, bug

#465 [10.0][FIX] shopinvader guest mode export
  shopinvader_locomotive/component/event_listeners.py
  shopinvader_locomotive/models/__init__.py
  shopinvader_locomotive/models/res_partner.py
  shopinvader_locomotive/tests/test_shopinvader_partner.py
  shopinvader_locomotive_guest_mode/__init__.py
  shopinvader_locomotive_guest_mode/models/__init__.py
  shopinvader_locomotive_guest_mode/models/res_partner.py
  shopinvader_locomotive_guest_mode/tests/__init__.py
  shopinvader_locomotive_guest_mode/tests/test_shopinvader_partner.py
Labels: approved

#470 [10.0][FIX] shopinvader: change url_key of all bindings in case of product renaming
  shopinvader/models/product_template.py
Labels: approved

#359 [12.0] [IMP] Shopinvader: allow the write on sale orders from partner without access
  shopinvader/models/res_partner.py
Labels: approved, enhancement, ready to merge

#474 [12.0] Customer language + company_name handling
  shopinvader/services/customer.py
Labels: 12.0, enhancement

#464 [12.0] shopinvader_locomotive: drop duplicated cron
  shopinvader_locomotive/data/ir_cron.xml
Labels: 12.0, approved, ready to merge

#485 [12.0][FIX] shopinvader: change url_key of all bindings in case of product renaming
  shopinvader/models/product_template.py
Labels: 12.0, approved
