Repository shopinvader/odoo-shopinvader, pull requests merged in 2019-08, with the labels that each got.

#334 [12.0][MIG] shopinvader_image
  shopinvader_image/README.rst
  shopinvader_image/__init__.py
  shopinvader_image/__manifest__.py
  shopinvader_image/hooks.py
  shopinvader_image/models/__init__.py
  shopinvader_image/models/shopinvader_backend.py
  shopinvader_image/models/shopinvader_category.py
  shopinvader_image/models/shopinvader_image_mixin.py
  shopinvader_image/models/shopinvader_image_resize.py
  shopinvader_image/models/shopinvader_variant.py
  shopinvader_image/readme/CONTRIBUTORS.rst
  shopinvader_image/readme/HISTORY.rst
  shopinvader_image/services/__init__.py
  shopinvader_image/services/abstract_sale.py
  shopinvader_image/static/description/index.html
  shopinvader_image/tests/test_cart.py
  shopinvader_image/tests/test_getting_image.py
Labels: needs review

#335 [12.0][MIG] shopinvader_assortment
  shopinvader_assortment/__manifest__.py
  shopinvader_assortment/models/se_index.py
  shopinvader_assortment/models/shopinvader_backend.py
  shopinvader_assortment/readme/CONTRIBUTORS.rst
  shopinvader_assortment/readme/HISTORY.rst
  shopinvader_assortment/tests/test_product_auto_bind.py
Labels: needs review

#354 [12.0][MIG] shopinvader_delivery_carrier
  oca_dependencies.txt
  shopinvader_delivery_carrier/__manifest__.py
  shopinvader_delivery_carrier/controllers/main.py
  shopinvader_delivery_carrier/models/__init__.py
  shopinvader_delivery_carrier/models/backend.py
  shopinvader_delivery_carrier/models/sale.py
  shopinvader_delivery_carrier/models/shopinvader_notification.py
  shopinvader_delivery_carrier/models/stock_picking.py
  shopinvader_delivery_carrier/readme/CONTRIBUTORS.rst
  shopinvader_delivery_carrier/services/__init__.py
  shopinvader_delivery_carrier/services/cart.py
  shopinvader_delivery_carrier/tests/__init__.py
  shopinvader_delivery_carrier/tests/common.py
  shopinvader_delivery_carrier/tests/test_carrier.py
  shopinvader_delivery_carrier/tests/test_notification.py
Labels: needs review

#370 [12.0][FIX] search backend by api key name
  shopinvader/models/shopinvader_backend.py
Labels: bug, needs review

#372 [10.0][FIX] search backend by api key name
  shopinvader/models/shopinvader_backend.py
Labels: bug

#358 [12.0][MIG] shopinvader_lead
  setup/shopinvader_lead/odoo/addons/shopinvader_lead
  setup/shopinvader_lead/setup.py
  shopinvader_lead/__init__.py
  shopinvader_lead/__manifest__.py
  shopinvader_lead/controllers/__init__.py
  shopinvader_lead/controllers/main.py
  shopinvader_lead/models/__init__.py
  shopinvader_lead/models/lead.py
  shopinvader_lead/models/notification.py
  shopinvader_lead/services/__init__.py
  shopinvader_lead/services/lead.py
  shopinvader_lead/tests/__init__.py
  shopinvader_lead/tests/test_lead.py
Labels: needs review

#363 [12.0][FIX] shopinvader_product_stock: Call correct method on stock move
  shopinvader_product_stock/models/stock_move.py
Labels: enhancement, needs review

#361 [10.0][FIX] The pricelist should be the one set on the backend
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
Labels: enhancement, needs review

#377 [12.0][FIX] The pricelist should be the one set on the backend
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
Labels: needs review

#337 [12.0][MIG] shopinvader_locomotive
  requirements.txt
  shopinvader_locomotive/__init__.py
  shopinvader_locomotive/__manifest__.py
  shopinvader_locomotive/component/__init__.py
  shopinvader_locomotive/component/adapter.py
  shopinvader_locomotive/component/binder.py
  shopinvader_locomotive/component/core.py
  shopinvader_locomotive/component/deleter.py
  shopinvader_locomotive/component/event_listeners.py
  shopinvader_locomotive/component/exporter.py
  shopinvader_locomotive/component/mapper.py
  shopinvader_locomotive/component/shopinvader_partner_adapter.py
  shopinvader_locomotive/component/shopinvader_partner_export_mapper.py
  shopinvader_locomotive/controllers/__init__.py
  shopinvader_locomotive/controllers/main.py
  shopinvader_locomotive/data/ir_cron.xml
  shopinvader_locomotive/demo/backend_demo.xml
  shopinvader_locomotive/hooks.py
  shopinvader_locomotive/models/__init__.py
  shopinvader_locomotive/models/keychain.py
  shopinvader_locomotive/models/locomotive_binding.py
  shopinvader_locomotive/models/shopinvader_backend.py
  shopinvader_locomotive/models/shopinvader_partner.py
  shopinvader_locomotive/readme/CONTRIBUTORS.rst
  shopinvader_locomotive/readme/HISTORY.rst
  shopinvader_locomotive/services/customer.py
  shopinvader_locomotive/tests/__init__.py
  shopinvader_locomotive/tests/common.py
  shopinvader_locomotive/tests/test_backend.py
  shopinvader_locomotive/tests/test_shopinvader_partner.py
  shopinvader_locomotive/views/shopinvader_backend_view.xml
Labels: needs review

#368 [10.0][IMP] product_stock_state: Allows to override the way to get the qty …
  product_stock_state/models/product_product.py
Labels: needs review

#369 [12.0][IMP] product_stock_state: Allows to override the way to get the qty …
  product_stock_state/models/product_product.py
Labels: needs review

#374 [10.0][FIX] shopinvader: increase protection of the cart entry points
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
  shopinvader/tests/test_cart_item.py
Labels: needs review

#378 [12.0][FIX] shopinvader: increase protection of the cart entry points
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
  shopinvader/tests/test_cart_item.py
Labels: needs review
