Repository shopinvader/odoo-shopinvader, pull requests merged in 2019-09, with the labels that each got.

#381 [12.0][FIX] shopinvader: Don't browse on non-existent cart
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
Labels: approved

#382 [10.0][FIX] shopinvader: Don't browse on non-existent cart
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
Labels: approved

#383 [12.0][FIX] shopinvader: Add inherited field 'description'
  shopinvader/models/shopinvader_variant.py
Labels: approved

#384 [10.0][FIX] shopinvader: Add inherited field 'description'
  shopinvader/models/shopinvader_variant.py
Labels: approved

#392 shopinvader_algolia: migrate to v12
  shopinvader_algolia/__manifest__.py
  shopinvader_algolia/components/deleter.py
  shopinvader_algolia/components/exporter.py
  shopinvader_algolia/hooks.py
  shopinvader_algolia/models/shopinvader_product.py
  shopinvader_algolia/readme/CONTRIBUTORS.rst
  shopinvader_algolia/tests/test_export.py
Labels: approved

#394 [10.0][FIX] shopinvader_image: Key is a required field of shopinvader.image…
  shopinvader_image/views/shopinvader_image_resize_view.xml
Labels: approved

#399 [10.0][REF] rename test variable, make it more explicit
  shopinvader_quotation/tests/test_quotation.py
Labels: approved

#406 [12.0][FIX] fix issue when confirming quotation
  shopinvader/models/sale.py
Labels: 12.0, approved

#402 [10.0][IMP] shopinvader: action_confirm_cart only applies to cart
  shopinvader/models/sale.py
Labels: 10.0

#403 [10.0][IMP] shopinvader: Get rid of last_step_id
  shopinvader/demo/backend_demo.xml
  shopinvader/models/shopinvader_backend.py
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
  shopinvader/views/shopinvader_backend_view.xml
Labels: 10.0

#408 [10.0][FIX] shopinvader_locomotive: limit partner export and manage write access
  shopinvader_locomotive/__manifest__.py
  shopinvader_locomotive/component/event_listeners.py
  shopinvader_locomotive/models/locomotive_binding.py
  shopinvader_locomotive/tests/__init__.py
  shopinvader_locomotive/tests/test_shopinvader_partner.py
Labels: 10.0, approved

#323 [10.0][ADD] Add wizard to bind shopinvader.partner
  shopinvader/__manifest__.py
  shopinvader/tests/__init__.py
  shopinvader/tests/test_shopinvader_partner_binding.py
  shopinvader/wizards/__init__.py
  shopinvader/wizards/shopinvader_partner_binding.py
  shopinvader/wizards/shopinvader_partner_binding.xml
  shopinvader/wizards/shopinvader_partner_binding_line.py
Labels: 10.0, approved, ready to merge

#412 [12.0]][FIX] shopinvader_locomotive: limit partner export and manage write access
  shopinvader_locomotive/__manifest__.py
  shopinvader_locomotive/component/event_listeners.py
  shopinvader_locomotive/models/locomotive_binding.py
  shopinvader_locomotive/tests/__init__.py
  shopinvader_locomotive/tests/test_shopinvader_partner.py
Labels: 12.0, approved

#413 [12.0] Add wizard to bind shopinvader.partner
  shopinvader/__manifest__.py
  shopinvader/tests/__init__.py
  shopinvader/tests/test_shopinvader_partner_binding.py
  shopinvader/wizards/__init__.py
  shopinvader/wizards/shopinvader_partner_binding.py
  shopinvader/wizards/shopinvader_partner_binding.xml
  shopinvader/wizards/shopinvader_partner_binding_line.py
Labels: 12.0, approved, ready to merge

#357 [10.0][ADD] Add a 'clear' on cart service + backend config
  shopinvader/models/shopinvader_backend.py
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
  shopinvader/views/shopinvader_backend_view.xml
Labels: approved, enhancement, needs review, ready to merge

#325 [10.0][ADD] Add delivery service
  shopinvader_delivery_carrier/__manifest__.py
  shopinvader_delivery_carrier/services/__init__.py
  shopinvader_delivery_carrier/services/abstract_sale.py
  shopinvader_delivery_carrier/services/cart.py
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_delivery_carrier/tests/__init__.py
  shopinvader_delivery_carrier/tests/test_delivery_service.py
Labels: 10.0, approved, enhancement, needs review, ready to merge

#313 [10.0][ADD] add module shopinvader_delivery_instruction
  setup/shopinvader_delivery_instruction/odoo/__init__.py
  setup/shopinvader_delivery_instruction/odoo/addons/__init__.py
  setup/shopinvader_delivery_instruction/odoo/addons/shopinvader_delivery_instruction
  setup/shopinvader_delivery_instruction/setup.py
  shopinvader_delivery_instruction/__init__.py
  shopinvader_delivery_instruction/__manifest__.py
  shopinvader_delivery_instruction/services/__init__.py
  shopinvader_delivery_instruction/services/abstract_sale.py
  shopinvader_delivery_instruction/services/cart.py
  shopinvader_delivery_instruction/tests/__init__.py
  shopinvader_delivery_instruction/tests/test_sale_order_picking_note.py
Labels: 10.0, approved, ready to merge

#327 [10.0][ADD] Add shopinvader_invoice
  setup/shopinvader_invoice/odoo/__init__.py
  setup/shopinvader_invoice/odoo/addons/__init__.py
  setup/shopinvader_invoice/odoo/addons/shopinvader_invoice
  setup/shopinvader_invoice/setup.py
  shopinvader_invoice/__init__.py
  shopinvader_invoice/__manifest__.py
  shopinvader_invoice/readme/CONTRIBUTORS.rst
  shopinvader_invoice/readme/DESCRIPTION.rst
  shopinvader_invoice/services/__init__.py
  shopinvader_invoice/services/invoice.py
  shopinvader_invoice/tests/__init__.py
  shopinvader_invoice/tests/test_invoice_service.py
Labels: 10.0, needs review

#418 [10.0][FIX] encoding for image name
  shopinvader_image/models/shopinvader_image_resize.py
Labels: 10.0

#410 [12.0][IMP] Shopinvader_demo_app dependencies
  oca_dependencies.txt
  setup/shopinvader_demo_app/odoo/addons/shopinvader_demo_app
  setup/shopinvader_demo_app/setup.py
  shopinvader_demo_app/__manifest__.py
Labels: 12.0, needs review

#430 [12.0][FIX] shopinvader: prevent any creation of empty cart by search…
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
Labels: 12.0, approved

#431 [12.0][FIX] shopinvader_assortment backend_view
  shopinvader_assortment/views/shopinvader_backend.xml
Labels: 12.0, approved

#434 [12.0][IMP]shopinvader_locomotive: Exports new locales mapping to locomotive
  shopinvader_locomotive/component/shopinvader_site_export_mapper.py
  shopinvader_locomotive/tests/test_backend.py
Labels: 12.0, enhancement

#435 [12.0] [FIX] shopinvader: Fix binding not created when a new lang is added
  shopinvader/models/shopinvader_backend.py
  shopinvader/tests/test_backend.py
  shopinvader/wizards/shopinvader_category_binding_wizard.py
  shopinvader/wizards/shopinvader_category_unbinding_wizard.py
  shopinvader/wizards/shopinvader_variant_binding_wizard.py
  shopinvader/wizards/shopinvader_variant_unbinding_wizard.py
Labels: 12.0, bug

#436 [12.0][FIX] shopinvader_demo_ap: Storage backend forced to public
  shopinvader_demo_app/__manifest__.py
  shopinvader_demo_app/demo/storage_backend_demo.xml
  shopinvader_demo_app/hooks.py
Labels: 12.0

#437 [12.0][FIX] shopinvader_elasticsearch: hierarchicalCategories into index mu…
  shopinvader_elasticsearch/demo/index_config_demo.xml
Labels: 12.0, bug

#438 [12.0][FIX] shopinvader_locomotive: Provides the right url entrypoint for R…
  shopinvader_locomotive/component/shopinvader_site_export_mapper.py
  shopinvader_locomotive/tests/test_backend.py
Labels: 12.0, bug

#441 [12.0][IMP] shopinvader_demo_app: Add stripe
  shopinvader_demo_app/__manifest__.py
Labels: 12.0
