Repository shopinvader/odoo-shopinvader, pull requests merged in 2019-04, with the labels that each got.

#237 [10.0][ADD] Add shopinvader_backend_image_proxy module
  setup/shopinvader_backend_image_proxy/odoo/__init__.py
  setup/shopinvader_backend_image_proxy/odoo/addons/__init__.py
  setup/shopinvader_backend_image_proxy/odoo/addons/shopinvader_backend_image_proxy
  setup/shopinvader_backend_image_proxy/setup.py
  shopinvader_backend_image_proxy/__init__.py
  shopinvader_backend_image_proxy/__manifest__.py
  shopinvader_backend_image_proxy/models/__init__.py
  shopinvader_backend_image_proxy/models/shopinvader_backend.py
  shopinvader_backend_image_proxy/models/shopinvader_image_mixin.py
  shopinvader_backend_image_proxy/readme/CONFIGURE.rst
  shopinvader_backend_image_proxy/readme/CONTRIBUTORS.rst
  shopinvader_backend_image_proxy/readme/DESCRIPTION.rst
  shopinvader_backend_image_proxy/tests/__init__.py
  shopinvader_backend_image_proxy/tests/test_shopinvader_backend.py
  shopinvader_backend_image_proxy/tests/test_shopinvader_image_mixin.py
  shopinvader_backend_image_proxy/views/shopinvader_backend.xml
  shopinvader_image/models/shopinvader_image_mixin.py
Labels: needs fixing

#261 10 shopinvader backend search tab
  shopinvader_search_engine/models/__init__.py
  shopinvader_search_engine/models/se_index.py
  shopinvader_search_engine/models/shopinvader_backend.py
  shopinvader_search_engine/views/shopinvader_backend_view.xml
Labels: Mergeable

#272 [ADD][10.0] Auto-bind related categories during product binding
  shopinvader/models/shopinvader_backend.py
  shopinvader/tests/test_product.py
  shopinvader/views/shopinvader_backend_view.xml
  shopinvader/wizards/shopinvader_variant_binding_wizard.py
Labels: Mergeable

#282 [10.0][ADD] Picking notification for delivery
  shopinvader_delivery_carrier/README.rst
  shopinvader_delivery_carrier/__init__.py
  shopinvader_delivery_carrier/__manifest__.py
  shopinvader_delivery_carrier/demo/mail_template.xml
  shopinvader_delivery_carrier/demo/shopinvader_notification.xml
  shopinvader_delivery_carrier/models/__init__.py
  shopinvader_delivery_carrier/models/shopinvader_notification.py
  shopinvader_delivery_carrier/models/stock_picking.py
  shopinvader_delivery_carrier/services/cart.py
  shopinvader_delivery_carrier/tests/__init__.py
  shopinvader_delivery_carrier/tests/test_notification.py
Labels: Mergeable

#292 [10.0] use auth_api_key from OCA
  auth_api_key/README.rst
  auth_api_key/__init__.py
  auth_api_key/__manifest__.py
  auth_api_key/models/__init__.py
  auth_api_key/models/auth_api_key.py
  auth_api_key/models/ir_http.py
  auth_api_key/models/keychain_account.py
  auth_api_key/security/auth_api_key.xml
  auth_api_key/static/description/icon.png
  auth_api_key/views/auth_api_key.xml
  shopinvader/__manifest__.py
  shopinvader/controllers/main.py
  shopinvader/demo/auth_api_key_demo.xml
  shopinvader/demo/backend_demo.xml
  shopinvader/models/shopinvader_backend.py
  shopinvader/tests/__init__.py
  shopinvader/tests/common.py
  shopinvader/tests/test_controller.py
  shopinvader/views/shopinvader_backend_view.xml
  shopinvader/views/shopinvader_menu.xml
  shopinvader_product_stock/models/product_product.py
  shopinvader_product_stock/tests/common.py
Labels: needs review

#299 [10.0][FIX] Fix during unbind of shopinvader.category
  shopinvader/models/shopinvader_category.py
  shopinvader/tests/test_shopinvader_category_binding_wizard.py
Labels: needs fixing

#279 [10.0][ADD] Add ask_mail (abstract) + Implement it for sale
  partner_contact_company/models/partner.py
  shopinvader/models/shopinvader_notification.py
  shopinvader/services/__init__.py
  shopinvader/services/abstract_mail.py
  shopinvader/services/abstract_sale.py
  shopinvader/services/cart.py
  shopinvader/services/sale.py
  shopinvader/tests/test_cart.py
  shopinvader/tests/test_sale.py
Labels: needs fixing

#300 [10.0][UPD] Update computation of shopinvader.category level
  shopinvader/models/shopinvader_category.py
  shopinvader/tests/test_product.py
Labels: needs fixing
