Repository shopinvader/odoo-shopinvader, pull requests merged in 2020-03, with the labels that each got.

#589 Switch to OCA maintainer tools
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  .travis/travis_delete_algolia_index
  partner_contact_company/views/users_view.xml
  requirements.txt
  setup/shopinvader_import_image/setup.py
  shopinvader/controllers/main.py
  shopinvader/demo/pricelist_demo.xml
  shopinvader/shopinvader_response.py
  shopinvader_cart_expiry/__manifest__.py
  shopinvader_delivery_instruction/__manifest__.py
  shopinvader_elasticsearch/__manifest__.py
  shopinvader_invoice/__manifest__.py
  shopinvader_partner_vat/__manifest__.py
  shopinvader_partner_vat/services/vat.py
  shopinvader_pending_cart_reminder/__manifest__.py
  shopinvader_product_template_multi_link/__manifest__.py
  shopinvader_product_template_multi_link/models/shopinvader_product.py
  shopinvader_product_template_multi_link/tests/test_product.py
  shopinvader_quotation/__manifest__.py
  shopinvader_sale_report/__manifest__.py
  test-requirements.txt
Labels: 10.0, approved

#545 [13.0] Add shopinvader_customer_multi_user
  shopinvader/models/res_partner.py
  shopinvader/services/address.py
  shopinvader/services/customer.py
  shopinvader/services/partner_mixin.py
  shopinvader/tests/test_customer.py
  shopinvader_customer_multi_user/README.rst
  shopinvader_customer_multi_user/__init__.py
  shopinvader_customer_multi_user/__manifest__.py
  shopinvader_customer_multi_user/components/__init__.py
  shopinvader_customer_multi_user/components/access_info.py
  shopinvader_customer_multi_user/controllers/__init__.py
  shopinvader_customer_multi_user/controllers/main.py
  shopinvader_customer_multi_user/models/__init__.py
  shopinvader_customer_multi_user/models/res_partner.py
  shopinvader_customer_multi_user/models/shopinvader_backend.py
  shopinvader_customer_multi_user/models/shopinvader_partner.py
  shopinvader_customer_multi_user/readme/CONTRIBUTORS.rst
  shopinvader_customer_multi_user/readme/CREDITS.rst
  shopinvader_customer_multi_user/readme/DESCRIPTION.rst
  shopinvader_customer_multi_user/readme/USAGE.rst
  shopinvader_customer_multi_user/services/__init__.py
  shopinvader_customer_multi_user/services/customer.py
  shopinvader_customer_multi_user/static/description/index.html
  shopinvader_customer_multi_user/tests/__init__.py
  shopinvader_customer_multi_user/tests/test_multi_user.py
  shopinvader_customer_multi_user/views/partner_view.xml
  shopinvader_customer_multi_user/views/shopinvader_backend.xml
Labels: 13.0, approved, ready to merge

#576 Fix typo in class name
  shopinvader_elasticsearch/components/exporter.py
Labels: approved, ready to merge

#575 Fix typo in name of class
  shopinvader_elasticsearch/components/exporter.py
Labels: approved, ready to merge

#570 [10.0][IMP][ADD] shopinvader - Document generate/download (pdf)
  shopinvader/controllers/main.py
  shopinvader/services/__init__.py
  shopinvader/services/abstract_download.py
  shopinvader/services/invoice.py
  shopinvader/services/sale.py
  shopinvader/tests/common.py
  shopinvader/tests/test_invoice.py
  shopinvader/tests/test_sale.py
Labels: approved, enhancement, needs review, ready to merge

#512 [10.0][UPD] Add the invoice/get service
  shopinvader_invoice/services/invoice.py
  shopinvader_invoice/tests/test_invoice_service.py
Labels: approved, enhancement, needs review, ready to merge

#526 [10.0][ADD] shopinvader_delivery_carrier add sale info related to returned pickings
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_delivery_carrier/tests/test_delivery_service.py
Labels: approved, ready to merge

#571 [10.0][IMP] shopinvader: Improve add item service
  shopinvader/models/sale.py
  shopinvader/models/shopinvader_backend.py
  shopinvader/services/cart.py
  shopinvader/tests/common.py
  shopinvader/tests/test_cart.py
  shopinvader/tests/test_cart_item.py
  shopinvader/views/sale_view.xml
  shopinvader/views/shopinvader_backend_view.xml
  shopinvader_promotion_rule/models/sale_order.py
  shopinvader_promotion_rule/services/cart.py
  shopinvader_promotion_rule/tests/test_cart.py
Labels: approved, enhancement, ready to merge

#572 [10.0] add new addon to allow to display the category image if the product does not have one
  setup/shopinvader_category_image_for_product/odoo/__init__.py
  setup/shopinvader_category_image_for_product/odoo/addons/__init__.py
  setup/shopinvader_category_image_for_product/odoo/addons/shopinvader_category_image_for_product
  setup/shopinvader_category_image_for_product/setup.py
  shopinvader_category_image_for_product/README.rst
  shopinvader_category_image_for_product/__init__.py
  shopinvader_category_image_for_product/__manifest__.py
  shopinvader_category_image_for_product/data/ir_export.xml
  shopinvader_category_image_for_product/models/__init__.py
  shopinvader_category_image_for_product/models/shopinvader_variant.py
  shopinvader_category_image_for_product/readme/CONTRIBUTORS.rst
  shopinvader_category_image_for_product/readme/DESCRIPTION.rst
Labels: approved, needs review, ready to merge

#577 [10.0][FIX] Fix missing parameters into some search validator
  shopinvader/services/address.py
  shopinvader/services/sale.py
  shopinvader/services/service.py
  shopinvader/tests/test_address.py
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_invoice/services/invoice.py
Labels: approved, enhancement, needs review, ready to merge

#404 [10.0][ADD] Return also state label (not only technical value)
  shopinvader/services/abstract_sale.py
  shopinvader/services/service.py
  shopinvader/tests/common.py
  shopinvader/tests/test_sale.py
  shopinvader_invoice/services/invoice.py
  shopinvader_invoice/tests/test_invoice_service.py
Labels: approved, ready to merge

#567 [10.0][ADD] Add module shopinvader_product_stock_assortment.
  setup/shopinvader_product_stock_assortment/odoo/__init__.py
  setup/shopinvader_product_stock_assortment/odoo/addons/__init__.py
  setup/shopinvader_product_stock_assortment/odoo/addons/shopinvader_product_stock_assortment
  setup/shopinvader_product_stock_assortment/setup.py
  shopinvader_product_stock_assortment/__init__.py
  shopinvader_product_stock_assortment/__manifest__.py
  shopinvader_product_stock_assortment/models/__init__.py
  shopinvader_product_stock_assortment/models/shopinvader_backend.py
  shopinvader_product_stock_assortment/tests/__init__.py
  shopinvader_product_stock_assortment/tests/test_product_auto_bind.py
Labels: 10.0, approved, needs review, ready to merge

#521 [10.0][IMP] shopinvader: Allows to display not bound products in cart
  shopinvader/models/shopinvader_backend.py
  shopinvader/services/abstract_sale.py
  shopinvader/tests/test_cart_item.py
  shopinvader/views/shopinvader_backend_view.xml
Labels: approved, enhancement, ready to merge

#595 [10.0][FIX] fix database transaction error on multi-languages anonymous carts
  shopinvader/services/cart.py
Labels: approved

#556 [10.0][IMP] shopinvader_locomotive_reset_password: Add password expiration management
  shopinvader_locomotive_reset_password/__manifest__.py
  shopinvader_locomotive_reset_password/data/ir_cron.xml
  shopinvader_locomotive_reset_password/data/mail_template.xml
  shopinvader_locomotive_reset_password/demo/shopinvader_backend.xml
  shopinvader_locomotive_reset_password/models/__init__.py
  shopinvader_locomotive_reset_password/models/shopinvader_backend.py
  shopinvader_locomotive_reset_password/readme/DESCRIPTION.rst
  shopinvader_locomotive_reset_password/tests/__init__.py
  shopinvader_locomotive_reset_password/tests/test_password_expired_reset.py
  shopinvader_locomotive_reset_password/views/shopinvader_backend.xml
  shopinvader_locomotive_reset_password/wizards/reset_password.py
Labels: approved, needs review, ready to merge

#561 [10.0][IMP] shopinvader: Add validator for contact types
  shopinvader/services/address.py
  shopinvader/tests/test_address.py
Labels: approved, enhancement, needs review, ready to merge

#563 [10.0] shopinvader.partner: switch to ondelete=restrict
  shopinvader/models/shopinvader_partner.py
Labels: approved, enhancement, needs review, ready to merge

#560 [10.0][FIX] shopinvader: Shopinvader Manager inherits from queue manager
  shopinvader/migrations/10.0.2.7.1/post-migrate.py
  shopinvader/security/shopinvader_security.xml
Labels: approved, enhancement, ready to merge

#467 [10.0][UPD] update with shopinvader invoice payment
  shopinvader_invoice/services/invoice.py
  shopinvader_invoice/tests/common.py
  shopinvader_invoice/tests/test_invoice_service.py
Labels: approved, ready to merge

#449 [10.0][UPD] shopinvader: force update pricelist and prices
  shopinvader/__manifest__.py
  shopinvader/data/ir_cron.xml
  shopinvader/models/sale.py
  shopinvader/models/shopinvader_backend.py
  shopinvader/tests/common.py
  shopinvader/tests/test_sale.py
  shopinvader_promotion_rule/models/__init__.py
  shopinvader_promotion_rule/models/shopinvader_backend.py
Labels: approved, needs review, ready to merge

#553 [10.0][FIX] shopinvader_sale_profile: Export default role if no profile
  shopinvader_sale_profile/components/__init__.py
  shopinvader_sale_profile/components/shopinvader_partner_export_mapper.py
  shopinvader_sale_profile/components/shopinvader_sale_profile_listener.py
  shopinvader_sale_profile/tests/__init__.py
  shopinvader_sale_profile/tests/test_shopinvader_partner.py
Labels: approved, ready to merge

#584 [10.0][CHG]shopinvader_invoice: add signed amount in response
  shopinvader_invoice/services/invoice.py
  shopinvader_invoice/tests/common.py
Labels: approved, enhancement, ready to merge

#596 [10.0][CHG] being able to make the difference between an update done by the customer and update done internally in Odoo
  shopinvader/models/__init__.py
  shopinvader/models/sale.py
  shopinvader/models/track_external_mixin.py
  shopinvader/services/service.py
  shopinvader/tests/common.py
  shopinvader/tests/test_cart.py
  shopinvader/tests/test_cart_item.py
  shopinvader_cart_expiry/models/shopinvader_backend.py
  shopinvader_cart_expiry/tests/test_cart_expiry.py
  shopinvader_pending_cart_reminder/models/sale_order.py
  shopinvader_pending_cart_reminder/tests/test_sale_order.py
Labels: approved

#558 [10.0][IMP] shopinvader: Allow to copy a previous sale
  .isort.cfg
  shopinvader/services/cart.py
  shopinvader/tests/__init__.py
  shopinvader/tests/test_cart_copy.py
  shopinvader_delivery_carrier/services/cart.py
Labels: approved, needs review, ready to merge
