Repository shopinvader/odoo-shopinvader, pull requests merged in 2020-10, with the labels that each got.

#781 [13.0][FWD] Add backend invoice options
  shopinvader/models/shopinvader_backend.py
  shopinvader/services/abstract_download.py
  shopinvader/services/invoice.py
  shopinvader/services/sale.py
  shopinvader/tests/test_invoice.py
  shopinvader/views/shopinvader_backend_view.xml
Labels: 13.0, approved, bot is merging ⏳

#793 [ADD][10.0] add total without shipping and without discount in cart service response
  shopinvader_delivery_carrier/services/abstract_sale.py
  shopinvader_delivery_carrier/tests/test_carrier.py
Labels: approved, bot is merging ⏳

#794 [13.0] black upgrade 19.10b0
  .pre-commit-config.yaml
  shopinvader/models/shopinvader_variant.py
Labels: approved, bot is merging ⏳

#796 [10.0] black upgrade 19.10b0
  .pre-commit-config.yaml
  shopinvader/models/shopinvader_variant.py
Labels: bot is merging ⏳

#797 [13.0] product.filter test coverage and fixes
  shopinvader/__manifest__.py
  shopinvader/models/product_filter.py
  shopinvader/tests/__init__.py
  shopinvader/tests/test_product.py
  shopinvader/tests/test_product_filter.py
  shopinvader/views/product_filter_view.xml
  shopinvader/views/product_view.xml
Labels: approved, bot is merging ⏳

#798 [10.0][IMP] shopinvader_elastic_search: Fix pre-commit errors in some…
  shopinvader_elasticsearch/tests/test_shopinvader_elasticsearch.py
Labels: bot is merging ⏳, enhancement
