Repository shopinvader/odoo-shopinvader, pull requests merged in 2020-09, with the labels that each got.

#761 [12.0][PORT] 458 from 10.0
  shopinvader_search_engine/tests/__init__.py
  shopinvader_search_engine/tests/test_action_server.py
  shopinvader_search_engine/views/product_category_view.xml
  shopinvader_search_engine/views/product_view.xml
Labels: bot is merging ⏳

#680 [IMP] add code in api for state and country in address
  shopinvader/services/address.py
Labels: 10.0, approved, bot is merging ⏳, needs review, ready to merge

#762 [12.0][PORT] 627 from 10.0
  shopinvader_locomotive/component/shopinvader_site_export_mapper.py
  shopinvader_locomotive/tests/test_backend.py
Labels: bot is merging ⏳

#763 [12.0][PORT] 621 from 10.0
  shopinvader/services/sale.py
Labels: bot is merging ⏳

#765 [13.0][PORT] 651 from 10.0
  shopinvader_sale_profile/models/shopinvader_partner.py
  shopinvader_sale_profile/tests/test_shopinvader_partner.py
Labels: bot is merging ⏳

#726 [12.0][BKP] #704 Fix call to ir.config_parameter using sudo
  shopinvader/models/shopinvader_config_settings.py
Labels: bot is merging ⏳, enhancement, needs review

#764 [12.0][PORT] 651 from 10.0
  shopinvader_sale_profile/models/shopinvader_partner.py
  shopinvader_sale_profile/tests/test_shopinvader_partner.py
Labels: bot is merging ⏳

#767 [12.0][PORT] 606 from 10.0
  shopinvader_delivery_carrier/readme/USAGE.rst
  shopinvader_delivery_carrier/services/delivery_carrier.py
  shopinvader_delivery_carrier/tests/test_delivery_carrier.py
Labels: bot is merging ⏳

#770 [13.0][PORT] 467 from 10.0
  shopinvader_invoice/services/invoice.py
  shopinvader_invoice/tests/common.py
  shopinvader_invoice/tests/test_invoice_service.py
Labels: bot is merging ⏳

#739 [12.0][PORT] 417 from 10.0
  shopinvader_delivery_carrier/__manifest__.py
  shopinvader_delivery_carrier/services/abstract_sale.py
  shopinvader_delivery_carrier/services/delivery_carrier.py
  shopinvader_delivery_carrier/tests/common.py
  shopinvader_delivery_carrier/tests/test_carrier.py
  shopinvader_delivery_carrier/tests/test_delivery_carrier.py
Labels: 12.0, bot is merging ⏳, forwardport, needs review

#769 [12.0][PORT] 707 from 13.0
  shopinvader/controllers/main.py
  shopinvader/services/__init__.py
  shopinvader/services/abstract_download.py
  shopinvader/services/invoice.py
  shopinvader/services/sale.py
  shopinvader/tests/common.py
  shopinvader/tests/test_invoice.py
  shopinvader/tests/test_sale.py
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_delivery_carrier/tests/test_delivery_service.py
  shopinvader_quotation/models/sale.py
  shopinvader_quotation/services/quotation.py
  shopinvader_quotation/tests/__init__.py
  shopinvader_quotation/tests/test_quotation_download.py
Labels: bot is merging ⏳

#751 Checkout address: do not wipe invoice address by default
  shopinvader/models/shopinvader_backend.py
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
  shopinvader/views/shopinvader_backend_view.xml
Labels: bot is merging ⏳, needs review

#768 [13.0] s_customer_multi_user: refactor is_invader_user
  shopinvader_customer_multi_user/__manifest__.py
  shopinvader_customer_multi_user/controllers/main.py
  shopinvader_customer_multi_user/migrations/13.0.1.1.0/pre-migrate.py
  shopinvader_customer_multi_user/models/res_partner.py
  shopinvader_customer_multi_user/models/shopinvader_partner.py
  shopinvader_customer_multi_user/services/customer.py
  shopinvader_customer_multi_user/tests/test_multi_user.py
  shopinvader_customer_multi_user/views/partner_view.xml
  shopinvader_customer_multi_user/views/shopinvader_partner_view.xml
Labels: 13.0, bot is merging ⏳, needs review
