Repository shopinvader/odoo-shopinvader, pull requests merged in 2020-05, with the labels that each got.

#616 [12.0][IMP] shopinvader_elasticsearch - change demo index
  shopinvader_elasticsearch/demo/index_config_demo.xml
Labels: 12.0, approved

#360 [10.0][FIX] Fix delete synchronisation
  shopinvader/models/product_product.py
  shopinvader/models/shopinvader_product.py
  shopinvader_search_engine/tests/__init__.py
  shopinvader_search_engine/tests/test_delete_product.py
Labels: 10.0, bot is merging ⏳, enhancement, needs review

#632 [10.0][FIX] pylint configuration for mandatory checks
  .pylintrc-mandatory
Labels: approved, bot is merging ⏳

#630 [13.0][FIX] shopinvader_delivery_carrier: Fix simulation + wrong compute
  shopinvader_delivery_carrier/models/delivery_carrier.py
  shopinvader_delivery_carrier/models/sale.py
  shopinvader_delivery_carrier/tests/test_delivery_carrier.py
Labels: 13.0, approved, bot is merging ⏳, needs review

#629 [10.0][IMP] shopinvader: Minimum Cerberus version
  setup/shopinvader/setup.py
Labels: 10.0, bot is merging ⏳, enhancement, needs review

#627 [10.0][IMP] shopinvader_locomotive: Improve metadata
  shopinvader_locomotive/component/mapper.py
  shopinvader_locomotive/tests/test_backend.py
Labels: 10.0, approved, bot is merging ⏳, needs review

#636 [10.0][FIX] - shopinvader_delivery_carrier - flake8 fix
  shopinvader_delivery_carrier/models/stock_picking.py
Labels: approved, bot is merging ⏳, enhancement, ready to merge

#641 [PATCH] pin flake8
  .pre-commit-config.yaml
Labels: bot is merging ⏳, enhancement

#640 [PATCH] pin flake8
  .pre-commit-config.yaml
Labels: bot is merging ⏳, enhancement

#642 [PATCH] pin flake8
  .pre-commit-config.yaml
Labels: bot is merging ⏳, enhancement

#605 [12.0][MIG] shopinvader_multi_category
  shopinvader_multi_category/__manifest__.py
  shopinvader_multi_category/readme/CONTRIBUTORS.rst
Labels: 12.0, approved, bot is merging ⏳, migration, needs review, ready to merge

#633 [MIG] 12.0 shopinvader_sale_profile
  shopinvader_sale_profile/README.rst
  shopinvader_sale_profile/__manifest__.py
  shopinvader_sale_profile/components/__init__.py
  shopinvader_sale_profile/components/shopinvader_partner_export_mapper.py
  shopinvader_sale_profile/components/shopinvader_sale_profile_listener.py
  shopinvader_sale_profile/services/shopinvader_customer_service.py
  shopinvader_sale_profile/static/description/index.html
  shopinvader_sale_profile/tests/__init__.py
  shopinvader_sale_profile/tests/test_shopinvader_partner.py
  shopinvader_sale_profile/views/res_partner.xml
  shopinvader_sale_profile/views/shopinvader_backend.xml
Labels: 12.0, approved, bot is merging ⏳, needs review, ready to merge

#621 [10.0][FIX] shopinvader: sale service should return so linked to child partners
  shopinvader/services/sale.py
Labels: 10.0, approved, bot is merging ⏳, ready to merge

#644 [12.0][PORT] #577 from 10.0: Fix missing parameters into some search validator
  shopinvader/services/address.py
  shopinvader/services/sale.py
  shopinvader/services/service.py
  shopinvader/tests/test_address.py
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_invoice/services/invoice.py
Labels: bot is merging ⏳, forwardport, needs review

#458 [10.0][FIX] action server in tree view must play on all selected records
  shopinvader_search_engine/tests/__init__.py
  shopinvader_search_engine/tests/test_action_server.py
  shopinvader_search_engine/views/product_category_view.xml
  shopinvader_search_engine/views/product_view.xml
Labels: 10.0, approved, bot is merging ⏳, needs review, ready to merge

#639 [13.0][PORT] #577 from 10.0: Fix missing parameters into some search validator
  shopinvader/services/address.py
  shopinvader/services/sale.py
  shopinvader/services/service.py
  shopinvader/tests/test_address.py
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_invoice/services/invoice.py
Labels: bot is merging ⏳, forwardport, needs review

#649 [12.0][PORT] 563 from 10.0: shopinvader.partner: switch to ondelete=restrict
  shopinvader/models/shopinvader_partner.py
Labels: bot is merging ⏳, forwardport, needs review

#648 [13.0][PORT] 563 from 10.0: shopinvader.partner: switch to ondelete=restrict
  shopinvader/models/shopinvader_partner.py
Labels: bot is merging ⏳, forwardport, needs review

#638 [12.0][FWD] Add translated label of selection fields into returned js…
  shopinvader/services/abstract_sale.py
  shopinvader/services/service.py
  shopinvader/tests/common.py
  shopinvader/tests/test_sale.py
  shopinvader_invoice/services/invoice.py
  shopinvader_invoice/tests/test_invoice_service.py
Labels: bot is merging ⏳, forwardport

#645 [13.0][FWD] Add translated label of selection fields into returned js
  shopinvader/services/abstract_sale.py
  shopinvader/services/service.py
  shopinvader/tests/common.py
  shopinvader/tests/test_sale.py
  shopinvader_invoice/services/invoice.py
  shopinvader_invoice/tests/test_invoice_service.py
Labels: bot is merging ⏳, forwardport, needs review

#643 [12.0][FWD] Fix delete synchronisation
  shopinvader/models/product_product.py
  shopinvader/models/shopinvader_product.py
  shopinvader_search_engine/tests/__init__.py
  shopinvader_search_engine/tests/test_delete_product.py
Labels: bot is merging ⏳, forwardport, needs review

#646 [13.0][FWD] Fix delete synchronisation
  shopinvader/models/product_product.py
  shopinvader/models/shopinvader_product.py
  shopinvader_search_engine/tests/__init__.py
  shopinvader_search_engine/tests/test_delete_product.py
Labels: bot is merging ⏳, forwardport, needs review

#658 [10.0][IMP] Travis tests
  .travis.yml
Labels: bot is merging ⏳, enhancement

#659 [12.0][IMP] Travis tests
  .travis.yml
Labels: bot is merging ⏳

#660 [13.0][IMP] Travis tests
  .travis.yml
Labels: bot is merging ⏳

#631 [10.0][ADD] Add shopinvader_membership
  setup/shopinvader_membership/odoo/__init__.py
  setup/shopinvader_membership/odoo/addons/__init__.py
  setup/shopinvader_membership/odoo/addons/shopinvader_membership
  setup/shopinvader_membership/setup.py
  shopinvader_membership/README.rst
  shopinvader_membership/__init__.py
  shopinvader_membership/__manifest__.py
  shopinvader_membership/readme/CONTRIBUTORS.rst
  shopinvader_membership/readme/DESCRIPTION.rst
  shopinvader_membership/services/__init__.py
  shopinvader_membership/services/membership.py
  shopinvader_membership/static/description/icon.png
  shopinvader_membership/static/description/index.html
  shopinvader_membership/tests/__init__.py
  shopinvader_membership/tests/test_membership_service.py
Labels: 10.0, approved, bot is merging ⏳, needs review, ready to merge

#635 [13.0][MIG] shopinvader_guest_mode, shopinvader_locomotive_guest_mode
  shopinvader_guest_mode/__manifest__.py
  shopinvader_guest_mode/models/shopinvader_backend.py
  shopinvader_guest_mode/models/shopinvader_partner.py
  shopinvader_guest_mode/services/guest_service.py
  shopinvader_guest_mode/tests/test_shopinvader_partner.py
  shopinvader_locomotive_guest_mode/__manifest__.py
  shopinvader_locomotive_guest_mode/models/res_partner.py
Labels: bot is merging ⏳, migration, needs review

#655 [12.0][PORT] #558 from 10.0 to 12.0: Allow to copy a previous sale
  .isort.cfg
  shopinvader/services/cart.py
  shopinvader/tests/__init__.py
  shopinvader/tests/test_cart_copy.py
  shopinvader_delivery_carrier/services/cart.py
Labels: bot is merging ⏳, forwardport, needs review

#654 [13.0][PORT] #558 from 10.0: Allow to copy a previous sale
  .isort.cfg
  shopinvader/services/cart.py
  shopinvader/tests/__init__.py
  shopinvader/tests/test_cart_copy.py
  shopinvader_delivery_carrier/services/cart.py
Labels: bot is merging ⏳, forwardport, needs review

#657 [13.0][PORT] #568 from 10.0: Fix shopinvader - Variants/Product active/inactive
  shopinvader/models/shopinvader_variant.py
  shopinvader/tests/test_product.py
Labels: bot is merging ⏳, forwardport, needs review

#656 [12.0][PORT] #568 from 10.0: Fix shopinvader - Variants/Product active/inactive
  shopinvader/models/shopinvader_variant.py
  shopinvader/tests/test_product.py
Labels: bot is merging ⏳, forwardport, needs review

#675 [12.0][PORT] #620 from 10.0: [FIX] shopinvader: unique constrains on email should only apply to active records
  shopinvader/models/res_partner.py
  shopinvader/tests/test_res_partner.py
Labels: approved, bot is merging ⏳, forwardport, needs review

#674 [13.0][PORT] #620 from 10.0: [FIX] shopinvader: unique constrains on email should only apply to active records
  shopinvader/models/res_partner.py
  shopinvader/tests/test_res_partner.py
Labels: approved, bot is merging ⏳, forwardport, needs review

#623 [12.0][FIX] fix missing note in return
  shopinvader/services/abstract_sale.py
  shopinvader/tests/test_cart.py
Labels: 12.0, approved, bot is merging ⏳, enhancement, forwardport, ready to merge

#678 [FIX] shopinvader_quotation: fix validator for search by using default one
  shopinvader_quotation/services/quotation.py
Labels: approved, bot is merging ⏳, enhancement

#661 [12.0][FWD] #449 shopinvader: force update pricelist and prices
  shopinvader/__manifest__.py
  shopinvader/data/ir_cron.xml
  shopinvader/models/sale.py
  shopinvader/models/shopinvader_backend.py
  shopinvader/tests/common.py
  shopinvader/tests/test_sale.py
  shopinvader_promotion_rule/models/__init__.py
  shopinvader_promotion_rule/models/shopinvader_backend.py
Labels: bot is merging ⏳, forwardport, needs review

#686 [13.0][PORT] 526 from 10.0
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_delivery_carrier/tests/test_delivery_service.py
Labels: 13.0, bot is merging ⏳, forwardport

#685 [12.0][PORT] 526 from 10.0
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_delivery_carrier/tests/test_delivery_service.py
Labels: 12.0, bot is merging ⏳, forwardport
