Repository shopinvader/odoo-shopinvader, pull requests merged in 2020-04, with the labels that each got.

#599 [10.0][FIX] shopinvader: Recompute also sale order lines
  shopinvader/models/sale.py
Labels: approved, bug, needs review, ready to merge

#598 [10.0][IMP] shopinvader/guest_mode: Allows to update profile in guest mode
  shopinvader/services/address.py
  shopinvader_guest_mode/services/__init__.py
  shopinvader_guest_mode/services/address.py
  shopinvader_guest_mode/tests/test_guest_service.py
Labels: approved, enhancement, needs review, ready to merge

#564 [10.0] shopinvader: improve shopinvader.partner views
  shopinvader/models/shopinvader_binding.py
  shopinvader/models/shopinvader_partner.py
  shopinvader/views/partner_view.xml
  shopinvader/views/shopinvader_partner_view.xml
  shopinvader_sale_profile/views/shopinvader_partner.xml
Labels: 10.0, needs review

#606 [10.0][FIX] fix incorrect api return
  shopinvader_delivery_carrier/readme/USAGE.rst
  shopinvader_delivery_carrier/services/delivery_carrier.py
  shopinvader_delivery_carrier/tests/test_delivery_carrier.py
Labels: 10.0, approved, needs review, ready to merge

#290 [10.0][FIX] remove carrier_id when the shipping address is modified
  shopinvader_delivery_carrier/services/cart.py
  shopinvader_delivery_carrier/tests/test_carrier.py
Labels: 10.0, approved, needs review, ready to merge

#612 [10.0][FIX] fix missing note in return
  shopinvader/services/abstract_sale.py
  shopinvader/tests/test_cart.py
Labels: approved, enhancement, needs review

#608 [10.0][FIX] shopinvader: Allow to bind partner to different backends
  shopinvader/__manifest__.py
  shopinvader/demo/backend_demo.xml
  shopinvader/demo/res_company.xml
  shopinvader/tests/common.py
  shopinvader/tests/test_shopinvader_partner_binding.py
  shopinvader/wizards/shopinvader_partner_binding_line.py
Labels: approved, enhancement, needs review, ready to merge

#417 [IMP] add carrier code into api response
  shopinvader_delivery_carrier/services/abstract_sale.py
  shopinvader_delivery_carrier/services/delivery_carrier.py
  shopinvader_delivery_carrier/tests/common.py
  shopinvader_delivery_carrier/tests/test_carrier.py
  shopinvader_delivery_carrier/tests/test_delivery_carrier.py
Labels: 10.0, needs review

#579 [12.0][FIX]shopinvader, fix bind products and bind categories buttons
  shopinvader/readme/CONTRIBUTORS.rst
  shopinvader/wizards/shopinvader_category_binding_wizard.py
  shopinvader/wizards/shopinvader_variant_binding_wizard.py
Labels: 12.0, approved, bug, ready to merge

#604 [12.0][FIX] shopinvader wrong variable was used for categories
  shopinvader/models/shopinvader_product.py
Labels: 12.0, approved, ready to merge

#603 [12.0][MIG] shopinvader_product_stock_state
  shopinvader_product_stock_state/__manifest__.py
  shopinvader_product_stock_state/models/shopinvader_variant.py
  shopinvader_product_stock_state/readme/CONTRIBUTORS.rst
  shopinvader_product_stock_state/readme/CREDITS.rst
  shopinvader_product_stock_state/readme/DESCRIPTION.rst
  shopinvader_product_stock_state/readme/USAGE.rst
  shopinvader_product_stock_state/tests/test_product.py
Labels: 12.0, approved

#617 [12.0][IMP] update demo data as doc have changed
  shopinvader_locomotive/demo/backend_demo.xml
  shopinvader_locomotive/tests/test_backend.py
  shopinvader_locomotive/tests/test_search_engine_site_export.py
  shopinvader_locomotive_guest_mode/tests/test_backend.py
Labels: 12.0

#620 [FIX] shopinvader: unique constrains on email should only apply to active records
  shopinvader/models/res_partner.py
  shopinvader/tests/test_res_partner.py
Labels: 10.0

#607 [10.0][FIX] fix issue when creating binding from the main record
  .isort.cfg
  base_url/models/abstract_url.py
  base_url/tests/models.py
  base_url/tests/models_mixin.py
  base_url/tests/test_abstract_url.py
  test-requirements.txt
Labels: 10.0, approved, bug, needs review, ready to merge

#622 Acsone 10.0 force technical user recompute export
  shopinvader_search_engine/__manifest__.py
  shopinvader_search_engine/models/shopinvader_backend.py
Labels: 10.0

#515 [10.0][IMP] Use the technical user to recompute and export
  shopinvader_search_engine/__manifest__.py
  shopinvader_search_engine/models/shopinvader_backend.py
  shopinvader_search_engine/tests/__init__.py
  shopinvader_search_engine/tests/test_shopinvader_backend.py
Labels: 10.0, WIP, needs review

#582 13.0 Migrate shopinvader_lead
  shopinvader_lead/README.rst
  shopinvader_lead/__manifest__.py
  shopinvader_lead/static/description/index.html
Labels: 13.0, approved, bot is merging ⏳, needs review, ready to merge
