Repository shopinvader/odoo-shopinvader, pull requests merged in 2020-07, with the labels that each got.

#698 [12.0][FIX] product_stock_state: fix no qty when stock is 0
  shopinvader_product_stock_state/models/shopinvader_variant.py
  shopinvader_product_stock_state/tests/test_product.py
Labels: 12.0, bot is merging ⏳

#717 [10.0][ADD] shopinvader_membership - get membership products and subscribe
  shopinvader_membership/services/__init__.py
  shopinvader_membership/services/membership.py
  shopinvader_membership/services/membership_product.py
  shopinvader_membership/tests/__init__.py
  shopinvader_membership/tests/test_membership_product_service.py
  shopinvader_membership/tests/test_membership_service.py
Labels: approved, bot is merging ⏳

#544 [13.0] Add shopinvader_notification_default
  oca_dependencies.txt
  shopinvader/models/shopinvader_backend.py
  shopinvader/models/shopinvader_notification.py
  shopinvader/views/shopinvader_backend_view.xml
  shopinvader_notification_default/README.rst
  shopinvader_notification_default/__init__.py
  shopinvader_notification_default/__manifest__.py
  shopinvader_notification_default/data/email_template.xml
  shopinvader_notification_default/data/shopinvader_notification.xml
  shopinvader_notification_default/readme/CONTRIBUTORS.rst
  shopinvader_notification_default/readme/CREDITS.rst
  shopinvader_notification_default/readme/DESCRIPTION.rst
  shopinvader_notification_default/static/description/index.html
  shopinvader_notification_default/templates/cart_email.xml
  shopinvader_notification_default/templates/customer_address_email.xml
  shopinvader_notification_default/templates/customer_profile_email.xml
  shopinvader_notification_default/templates/invoice_email.xml
  shopinvader_notification_default/templates/layout.xml
  shopinvader_notification_default/templates/sale_email.xml
Labels: 13.0, WIP, bot is merging ⏳

#711 s_locomotive_algolia: do not expose private key
  shopinvader_locomotive_algolia/__init__.py
  shopinvader_locomotive_algolia/__manifest__.py
  shopinvader_locomotive_algolia/component/shopinvader_site_export_mapper.py
  shopinvader_locomotive_algolia/models/__init__.py
  shopinvader_locomotive_algolia/models/se_backend_algolia.py
  shopinvader_locomotive_algolia/tests/test_search_engine_site_export.py
  shopinvader_locomotive_algolia/views/se_backend_algolia.xml
Labels: 13.0, approved, bot is merging ⏳, ready to merge

#719 Fix odoo warning about _company_default_get deprecated
  shopinvader/models/shopinvader_backend.py
Labels: bot is merging ⏳

#716 [FIX] shopinvader: prevent to trigger a useless process if product name is not updated
  shopinvader/models/product_template.py
Labels: approved, bot is merging ⏳

#705 [13.0] shopinvader: fix category automatic url compute
  base_url/models/abstract_url.py
  shopinvader/models/shopinvader_category.py
  shopinvader/tests/__init__.py
  shopinvader/tests/test_notification.py
  shopinvader/tests/test_salesman_notification.py
  shopinvader/tests/test_shopinvader_category.py
  shopinvader/tests/test_shopinvader_category_binding_wizard.py
Labels: 13.0, bot is merging ⏳, needs review

#721 Fix recompute product/category server actions
  shopinvader_search_engine/views/product_category_view.xml
  shopinvader_search_engine/views/product_view.xml
Labels: approved, bot is merging ⏳

#707 [13.0][FWD] shopinvader - Document generate/download (pdf)
  shopinvader/controllers/main.py
  shopinvader/services/__init__.py
  shopinvader/services/abstract_download.py
  shopinvader/services/invoice.py
  shopinvader/services/sale.py
  shopinvader/tests/common.py
  shopinvader/tests/test_invoice.py
  shopinvader/tests/test_sale.py
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_delivery_carrier/tests/test_delivery_service.py
  shopinvader_quotation/models/sale.py
  shopinvader_quotation/services/quotation.py
  shopinvader_quotation/tests/__init__.py
  shopinvader_quotation/tests/test_quotation_download.py
Labels: 13.0, approved, bot is merging ⏳, forwardport, ready to merge

#708 [13.0][MIG] shopinvader_product_template_multi_link
  oca_dependencies.txt
  shopinvader_product_template_multi_link/__manifest__.py
  shopinvader_product_template_multi_link/models/shopinvader_product.py
  shopinvader_product_template_multi_link/tests/test_product.py
Labels: 13.0, approved, bot is merging ⏳, ready to merge

#720 Add conf for root category level
  shopinvader/models/shopinvader_backend.py
  shopinvader/tests/test_backend.py
  shopinvader/views/shopinvader_backend_view.xml
Labels: 13.0, approved, bot is merging ⏳, enhancement

#697 [13.0] Wishlist: support item ordering
  shopinvader_wishlist/services/wishlist.py
  shopinvader_wishlist/tests/test_wishlist.py
Labels: 13.0, approved, bot is merging ⏳, needs review

#723 Fix manager role for admin
  shopinvader/security/shopinvader_security.xml
Labels: 13.0, approved, bot is merging ⏳, bug
