Repository shopinvader/odoo-shopinvader, pull requests merged in 2020-06, with the labels that each got.

#650 [13.0][PORT] #595 from 10.0: [FIX] fix database transaction error on multi-languages anonymous carts
  shopinvader/services/cart.py
Labels: bot is merging ⏳, forwardport, needs review

#684 [12.0][FWD] #595 fix database transaction error on multi-languages anonymo…
  shopinvader/services/cart.py
Labels: bot is merging ⏳, forwardport, needs review

#653 [10.0][ADD] Allow quotation download
  shopinvader_quotation/services/quotation.py
  shopinvader_quotation/tests/__init__.py
  shopinvader_quotation/tests/test_quotation_download.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#601 shopinvader_locomotive: split test backend common case
  shopinvader_locomotive/tests/test_backend.py
Labels: 13.0, approved, bot is merging ⏳, ready to merge

#669 [12.0][PORT] #607 and #340 port from 10.0: [FIX] fix issue when creating binding from the main record
  .isort.cfg
  base_url/models/abstract_url.py
  base_url/tests/models.py
  base_url/tests/models_mixin.py
  base_url/tests/test_abstract_url.py
  shopinvader/models/shopinvader_category.py
  shopinvader/models/shopinvader_product.py
  shopinvader/models/tools.py
  test-requirements.txt
Labels: bot is merging ⏳, forwardport, needs review

#668 [13.0][PORT] #607 port from 10.0: [FIX] fix issue when creating binding from the main record
  .isort.cfg
  base_url/models/abstract_url.py
  base_url/tests/models.py
  base_url/tests/models_mixin.py
  base_url/tests/test_abstract_url.py
  shopinvader/models/shopinvader_category.py
  shopinvader/models/shopinvader_product.py
  shopinvader/models/tools.py
  test-requirements.txt
Labels: bot is merging ⏳, forwardport, needs review

#647 [10.0][ADD] Add shopinvader_sale_communication
  setup/shopinvader_sale_communication/odoo/__init__.py
  setup/shopinvader_sale_communication/odoo/addons/__init__.py
  setup/shopinvader_sale_communication/odoo/addons/shopinvader_sale_communication
  setup/shopinvader_sale_communication/setup.py
  shopinvader_sale_communication/README.rst
  shopinvader_sale_communication/__init__.py
  shopinvader_sale_communication/__manifest__.py
  shopinvader_sale_communication/models/__init__.py
  shopinvader_sale_communication/models/sale_order.py
  shopinvader_sale_communication/readme/CONTRIBUTORS.rst
  shopinvader_sale_communication/readme/DESCRIPTION.rst
  shopinvader_sale_communication/services/__init__.py
  shopinvader_sale_communication/services/abstract_sale.py
  shopinvader_sale_communication/services/cart.py
  shopinvader_sale_communication/tests/__init__.py
  shopinvader_sale_communication/tests/test_cart.py
  shopinvader_sale_communication/tests/test_sale.py
  shopinvader_sale_communication/views/sale_order.xml
Labels: approved, bot is merging ⏳, needs review, question, ready to merge

#677 [12.0][PORT] #622 port from 10.0: force technical user recompute export
  shopinvader_search_engine/__manifest__.py
  shopinvader_search_engine/models/shopinvader_backend.py
  shopinvader_search_engine/tests/__init__.py
Labels: bot is merging ⏳, forwardport

#681 [13.0][ENH] shopinvader: Easier product configuration access
  shopinvader/views/shopinvader_variant_view.xml
Labels: approved, bot is merging ⏳, enhancement, ready to merge

#634 [FIX] API convention
  README.md
  shopinvader/services/invoice.py
  shopinvader/tests/test_invoice.py
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_delivery_carrier/services/delivery_carrier.py
  shopinvader_delivery_carrier/tests/test_delivery_carrier.py
  shopinvader_invoice/tests/common.py
  shopinvader_invoice/tests/test_invoice_service.py
  shopinvader_lead/services/lead.py
  shopinvader_lead/tests/test_lead.py
Labels: 10.0, approved, bot is merging ⏳, needs review, ready to merge

#676 [13.0][PORT] #622 port from 10.0: force technical user recompute export
  shopinvader_algolia/__manifest__.py
  shopinvader_algolia/tests/test_export.py
  shopinvader_search_engine/__manifest__.py
  shopinvader_search_engine/models/shopinvader_backend.py
Labels: bot is merging ⏳, forwardport, needs review

#691 [12.0][FWD] #564 shopinvader: improve shopinvader.partner views
  shopinvader/models/shopinvader_binding.py
  shopinvader/models/shopinvader_partner.py
  shopinvader/views/partner_view.xml
  shopinvader/views/shopinvader_partner_view.xml
  shopinvader_sale_profile/views/shopinvader_partner.xml
Labels: bot is merging ⏳, forwardport, needs review

#666 [13.0][PORT] #560 from 10.0: shopinvader: Shopinvader Manager inherits from queue manager
  shopinvader/__manifest__.py
  shopinvader/migrations/13.0.1.7.0/post-migrate.py
  shopinvader/security/shopinvader_security.xml
Labels: bot is merging ⏳, forwardport, needs review

#692 [13.0][FWD] #564 shopinvader: improve shopinvader.partner views
  shopinvader/models/shopinvader_binding.py
  shopinvader/models/shopinvader_partner.py
  shopinvader/views/partner_view.xml
  shopinvader/views/shopinvader_partner_view.xml
  shopinvader_sale_profile/views/shopinvader_partner.xml
Labels: bot is merging ⏳, forwardport, needs review

#673 [12.0][PORT] #560 from 10.0: shopinvader: Shopinvader Manager inherits from queue manager
  shopinvader/__manifest__.py
  shopinvader/migrations/12.0.3.13.0/post-migrate.py
  shopinvader/security/shopinvader_security.xml
Labels: bot is merging ⏳, forwardport, needs review

#688 [13.0][PORT] 535 from 10.0
  .pre-commit-config.yaml
  shopinvader_cart_expiry/models/shopinvader_backend.py
  shopinvader_cart_expiry/tests/test_cart_expiry.py
Labels: 13.0, bot is merging ⏳, forwardport

#687 [12.0][PORT] 535 from 10.0
  .pre-commit-config.yaml
  shopinvader_cart_expiry/models/shopinvader_backend.py
  shopinvader_cart_expiry/tests/test_cart_expiry.py
Labels: 12.0, bot is merging ⏳, forwardport

#699 [12.0][PORT] 572 from 10.0
  setup/shopinvader_category_image_for_product/odoo/__init__.py
  setup/shopinvader_category_image_for_product/odoo/addons/__init__.py
  setup/shopinvader_category_image_for_product/odoo/addons/shopinvader_category_image_for_product
  setup/shopinvader_category_image_for_product/setup.py
  shopinvader_category_image_for_product/README.rst
  shopinvader_category_image_for_product/__init__.py
  shopinvader_category_image_for_product/__manifest__.py
  shopinvader_category_image_for_product/data/ir_export.xml
  shopinvader_category_image_for_product/models/__init__.py
  shopinvader_category_image_for_product/models/shopinvader_variant.py
  shopinvader_category_image_for_product/readme/CONTRIBUTORS.rst
  shopinvader_category_image_for_product/readme/DESCRIPTION.rst
Labels: bot is merging ⏳, forwardport

#701 [12.0][PORT] 512 from 10.0
  shopinvader_invoice/services/invoice.py
  shopinvader_invoice/tests/test_invoice_service.py
Labels: bot is merging ⏳, forwardport

#702 [13.0][PORT] 512 from 10.0
  shopinvader_invoice/services/invoice.py
  shopinvader_invoice/tests/test_invoice_service.py
Labels: bot is merging ⏳, forwardport

#704 [13.0] Fix call to ir.config_parameter using sudo
  shopinvader/models/shopinvader_config_settings.py
Labels: approved, bot is merging ⏳
