Repository shopinvader/odoo-shopinvader, pull requests merged in 2020-02, with the labels that each got.

#557 [MIG] shopinvader_delivery_carrier: Migration to 13.0
  shopinvader_delivery_carrier/__manifest__.py
  shopinvader_delivery_carrier/models/delivery_carrier.py
  shopinvader_delivery_carrier/models/sale.py
  shopinvader_delivery_carrier/models/stock_picking.py
  shopinvader_delivery_carrier/readme/CONTRIBUTORS.rst
  shopinvader_delivery_carrier/services/abstract_sale.py
  shopinvader_delivery_carrier/services/cart.py
  shopinvader_delivery_carrier/services/delivery_carrier.py
  shopinvader_delivery_carrier/tests/test_carrier.py
  shopinvader_delivery_carrier/tests/test_delivery_carrier.py
Labels: 13.0, needs review

#569 [12][FIX] shopinvader_guest_mode typo in description
  shopinvader_guest_mode/readme/DESCRIPTION.rst
Labels: 12.0

#562 [10.0][FIX] shopinvader_promotion_rule fix promotions applied
  shopinvader_promotion_rule/__init__.py
  shopinvader_promotion_rule/models/__init__.py
  shopinvader_promotion_rule/models/sale_order.py
  shopinvader_promotion_rule/tests/test_cart.py
Labels: approved, ready to merge

#568 [10.0][FIX] Fix shopinvader - Variants/Product active/inactive
  shopinvader/models/shopinvader_variant.py
  shopinvader/tests/test_product.py
Labels: 10.0, approved, enhancement, ready to merge
