Repository shopinvader/odoo-shopinvader, pull requests merged in 2020-11, with the labels that each got.

#788 [13.0] s_customer_multi_user: improve multi account behavior
  shopinvader/controllers/main.py
  shopinvader/models/res_partner.py
  shopinvader/services/address.py
  shopinvader/services/invoice.py
  shopinvader/services/sale.py
  shopinvader/services/service.py
  shopinvader/tests/test_shopinvader_partner_binding.py
  shopinvader_customer_multi_user/README.rst
  shopinvader_customer_multi_user/__init__.py
  shopinvader_customer_multi_user/__manifest__.py
  shopinvader_customer_multi_user/components/access_info.py
  shopinvader_customer_multi_user/controllers/__init__.py
  shopinvader_customer_multi_user/controllers/main.py
  shopinvader_customer_multi_user/migrations/13.0.1.2.0/post-migrate.py
  shopinvader_customer_multi_user/models/res_partner.py
  shopinvader_customer_multi_user/models/shopinvader_backend.py
  shopinvader_customer_multi_user/models/shopinvader_partner.py
  shopinvader_customer_multi_user/readme/CONTRIBUTORS.rst
  shopinvader_customer_multi_user/services/__init__.py
  shopinvader_customer_multi_user/services/address.py
  shopinvader_customer_multi_user/services/customer.py
  shopinvader_customer_multi_user/services/service.py
  shopinvader_customer_multi_user/tests/__init__.py
  shopinvader_customer_multi_user/tests/common.py
  shopinvader_customer_multi_user/tests/test_multi_user.py
  shopinvader_customer_multi_user/tests/test_multi_user_customer.py
  shopinvader_customer_multi_user/tests/test_multi_user_partner.py
  shopinvader_customer_multi_user/tests/test_multi_user_service_ctx.py
  shopinvader_customer_multi_user/tests/test_multi_user_service_partner_domain.py
  shopinvader_customer_multi_user/tests/test_multi_user_token.py
  shopinvader_customer_multi_user/views/partner_view.xml
  shopinvader_customer_multi_user/views/shopinvader_backend.xml
  shopinvader_customer_multi_user/views/shopinvader_partner_view.xml
  shopinvader_quotation/services/quotation.py
  shopinvader_wishlist/services/wishlist.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#780 [13.0][FIX] notification job access rights
  shopinvader/models/shopinvader_notification.py
Labels: bot is merging ⏳

#696 [13.0] Add shopinvader_locomotive_wishlist
  shopinvader_locomotive/tests/common.py
  shopinvader_locomotive/tests/test_backend.py
  shopinvader_locomotive/tests/test_search_engine_site_export.py
  shopinvader_locomotive_wishlist/__init__.py
  shopinvader_locomotive_wishlist/__manifest__.py
  shopinvader_locomotive_wishlist/components/__init__.py
  shopinvader_locomotive_wishlist/components/event_listeners.py
  shopinvader_locomotive_wishlist/components/shopinvader_partner_export_mapper.py
  shopinvader_locomotive_wishlist/readme/CONTRIBUTORS.rst
  shopinvader_locomotive_wishlist/readme/DESCRIPTION.rst
  shopinvader_locomotive_wishlist/tests/__init__.py
  shopinvader_locomotive_wishlist/tests/test_shopinvader_partner.py
Labels: 13.0, approved, bot is merging ⏳, ready to merge

#804 Avoid loading all translations for tests + fix pre-commit
  .isort.cfg
  .pre-commit-config.yaml
  .travis/travis_delete_algolia_index
  shopinvader/tests/common.py
  shopinvader/tests/test_backend.py
  shopinvader_guest_mode/migrations/12.0.1.0.0/pre-migrate.py
  shopinvader_locomotive_guest_mode/models/res_partner.py
  shopinvader_locomotive_wishlist/tests/test_shopinvader_partner.py
  shopinvader_product_template_multi_link/models/shopinvader_product.py
  shopinvader_product_template_multi_link/readme/DESCRIPTION.rst
  shopinvader_product_template_multi_link/tests/test_product.py
Labels: bot is merging ⏳

#710 shopinvader_product_stock*: Migration to 13.0
  .pre-commit-config.yaml
  product_stock_state/README.rst
  product_stock_state/__init__.py
  product_stock_state/__manifest__.py
  product_stock_state/demo/product_category.xml
  product_stock_state/demo/product_product.xml
  product_stock_state/demo/res_groups.xml
  product_stock_state/i18n/fr.po
  product_stock_state/models/__init__.py
  product_stock_state/models/product_category.py
  product_stock_state/models/product_product.py
  product_stock_state/models/product_template.py
  product_stock_state/models/res_company.py
  product_stock_state/models/sale_config_settings.py
  product_stock_state/security/res_groups.xml
  product_stock_state/static/description/product_product_tree.png
  product_stock_state/tests/__init__.py
  product_stock_state/tests/test_product_stock_state.py
  product_stock_state/views/product_category_view.xml
  product_stock_state/views/product_product_view.xml
  product_stock_state/views/product_template_view.xml
  product_stock_state/views/sale_config_settings_view.xml
  shopinvader_product_stock/__init__.py
  shopinvader_product_stock/__manifest__.py
  shopinvader_product_stock/hooks.py
  shopinvader_product_stock/models/product_product.py
  shopinvader_product_stock/models/shopinvader_backend.py
  shopinvader_product_stock/models/shopinvader_variant.py
  shopinvader_product_stock/models/stock_move.py
  shopinvader_product_stock/readme/CONTRIBUTORS.rst
  shopinvader_product_stock/tests/common.py
  shopinvader_product_stock/tests/test_product.py
  shopinvader_product_stock/tests/test_stock_move.py
  shopinvader_product_stock/views/shopinvader_backend.xml
  shopinvader_product_stock_state/README.rst
  shopinvader_product_stock_state/__manifest__.py
  shopinvader_product_stock_state/models/shopinvader_backend.py
  shopinvader_product_stock_state/models/shopinvader_variant.py
  shopinvader_product_stock_state/tests/test_product.py
  shopinvader_product_stock_state/views/shopinvader_backend.xml
Labels: 13.0, bot is merging ⏳, migration, needs review

#750 cart service: ease override of pricelist by partner
  shopinvader/models/shopinvader_backend.py
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#741 Improvements for search engine data check
  shopinvader_algolia/__manifest__.py
  shopinvader_algolia/views/shopinvader_variant_view.xml
  shopinvader_search_engine/tests/test_action_server.py
  shopinvader_search_engine/views/product_view.xml
Labels: bot is merging ⏳, needs review

#810 [13.0][PORT] 584 from 10.0
  shopinvader_invoice/services/invoice.py
  shopinvader_invoice/tests/common.py
Labels: bot is merging ⏳

#700 [13.0][PORT] 572 from 10.0
  setup/shopinvader_category_image_for_product/odoo/addons/shopinvader_category_image_for_product
  setup/shopinvader_category_image_for_product/setup.py
  shopinvader_category_image_for_product/README.rst
  shopinvader_category_image_for_product/__init__.py
  shopinvader_category_image_for_product/__manifest__.py
  shopinvader_category_image_for_product/data/ir_export.xml
  shopinvader_category_image_for_product/models/__init__.py
  shopinvader_category_image_for_product/models/shopinvader_variant.py
  shopinvader_category_image_for_product/readme/CONTRIBUTORS.rst
  shopinvader_category_image_for_product/readme/DESCRIPTION.rst
Labels: bot is merging ⏳, forwardport

#808 shopinvader: reduce test log noise
  shopinvader/tests/test_backend.py
  shopinvader/tests/test_cart.py
  shopinvader/tests/test_cart_copy.py
  shopinvader/tests/test_cart_item.py
  shopinvader/tests/test_customer.py
  shopinvader/tests/test_product.py
  shopinvader/tests/test_product_filter.py
  shopinvader/tests/test_sale.py
  shopinvader/tests/test_shopinvader_partner.py
  shopinvader/tests/test_shopinvader_variant_binding_wizard.py
  shopinvader/tests/test_shopinvader_variant_seo_title.py
Labels: bot is merging ⏳

#766 [13.0][PORT] 762 from 12.0
  shopinvader_locomotive/component/shopinvader_site_export_mapper.py
  shopinvader_locomotive/tests/test_backend.py
Labels: bot is merging ⏳, forwardport, needs review

#771 [13.0][PORT] 767 (606 V10) from 12.0
  shopinvader_delivery_carrier/readme/USAGE.rst
  shopinvader_delivery_carrier/services/delivery_carrier.py
  shopinvader_delivery_carrier/tests/test_delivery_carrier.py
Labels: bot is merging ⏳

#814 [13.0][PORT] 680 from 10.0
  shopinvader/services/address.py
Labels: bot is merging ⏳
