Repository shopinvader/odoo-shopinvader, pull requests merged in 2020-08, with the labels that each got.

#725 shopinvader_wishlist: allow bulk updates
  shopinvader_wishlist/services/wishlist.py
  shopinvader_wishlist/tests/test_wishlist.py
Labels: 13.0, bot is merging ⏳, enhancement, needs review

#693 [13.0] Add packaging for sale orders and wishlists
  shopinvader/services/abstract_sale.py
  shopinvader/services/cart.py
  shopinvader/tests/test_cart_item.py
  shopinvader_sale_packaging/__init__.py
  shopinvader_sale_packaging/__manifest__.py
  shopinvader_sale_packaging/data/ir_export_product.xml
  shopinvader_sale_packaging/models/__init__.py
  shopinvader_sale_packaging/models/shopinvader_variant.py
  shopinvader_sale_packaging/readme/CONTRIBUTORS.rst
  shopinvader_sale_packaging/readme/CREDITS.rst
  shopinvader_sale_packaging/readme/DESCRIPTION.rst
  shopinvader_sale_packaging/services/__init__.py
  shopinvader_sale_packaging/services/abstract_sale.py
  shopinvader_sale_packaging/services/cart.py
  shopinvader_sale_packaging/services/packaging_mixin.py
  shopinvader_sale_packaging/static/description/index.html
  shopinvader_sale_packaging/tests/__init__.py
  shopinvader_sale_packaging/tests/test_cart.py
  shopinvader_sale_packaging/tests/test_sale.py
  shopinvader_sale_packaging_wishlist/README.rst
  shopinvader_sale_packaging_wishlist/__init__.py
  shopinvader_sale_packaging_wishlist/__manifest__.py
  shopinvader_sale_packaging_wishlist/readme/CONTRIBUTORS.rst
  shopinvader_sale_packaging_wishlist/readme/CREDITS.rst
  shopinvader_sale_packaging_wishlist/readme/DESCRIPTION.rst
  shopinvader_sale_packaging_wishlist/services/__init__.py
  shopinvader_sale_packaging_wishlist/services/wishlist.py
  shopinvader_sale_packaging_wishlist/static/description/icon.png
  shopinvader_sale_packaging_wishlist/static/description/index.html
  shopinvader_sale_packaging_wishlist/tests/__init__.py
  shopinvader_sale_packaging_wishlist/tests/test_wishlist_packaging.py
  shopinvader_wishlist/services/wishlist.py
  shopinvader_wishlist/tests/test_wishlist.py
Labels: 13.0, approved, bot is merging ⏳, ready to merge

#706 [13.0] Improve and refactor shopinvader_import_image
  shopinvader_import_image/__init__.py
  shopinvader_import_image/__manifest__.py
  shopinvader_import_image/data/ir_cron.xml
  shopinvader_import_image/models/__init__.py
  shopinvader_import_image/models/import_image.py
  shopinvader_import_image/security/ir_model_access.xml
  shopinvader_import_image/tests/fixture/image_import_test.csv
  shopinvader_import_image/tests/test_import_image.py
  shopinvader_import_image/views/import_product_image_view.xml
  shopinvader_import_image/views/report_html.xml
  shopinvader_import_image/wizards/import_image.py
  shopinvader_import_image/wizards/import_product_image_view.xml
Labels: 13.0, approved, bot is merging ⏳, needs review, ready to merge

#740 sale service: expose client_order_ref
  shopinvader/demo/sale_demo.xml
  shopinvader/services/abstract_sale.py
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
  shopinvader/tests/test_sale.py
Labels: approved, bot is merging ⏳, needs review

#745 [12.0][FIX] Update cassette as now vies use https \o/
  shopinvader_partner_vat/tests/cassettes/failure.json
  shopinvader_partner_vat/tests/cassettes/success.json
Labels: 12.0, bot is merging ⏳

#746 [13.0][PORT] 745 from 12.0
  shopinvader_partner_vat/tests/cassettes/failure.json
  shopinvader_partner_vat/tests/cassettes/success.json
Labels: bot is merging ⏳

#737 s_locomotive: fix multilang site settings export
  shopinvader_locomotive/component/shopinvader_site_export_mapper.py
Labels: 13.0, bot is merging ⏳, bug, needs review

#718 Move tech_name field to server env mixin
  shopinvader/models/shopinvader_backend.py
Labels: bot is merging ⏳, needs review

#727 s_algolia: fix facet settings export
  shopinvader/models/product_filter.py
  shopinvader/tests/common.py
  shopinvader_algolia/models/se_index.py
  shopinvader_algolia/models/shopinvader_category.py
  shopinvader_algolia/models/shopinvader_product.py
  shopinvader_algolia/models/shopinvader_variant.py
  shopinvader_algolia/tests/test_export.py
Labels: 13.0, bot is merging ⏳, needs review

#733 [MIG] shopinvader_product_media: Migration to 13.0
  shopinvader_product_media/__manifest__.py
  shopinvader_product_media/data/ir_product_export.xml
Labels: 13.0, bot is merging ⏳, needs review

#734 IMP address: allow passing type + email, expose parent_id
  shopinvader/services/address.py
  shopinvader/services/customer.py
  shopinvader/tests/test_address.py
  shopinvader/tests/test_customer.py
Labels: 13.0, bot is merging ⏳, needs review

#735 [13.0] Allow sorting search results via `order` param
  shopinvader/services/service.py
  shopinvader/tests/test_sale.py
Labels: 13.0, bot is merging ⏳, needs review

#736 [ADD][13.0] s_delivery_carrier expose deliveries to sale service
  shopinvader_delivery_carrier/services/__init__.py
  shopinvader_delivery_carrier/services/sale.py
  shopinvader_delivery_carrier/tests/__init__.py
  shopinvader_delivery_carrier/tests/test_sale_service.py
Labels: 13.0, bot is merging ⏳

#749 [FIX] Update cassette as now vies use https \o/
  shopinvader_partner_vat/tests/cassettes/failure.json
  shopinvader_partner_vat/tests/cassettes/success.json
Labels: bot is merging ⏳

#651 [FIX] shopinvader_sale_profile: support profile without fiscal positions
  shopinvader_sale_profile/models/shopinvader_partner.py
  shopinvader_sale_profile/tests/test_shopinvader_partner.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#662 [FIX] 12.0 sale_profile customer creation pricelist
  shopinvader_sale_profile/services/shopinvader_customer_service.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#663 [FIX] 10.0 sale_profile customer creation pricelist
  shopinvader_sale_profile/services/shopinvader_customer_service.py
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#738 [FIX] remove useless code added during the forward port #661
  shopinvader/models/shopinvader_backend.py
Labels: 12.0, bot is merging ⏳, bug, forwardport

#752 [12.0][PORT] 426 from 10.0
  shopinvader_promotion_rule/services/cart.py
Labels: bot is merging ⏳

#753 [13.0][PORT] 426 from 10.0
  shopinvader_promotion_rule/services/cart.py
Labels: bot is merging ⏳

#615 [12.0][IMP] shopinvader_delivery_carrier change args order
  shopinvader_delivery_carrier/services/abstract_sale.py
Labels: 12.0, approved, bot is merging ⏳, ready to merge

#755 [13.0][PORT] 567 from 10.0
  setup/shopinvader_product_stock_assortment/odoo/__init__.py
  setup/shopinvader_product_stock_assortment/odoo/addons/__init__.py
  setup/shopinvader_product_stock_assortment/odoo/addons/shopinvader_product_stock_assortment
  setup/shopinvader_product_stock_assortment/setup.py
  shopinvader_product_stock_assortment/__init__.py
  shopinvader_product_stock_assortment/__manifest__.py
  shopinvader_product_stock_assortment/models/__init__.py
  shopinvader_product_stock_assortment/models/shopinvader_backend.py
  shopinvader_product_stock_assortment/tests/__init__.py
  shopinvader_product_stock_assortment/tests/test_product_auto_bind.py
Labels: bot is merging ⏳

#754 [12.0][PORT] 567 from 10.0
  setup/shopinvader_product_stock_assortment/odoo/__init__.py
  setup/shopinvader_product_stock_assortment/odoo/addons/__init__.py
  setup/shopinvader_product_stock_assortment/odoo/addons/shopinvader_product_stock_assortment
  setup/shopinvader_product_stock_assortment/setup.py
  shopinvader_product_stock_assortment/__init__.py
  shopinvader_product_stock_assortment/__manifest__.py
  shopinvader_product_stock_assortment/models/__init__.py
  shopinvader_product_stock_assortment/models/shopinvader_backend.py
  shopinvader_product_stock_assortment/tests/__init__.py
  shopinvader_product_stock_assortment/tests/test_product_auto_bind.py
Labels: bot is merging ⏳

#758 [12.0][PORT] 556 from 10.0
  shopinvader_locomotive_reset_password/__manifest__.py
  shopinvader_locomotive_reset_password/data/ir_cron.xml
  shopinvader_locomotive_reset_password/data/mail_template.xml
  shopinvader_locomotive_reset_password/demo/shopinvader_backend.xml
  shopinvader_locomotive_reset_password/models/__init__.py
  shopinvader_locomotive_reset_password/models/shopinvader_backend.py
  shopinvader_locomotive_reset_password/readme/DESCRIPTION.rst
  shopinvader_locomotive_reset_password/tests/__init__.py
  shopinvader_locomotive_reset_password/tests/test_password_expired_reset.py
  shopinvader_locomotive_reset_password/views/shopinvader_backend.xml
  shopinvader_locomotive_reset_password/wizards/reset_password.py
Labels: bot is merging ⏳

#759 [13.0][PORT] 556 from 10.0
  shopinvader_locomotive_reset_password/__manifest__.py
  shopinvader_locomotive_reset_password/data/ir_cron.xml
  shopinvader_locomotive_reset_password/data/mail_template.xml
  shopinvader_locomotive_reset_password/demo/shopinvader_backend.xml
  shopinvader_locomotive_reset_password/models/__init__.py
  shopinvader_locomotive_reset_password/models/shopinvader_backend.py
  shopinvader_locomotive_reset_password/readme/DESCRIPTION.rst
  shopinvader_locomotive_reset_password/tests/__init__.py
  shopinvader_locomotive_reset_password/tests/test_password_expired_reset.py
  shopinvader_locomotive_reset_password/views/shopinvader_backend.xml
  shopinvader_locomotive_reset_password/wizards/reset_password.py
Labels: bot is merging ⏳

#760 [13.0][PORT] 633 from 12.0
  shopinvader_sale_profile/README.rst
  shopinvader_sale_profile/__manifest__.py
  shopinvader_sale_profile/components/__init__.py
  shopinvader_sale_profile/components/shopinvader_partner_export_mapper.py
  shopinvader_sale_profile/components/shopinvader_sale_profile_listener.py
  shopinvader_sale_profile/services/shopinvader_customer_service.py
  shopinvader_sale_profile/static/description/index.html
  shopinvader_sale_profile/tests/__init__.py
  shopinvader_sale_profile/tests/test_shopinvader_partner.py
  shopinvader_sale_profile/views/res_partner.xml
  shopinvader_sale_profile/views/shopinvader_backend.xml
Labels: bot is merging ⏳

#756 [12.0][PORT] 562 from 10.0
  shopinvader_promotion_rule/__init__.py
  shopinvader_promotion_rule/models/__init__.py
  shopinvader_promotion_rule/models/sale_order.py
  shopinvader_promotion_rule/tests/test_cart.py
Labels: bot is merging ⏳

#757 [13.0][PORT] 562 from 10.0
  shopinvader_promotion_rule/__init__.py
  shopinvader_promotion_rule/models/__init__.py
  shopinvader_promotion_rule/models/sale_order.py
  shopinvader_promotion_rule/tests/test_cart.py
Labels: bot is merging ⏳
