Repository shopinvader/odoo-shopinvader, pull requests merged in 2021-01, with the labels that each got.

#837 [FIX] 13.0 delivery_carrier test
  shopinvader_delivery_carrier/tests/test_carrier.py
  shopinvader_search_engine/views/product_category_view.xml
  shopinvader_search_engine/views/product_view.xml
Labels: bot is merging ⏳

#805 [13.0] shopinvader_wishlist: add /replace_items endpoint
  shopinvader_locomotive_wishlist/__init__.py
  shopinvader_locomotive_wishlist/components/event_listeners.py
  shopinvader_locomotive_wishlist/services/__init__.py
  shopinvader_locomotive_wishlist/services/wishlist.py
  shopinvader_locomotive_wishlist/tests/__init__.py
  shopinvader_locomotive_wishlist/tests/test_wishlist.py
  shopinvader_wishlist/services/wishlist.py
  shopinvader_wishlist/tests/test_wishlist.py
Labels: 13.0, approved, bot is merging ⏳, enhancement, ready to merge

#828 shopinvader: cart create rely on onchanges for addresses
  shopinvader/services/cart.py
Labels: 13.0, approved, bot is merging ⏳, bug, ready to merge

#840 s_sale_packaging: adapt filter to changes sale_by_packaging
  shopinvader_sale_packaging/models/shopinvader_variant.py
  shopinvader_sale_packaging/services/packaging_mixin.py
Labels: bot is merging ⏳

#844 10.0 FIX travis: limit test to maintained version, OCB
  .isort.cfg
  .pre-commit-config.yaml
  .travis.yml
  shopinvader_backend_image_proxy/models/shopinvader_backend.py
  shopinvader_import_image/models/import_image.py
Labels: approved, bot is merging ⏳

#823 [REF] remove all @job to use the new api
  shopinvader/__manifest__.py
  shopinvader/data/queue_job_channel_data.xml
  shopinvader/data/queue_job_function_data.xml
  shopinvader/models/shopinvader_notification.py
  shopinvader_cart_expiry/__manifest__.py
  shopinvader_cart_expiry/data/queue_job_function_data.xml
  shopinvader_cart_expiry/models/shopinvader_backend.py
  shopinvader_import_image/__manifest__.py
  shopinvader_import_image/data/queue_job_channel_data.xml
  shopinvader_import_image/data/queue_job_function_data.xml
  shopinvader_import_image/models/import_image.py
  shopinvader_locomotive/__manifest__.py
  shopinvader_locomotive/data/queue_job_function_data.xml
  shopinvader_locomotive/models/locomotive_binding.py
  shopinvader_locomotive_reset_password/__manifest__.py
  shopinvader_locomotive_reset_password/data/queue_job_function_data.xml
  shopinvader_locomotive_reset_password/models/partner.py
  shopinvader_locomotive_reset_password/models/shopinvader_backend.py
  shopinvader_locomotive_reset_password/wizards/reset_password.py
  shopinvader_product_stock/__manifest__.py
  shopinvader_product_stock/data/queue_job_channel_data.xml
  shopinvader_product_stock/data/queue_job_function_data.xml
  shopinvader_product_stock/models/product_product.py
  shopinvader_product_stock/models/stock_move.py
  shopinvader_product_stock/tests/test_product.py
  test-requirements.txt
Labels: approved, bot is merging ⏳, ready to merge

#822 [13.0][PORT] 793 from 10.0
  shopinvader_delivery_carrier/services/abstract_sale.py
  shopinvader_delivery_carrier/tests/test_carrier.py
Labels: 13.0, bot is merging ⏳, forwardport

#832 [FIX] fix wrong variable passed for shopinvader categories
  shopinvader/models/shopinvader_product.py
Labels: bot is merging ⏳

#820 [13.0][PORT] 647 from 10.0
  .pre-commit-config.yaml
  shopinvader_sale_communication/README.rst
  shopinvader_sale_communication/__init__.py
  shopinvader_sale_communication/__manifest__.py
  shopinvader_sale_communication/models/__init__.py
  shopinvader_sale_communication/models/sale_order.py
  shopinvader_sale_communication/readme/CONTRIBUTORS.rst
  shopinvader_sale_communication/readme/DESCRIPTION.rst
  shopinvader_sale_communication/services/__init__.py
  shopinvader_sale_communication/services/abstract_sale.py
  shopinvader_sale_communication/services/cart.py
  shopinvader_sale_communication/tests/__init__.py
  shopinvader_sale_communication/tests/test_cart.py
  shopinvader_sale_communication/tests/test_sale.py
  shopinvader_sale_communication/views/sale_order.xml
Labels: 13.0, bot is merging ⏳, forwardport

#819 [13.0][PORT] 598 from 10.0
  shopinvader/services/address.py
  shopinvader_guest_mode/services/__init__.py
  shopinvader_guest_mode/services/address.py
  shopinvader_guest_mode/tests/test_guest_service.py
Labels: 13.0, bot is merging ⏳, forwardport

#829 s_customer_multi_user: fix/imp address domains
  shopinvader/services/address.py
  shopinvader/services/service.py
  shopinvader/tests/test_salesman_notification.py
  shopinvader_customer_multi_user/__init__.py
  shopinvader_customer_multi_user/components/__init__.py
  shopinvader_customer_multi_user/components/access_info.py
  shopinvader_customer_multi_user/models/shopinvader_backend.py
  shopinvader_customer_multi_user/models/shopinvader_partner.py
  shopinvader_customer_multi_user/services/address.py
  shopinvader_customer_multi_user/services/service.py
  shopinvader_customer_multi_user/tests/common.py
  shopinvader_customer_multi_user/tests/test_multi_user_service_partner_domain.py
Labels: 13.0, approved, bot is merging ⏳, enhancement, ready to merge

#848 [13.0] [UPD] rename alias to target for base_jsonify
  shopinvader/data/ir_export_category.xml
  shopinvader/data/ir_export_product.xml
  shopinvader_algolia/data/ir_export_product.xml
  shopinvader_custom_attribute/data/ir_export_product.xml
  shopinvader_demo_app/data/ir_export_product.xml
  shopinvader_elasticsearch/data/ir_export_product.xml
  shopinvader_product_media/data/ir_product_export.xml
  shopinvader_product_stock/data/ir_export_product.xml
  shopinvader_product_stock/models/shopinvader_variant.py
  shopinvader_product_stock/tests/test_product.py
Labels: approved, bot is merging ⏳

#826 [FIX] non-blocking errors that will be blocking in 14.0
  shopinvader/models/shopinvader_notification.py
  shopinvader/views/shopinvader_variant_view.xml
Labels: bot is merging ⏳

#775 [13.0] [MIG] shopinvader_backend_image_proxy
  setup/shopinvader_backend_image_proxy/odoo/addons/shopinvader_backend_image_proxy
  setup/shopinvader_backend_image_proxy/setup.py
  shopinvader_backend_image_proxy/__manifest__.py
  shopinvader_backend_image_proxy/models/shopinvader_backend.py
  shopinvader_backend_image_proxy/models/shopinvader_image_mixin.py
Labels: 13.0, approved, bot is merging ⏳, migration, needs review, ready to merge

#773 [13.0][PORT] 561 from 10.0
  shopinvader/services/address.py
  shopinvader/tests/test_address.py
Labels: 13.0, approved, bot is merging ⏳, forwardport, help wanted, needs fixing, ready to merge

#821 [13.0][PORT] 739 and 615 from 12.0
  shopinvader_delivery_carrier/__manifest__.py
  shopinvader_delivery_carrier/services/abstract_sale.py
  shopinvader_delivery_carrier/services/delivery_carrier.py
  shopinvader_delivery_carrier/tests/common.py
  shopinvader_delivery_carrier/tests/test_carrier.py
  shopinvader_delivery_carrier/tests/test_delivery_carrier.py
Labels: 13.0, bot is merging ⏳, forwardport

#807 [13.0] Unify customer role value default and lookup
  shopinvader/__manifest__.py
  shopinvader/models/shopinvader_backend.py
  shopinvader/models/shopinvader_partner.py
  shopinvader/models/shopinvader_variant.py
  shopinvader/services/customer.py
  shopinvader/views/shopinvader_backend_view.xml
  shopinvader_locomotive/component/shopinvader_partner_export_mapper.py
  shopinvader_locomotive_sale_profile/components/__init__.py
  shopinvader_locomotive_sale_profile/components/shopinvader_partner_export_mapper.py
  shopinvader_sale_profile/__init__.py
  shopinvader_sale_profile/models/shopinvader_backend.py
  shopinvader_sale_profile/models/shopinvader_partner.py
  shopinvader_sale_profile/services/__init__.py
  shopinvader_sale_profile/services/shopinvader_customer_service.py
  shopinvader_sale_profile/tests/__init__.py
  shopinvader_sale_profile/tests/test_customer_service.py
  shopinvader_sale_profile/tests/test_shopinvader_backend_sale_profile.py
  shopinvader_sale_profile/tests/test_shopinvader_variant.py
  shopinvader_sale_profile/views/shopinvader_backend.xml
Labels: 13.0, bot is merging ⏳, enhancement

#851 [10.0][FIX]shopinvader_sale_profile: fix wrong company for determining pricelists on partner
  shopinvader_sale_profile/models/shopinvader_partner.py
Labels: approved, bot is merging ⏳

#852 shopinvader: fix services description
  shopinvader/services/address.py
  shopinvader/services/cart.py
  shopinvader/services/customer.py
  shopinvader/services/invoice.py
  shopinvader/services/sale.py
  shopinvader_delivery_carrier/services/delivery_carrier.py
  shopinvader_lead/services/lead.py
  shopinvader_wishlist/services/wishlist.py
Labels: bot is merging ⏳

#841 10.0 IMP invader: add mobile field to services
  shopinvader/services/address.py
  shopinvader/tests/test_address.py
  shopinvader/tests/test_customer.py
  shopinvader/tests/test_notification.py
Labels: approved, bot is merging ⏳, ready to merge
