Repository shopinvader/odoo-shopinvader, pull requests merged in 2021-02, with the labels that each got.

#830 [13.0] s_product_*_multi_link: fix non symmetric link
  shopinvader_product_template_multi_link/models/__init__.py
  shopinvader_product_template_multi_link/models/shopinvader_product.py
  shopinvader_product_template_multi_link/models/shopinvader_product_link_mixin.py
  shopinvader_product_template_multi_link/tests/test_product.py
  shopinvader_product_variant_multi_link/models/shopinvader_variant.py
  shopinvader_product_variant_multi_link/tests/test_product.py
Labels: 13.0, bot is merging ⏳, needs review

#877 [13.0] shopinvader_image: boost images compute
  shopinvader_image/models/shopinvader_image_mixin.py
  shopinvader_image/tests/__init__.py
  shopinvader_image/tests/test_getting_image.py
  shopinvader_image/tests/test_images.py
Labels: 13.0, approved, bot is merging ⏳, enhancement

#783 [13.0] Unify product data lookup
  shopinvader/data/ir_export_product.xml
  shopinvader/models/shopinvader_variant.py
  shopinvader/services/abstract_sale.py
  shopinvader/tests/common.py
  shopinvader/tests/test_cart_item.py
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_delivery_carrier/services/delivery_carrier.py
  shopinvader_image/__init__.py
  shopinvader_image/services/__init__.py
  shopinvader_image/services/abstract_sale.py
  shopinvader_invoice/services/invoice.py
  shopinvader_locomotive/component/shopinvader_site_export_mapper.py
  shopinvader_product_stock/tests/test_product.py
  shopinvader_product_template_multi_link/tests/test_product.py
  shopinvader_quotation/services/__init__.py
  shopinvader_quotation/services/abstract_sale.py
  shopinvader_sale_packaging/services/abstract_sale.py
  shopinvader_sale_packaging/tests/test_cart.py
  shopinvader_sale_packaging/tests/test_sale.py
  shopinvader_sale_packaging_wishlist/services/wishlist.py
  shopinvader_sale_packaging_wishlist/tests/test_wishlist_packaging.py
  shopinvader_search_engine/models/shopinvader_variant.py
  shopinvader_wishlist/services/wishlist.py
  shopinvader_wishlist/tests/test_wishlist.py
Labels: 13.0, approved, bot is merging ⏳, enhancement, needs review, ready to merge

#878 [13.0] Improve performance for product data
  shopinvader/data/ir_export_product.xml
  shopinvader/models/shopinvader_category.py
  shopinvader/models/shopinvader_product.py
  shopinvader/models/shopinvader_variant.py
  shopinvader/services/abstract_sale.py
  shopinvader/tests/test_product.py
  shopinvader/views/shopinvader_variant_view.xml
  shopinvader_elasticsearch/tests/test_shopinvader_elasticsearch.py
Labels: approved, bot is merging ⏳, ready to merge

#885 s_wishlist: add new endpoint 'add_items_to_cart'
  shopinvader_sale_packaging_wishlist/tests/test_wishlist_packaging.py
  shopinvader_wishlist/models/product_set.py
  shopinvader_wishlist/services/wishlist.py
  shopinvader_wishlist/tests/test_product_set.py
  shopinvader_wishlist/tests/test_wishlist.py
Labels: approved, bot is merging ⏳, ready to merge

#890 [13.0][FIX] download invoice
  shopinvader/controllers/main.py
Labels: approved, bot is merging ⏳
