Repository shopinvader/odoo-shopinvader, pull requests merged in 2021-08, with the labels that each got.

#1033 [14.0][ADD] shopinvader_customer_invoicing_mode
  setup/shopinvader_customer_invoicing_mode/odoo/addons/shopinvader_customer_invoicing_mode
  setup/shopinvader_customer_invoicing_mode/setup.py
  shopinvader_customer_invoicing_mode/README.rst
  shopinvader_customer_invoicing_mode/__init__.py
  shopinvader_customer_invoicing_mode/__manifest__.py
  shopinvader_customer_invoicing_mode/readme/CONTRIBUTORS.rst
  shopinvader_customer_invoicing_mode/readme/DESCRIPTION.rst
  shopinvader_customer_invoicing_mode/services/__init__.py
  shopinvader_customer_invoicing_mode/services/customer.py
  shopinvader_customer_invoicing_mode/tests/__init__.py
  shopinvader_customer_invoicing_mode/tests/test_customer.py
Labels: 14.0, bot is merging ⏳

#1052 [14.0][FIX] Misc. small fixes
  shopinvader/views/shopinvader_backend_view.xml
  shopinvader_auth_api_key/__manifest__.py
Labels: bot is merging ⏳

#1057 [14.0][IMP] shopinvader: Add string for Parent Has Shopinvader User
  shopinvader/models/res_partner.py
Labels: bot is merging ⏳, enhancement, needs review

#1056 [14.0][IMP] shopinvader: Minimum version of base_rest
  setup/shopinvader/setup.py
Labels: bot is merging ⏳, enhancement, needs review

#1044 s_product_brand: fix indexed ID
  shopinvader_product_brand/data/ir_export_brand.xml
Labels: 14.0, bot is merging ⏳, bug

#1059 [14.0][IMP] shopinvader menues and config.settings
  shopinvader/__manifest__.py
  shopinvader/models/__init__.py
  shopinvader/models/res_config_settings.py
  shopinvader/models/res_partner.py
  shopinvader/models/shopinvader_config_settings.py
  shopinvader/models/shopinvader_partner.py
  shopinvader/security/ir.model.access.csv
  shopinvader/tests/test_res_partner.py
  shopinvader/tests/test_shopinvader_partner.py
  shopinvader/views/res_config_settings.xml
  shopinvader/views/shopinvader_cart_step_view.xml
  shopinvader/views/shopinvader_category_view.xml
  shopinvader/views/shopinvader_config_settings.xml
  shopinvader/views/shopinvader_menu.xml
  shopinvader/views/shopinvader_partner_view.xml
  shopinvader/views/shopinvader_product_view.xml
  shopinvader/views/shopinvader_variant_view.xml
  shopinvader_guest_mode/tests/test_guest_service.py
  shopinvader_image/views/shopinvader_image_resize_view.xml
  shopinvader_product_brand/views/shopinvader_brand_view.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#1060 [14.0][IMP] shopinvader: Improve product views + add kanban
  shopinvader/models/product_category.py
  shopinvader/models/product_product.py
  shopinvader/models/product_template.py
  shopinvader/models/shopinvader_category.py
  shopinvader/models/shopinvader_product.py
  shopinvader/models/shopinvader_variant.py
  shopinvader/views/shopinvader_category_view.xml
  shopinvader/views/shopinvader_product_view.xml
  shopinvader/views/shopinvader_variant_view.xml
  shopinvader_search_engine/__manifest__.py
  shopinvader_search_engine/views/shopinvader_category_view.xml
  shopinvader_search_engine/views/shopinvader_variant_view.xml
Labels: bot is merging ⏳

#1031 [14.0] shopinvader_auth_jwt: Add end point to serve shopinvader services protected by a JWT authentication
  setup/shopinvader_auth_jwt/odoo/addons/shopinvader_auth_jwt
  setup/shopinvader_auth_jwt/setup.py
  shopinvader_auth_jwt/README.rst
  shopinvader_auth_jwt/__init__.py
  shopinvader_auth_jwt/__manifest__.py
  shopinvader_auth_jwt/components/__init__.py
  shopinvader_auth_jwt/components/service_context_provider.py
  shopinvader_auth_jwt/controllers/__init__.py
  shopinvader_auth_jwt/controllers/main.py
  shopinvader_auth_jwt/models/__init__.py
  shopinvader_auth_jwt/models/shopinvader_backend.py
  shopinvader_auth_jwt/readme/CONTRIBUTORS.rst
  shopinvader_auth_jwt/readme/DESCRIPTION.rst
  shopinvader_auth_jwt/static/description/index.html
  shopinvader_auth_jwt/views/shopinvader_backend.xml
Labels: bot is merging ⏳, 14.0

#1061 [14.0][FIX] shopinvader: Multi-company rules
  shopinvader/migrations/14.0.4.1.0/post-migrate.py
  shopinvader/models/shopinvader_binding.py
  shopinvader/models/shopinvader_category.py
  shopinvader/models/shopinvader_partner.py
  shopinvader/models/shopinvader_product.py
  shopinvader/models/shopinvader_variant.py
  shopinvader/security/shopinvader_backend_security.xml
  shopinvader/security/shopinvader_category_security.xml
  shopinvader/security/shopinvader_partner_security.xml
  shopinvader/security/shopinvader_product_security.xml
  shopinvader/security/shopinvader_variant_security.xml
  shopinvader/views/shopinvader_backend_view.xml
  shopinvader/views/shopinvader_category_view.xml
  shopinvader/views/shopinvader_partner_view.xml
  shopinvader/views/shopinvader_product_view.xml
  shopinvader/views/shopinvader_variant_view.xml
Labels: approved, bot is merging ⏳

#1065 [FIX] shopinvader_auth_jwt: add missing import
  shopinvader_auth_jwt/__init__.py
Labels: bot is merging ⏳

#1049 [14.0] Move currencies from shopinvader_locomotive to shopinvader, add endpoints for backend metadata
  shopinvader/models/shopinvader_backend.py
  shopinvader/readme/CONTRIBUTORS.rst
  shopinvader/services/__init__.py
  shopinvader/services/settings.py
  shopinvader/tests/__init__.py
  shopinvader/tests/test_settings.py
  shopinvader_locomotive/models/shopinvader_backend.py
Labels: approved, ready to merge, bot is merging ⏳

#1067 [FIX] add noupdate to avoid deleting and recreating record
  shopinvader/demo/product_product_demo.xml
Labels: bot is merging ⏳

#1045 [MIG][14.0] shopinvader_pending_cart_reminder
  .pre-commit-config.yaml
  setup/shopinvader_pending_cart_reminder/odoo/addons/shopinvader_pending_cart_reminder
  setup/shopinvader_pending_cart_reminder/setup.py
  shopinvader_pending_cart_reminder/__manifest__.py
  shopinvader_pending_cart_reminder/data/ir_cron.xml
  shopinvader_pending_cart_reminder/data/mail_template.xml
  shopinvader_pending_cart_reminder/models/sale_order.py
  shopinvader_pending_cart_reminder/models/shopinvader_backend.py
  shopinvader_pending_cart_reminder/tests/test_sale_order.py
  shopinvader_pending_cart_reminder/tests/test_shopinvader_backend.py
  shopinvader_pending_cart_reminder/views/shopinvader_backend.xml
Labels: approved, bot is merging ⏳, migration

#1070 [FIX] fix binding view on product.template form
  shopinvader/views/product_view.xml
  shopinvader/views/shopinvader_product_view.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#1007 [14.0][MIG] shopinvader_guest_mode
  .pre-commit-config.yaml
  setup/shopinvader_guest_mode/odoo/addons/shopinvader_guest_mode
  setup/shopinvader_guest_mode/setup.py
  shopinvader_guest_mode/__manifest__.py
  shopinvader_guest_mode/data/ir_cron.xml
  shopinvader_guest_mode/models/shopinvader_partner.py
  shopinvader_guest_mode/services/address.py
  shopinvader_guest_mode/services/customer.py
  shopinvader_guest_mode/services/guest_service.py
  shopinvader_guest_mode/tests/test_guest_service.py
  shopinvader_guest_mode/tests/test_shopinvader_backend.py
  shopinvader_guest_mode/tests/test_shopinvader_partner.py
  shopinvader_guest_mode/views/shopinvader_backend.xml
  shopinvader_guest_mode/views/shopinvader_partner.xml
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#1068 [IMP+FIX][14.0] shopinvader_import_image
  shopinvader_import_image/models/import_image.py
  shopinvader_import_image/views/import_product_image_view.xml
Labels: approved, bot is merging ⏳

#1074 [13.0] s_elasticsearch: turn off vcr.cassette test logs
  shopinvader_elasticsearch/tests/cassettes/TestElasticsearchBackend.test_10_export_one_product.yaml
  shopinvader_elasticsearch/tests/cassettes/TestElasticsearchBackend.test_20_export_all_products.yaml
  shopinvader_elasticsearch/tests/cassettes/TestElasticsearchBackend.test_30_export_all_categories.yaml
  shopinvader_elasticsearch/tests/test_shopinvader_elasticsearch.py
Labels: needs review, 13.0, bot is merging ⏳, TODO: fwd-v14

#1054 s_sale_packaging: add flag to control visibility
  shopinvader_sale_packaging/__manifest__.py
  shopinvader_sale_packaging/models/__init__.py
  shopinvader_sale_packaging/models/product_packaging.py
  shopinvader_sale_packaging/models/product_packaging_type.py
  shopinvader_sale_packaging/models/shopinvader_variant.py
  shopinvader_sale_packaging/tests/test_product_data.py
  shopinvader_sale_packaging/views/product_packaging.xml
  shopinvader_sale_packaging/views/product_packaging_type.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1078 [13.0] Backport UI improvements
  shopinvader/__manifest__.py
  shopinvader/models/__init__.py
  shopinvader/models/res_config_settings.py
  shopinvader/models/res_partner.py
  shopinvader/models/shopinvader_config_settings.py
  shopinvader/models/shopinvader_partner.py
  shopinvader/tests/test_res_partner.py
  shopinvader/tests/test_shopinvader_partner.py
  shopinvader/views/res_config_settings.xml
  shopinvader/views/shopinvader_cart_step_view.xml
  shopinvader/views/shopinvader_category_view.xml
  shopinvader/views/shopinvader_config_settings.xml
  shopinvader/views/shopinvader_menu.xml
  shopinvader/views/shopinvader_partner_view.xml
  shopinvader/views/shopinvader_product_view.xml
  shopinvader/views/shopinvader_variant_view.xml
  shopinvader_guest_mode/tests/test_guest_service.py
  shopinvader_image/views/shopinvader_image_resize_view.xml
Labels: bot is merging ⏳

#895 [MIG] shopinvader_customer_price: Migration to 14.0
  setup/shopinvader_customer_price/odoo/addons/shopinvader_customer_price
  setup/shopinvader_customer_price/setup.py
  shopinvader_customer_price/README.rst
  shopinvader_customer_price/__init__.py
  shopinvader_customer_price/__manifest__.py
  shopinvader_customer_price/i18n/shopinvader_customer_price.pot
  shopinvader_customer_price/models/__init__.py
  shopinvader_customer_price/models/shopinvader_backend.py
  shopinvader_customer_price/readme/CONTRIBUTORS.rst
  shopinvader_customer_price/readme/CREDITS.rst
  shopinvader_customer_price/readme/DESCRIPTION.rst
  shopinvader_customer_price/readme/ROADMAP.rst
  shopinvader_customer_price/services/__init__.py
  shopinvader_customer_price/services/customer_price.py
  shopinvader_customer_price/static/description/index.html
  shopinvader_customer_price/tests/__init__.py
  shopinvader_customer_price/tests/test_cart.py
  shopinvader_customer_price/tests/test_customer_price.py
  shopinvader_customer_price/views/shopinvader_backend_views.xml
Labels: needs review, bot is merging ⏳, migration, 14.0

#1083 [14.0][FIX] shopinvader_image: product.image.relation demo data
  shopinvader_image/demo/product_image_relation_demo.xml
  shopinvader_image/demo/product_product_image_relation_demo.xml
  shopinvader_image/hooks.py
Labels: bot is merging ⏳

#1091 [14.0][FIX] shopinvader: Improve category tests for children
  shopinvader/tests/test_product.py
Labels: enhancement, bot is merging ⏳

#1073 [14.0][MIG] shopinvader_product_template_multi_link
  .pre-commit-config.yaml
  setup/shopinvader_product_template_multi_link/odoo/addons/shopinvader_product_template_multi_link
  setup/shopinvader_product_template_multi_link/setup.py
  shopinvader_product_template_multi_link/__manifest__.py
  shopinvader_product_template_multi_link/data/ir_exports_line.xml
  shopinvader_product_template_multi_link/i18n/shopinvader_product_template_multi_link.pot
  shopinvader_product_template_multi_link/models/__init__.py
  shopinvader_product_template_multi_link/models/shopinvader_product.py
  shopinvader_product_template_multi_link/models/shopinvader_product_link_mixin.py
  shopinvader_product_template_multi_link/tests/common.py
  shopinvader_product_template_multi_link/tests/test_product.py
Labels: needs review, bot is merging ⏳, migration
