Repository shopinvader/odoo-shopinvader, pull requests merged in 2021-05, with the labels that each got.

#949 [13.0] shopinvader_sale_packaging: misc fixes
  shopinvader_sale_packaging/services/cart.py
  shopinvader_sale_packaging/services/packaging_mixin.py
Labels: 13.0, bot is merging ⏳

#942 [13.0] Misc wishlist fix/imp
  shopinvader/services/abstract_sale.py
  shopinvader/services/address.py
  shopinvader/services/cart.py
  shopinvader/services/service.py
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_invoice/services/invoice.py
  shopinvader_locomotive_wishlist/components/event_listeners.py
  shopinvader_wishlist/services/wishlist.py
  shopinvader_wishlist/tests/test_wishlist.py
Labels: 13.0, bot is merging ⏳

#957 [13.0] shopinvader: centralize partner work ctx setup
  shopinvader/controllers/main.py
  shopinvader/services/customer.py
  shopinvader/services/service.py
  shopinvader/tests/__init__.py
  shopinvader/tests/common.py
  shopinvader/tests/test_cart.py
  shopinvader/tests/test_customer.py
  shopinvader/tests/test_salesman_notification.py
  shopinvader/tests/test_utils.py
  shopinvader/utils.py
  shopinvader_customer_multi_user/tests/common.py
  shopinvader_customer_multi_user/tests/test_multi_user_customer.py
  shopinvader_customer_multi_user_wishlist/tests/test_wishlist.py
  shopinvader_guest_mode/services/guest_service.py
  shopinvader_promotion_rule/tests/test_cart.py
Labels: approved, bot is merging ⏳

#962 s_sale_packaging: include barcode
  shopinvader_sale_packaging/__manifest__.py
  shopinvader_sale_packaging/migrations/13.0.2.2.0/post-migrate.py
  shopinvader_sale_packaging/models/shopinvader_variant.py
  shopinvader_sale_packaging/services/packaging_mixin.py
  shopinvader_sale_packaging/tests/test_cart.py
  shopinvader_sale_packaging/tests/test_product_data.py
  shopinvader_sale_packaging/tests/test_sale.py
  shopinvader_sale_packaging_wishlist/tests/test_wishlist_packaging.py
Labels: 13.0, bot is merging ⏳

#965 s_wishlist: include access info in light parser
  shopinvader_wishlist/services/wishlist.py
  shopinvader_wishlist/tests/test_wishlist.py
Labels: bot is merging ⏳

#854 [13.0] update algolia
  shopinvader_algolia/tests/cassettes/TestAlgoliaBackend.test_10_export_one_product.yaml
  shopinvader_algolia/tests/cassettes/TestAlgoliaBackend.test_20_export_all_products.yaml
  shopinvader_algolia/tests/cassettes/TestAlgoliaBackend.test_30_export_all_categories.yaml
  shopinvader_algolia/tests/test_export.py
Labels: 13.0, bot is merging ⏳

#967 [14.0] shopinvader: fix test_invoice after core change
  shopinvader/tests/common.py
  shopinvader/tests/test_invoice.py
Labels: 14.0, approved, bot is merging ⏳

#966 [14.0] Drop pending merges in test requirements
  test-requirements.txt
Labels: 14.0

#917 [MIG] 14.0 elasticsearch
  .pre-commit-config.yaml
  setup/shopinvader_elasticsearch/odoo/addons/shopinvader_elasticsearch
  setup/shopinvader_elasticsearch/setup.py
  shopinvader_elasticsearch/__manifest__.py
  shopinvader_elasticsearch/data/ir_export_product.xml
  shopinvader_elasticsearch/demo/backend_demo.xml
  shopinvader_elasticsearch/demo/index_config_demo.xml
  shopinvader_elasticsearch/tests/cassettes/TestElasticsearchBackend.test_10_export_one_product.yaml
  shopinvader_elasticsearch/tests/cassettes/TestElasticsearchBackend.test_20_export_all_products.yaml
  shopinvader_elasticsearch/tests/cassettes/TestElasticsearchBackend.test_30_export_all_categories.yaml
  shopinvader_elasticsearch/tests/test_shopinvader_elasticsearch.py
Labels: 14.0, Blocked by dependency, approved, bot is merging ⏳, migration, needs review

#803 [13.0] Add shopinvader_customer_price + shopinvader_customer_price_wishlist
  setup/shopinvader_customer_price/odoo/addons/shopinvader_customer_price
  setup/shopinvader_customer_price/setup.py
  setup/shopinvader_customer_price_wishlist/odoo/addons/shopinvader_customer_price_wishlist
  setup/shopinvader_customer_price_wishlist/setup.py
  shopinvader/tests/common.py
  shopinvader/tests/test_product.py
  shopinvader_customer_price/README.rst
  shopinvader_customer_price/__init__.py
  shopinvader_customer_price/__manifest__.py
  shopinvader_customer_price/models/__init__.py
  shopinvader_customer_price/models/shopinvader_backend.py
  shopinvader_customer_price/readme/CONTRIBUTORS.rst
  shopinvader_customer_price/readme/CREDITS.rst
  shopinvader_customer_price/readme/DESCRIPTION.rst
  shopinvader_customer_price/readme/ROADMAP.rst
  shopinvader_customer_price/services/__init__.py
  shopinvader_customer_price/services/customer_price.py
  shopinvader_customer_price/static/description/index.html
  shopinvader_customer_price/tests/__init__.py
  shopinvader_customer_price/tests/test_cart.py
  shopinvader_customer_price/tests/test_customer_price.py
  shopinvader_customer_price/views/shopinvader_backend_views.xml
  shopinvader_customer_price_wishlist/README.rst
  shopinvader_customer_price_wishlist/__init__.py
  shopinvader_customer_price_wishlist/__manifest__.py
  shopinvader_customer_price_wishlist/readme/CONTRIBUTORS.rst
  shopinvader_customer_price_wishlist/readme/CREDITS.rst
  shopinvader_customer_price_wishlist/readme/DESCRIPTION.rst
  shopinvader_customer_price_wishlist/services/__init__.py
  shopinvader_customer_price_wishlist/services/wishlist.py
  shopinvader_customer_price_wishlist/static/description/index.html
  shopinvader_customer_price_wishlist/tests/__init__.py
  shopinvader_customer_price_wishlist/tests/test_wishlist_price.py
Labels: 13.0, bot is merging ⏳, enhancement

#969 [MIG] shopinvader_notification_default: Migration to 14.0
  .pre-commit-config.yaml
  setup/shopinvader_notification_default/odoo/addons/shopinvader_notification_default
  setup/shopinvader_notification_default/setup.py
  shopinvader_notification_default/__manifest__.py
  shopinvader_notification_default/data/email_template.xml
  shopinvader_notification_default/data/shopinvader_notification.xml
  shopinvader_notification_default/templates/cart_email.xml
  shopinvader_notification_default/templates/customer_address_email.xml
  shopinvader_notification_default/templates/customer_profile_email.xml
  shopinvader_notification_default/templates/invoice_email.xml
  shopinvader_notification_default/templates/layout.xml
  shopinvader_notification_default/templates/sale_email.xml
Labels: bot is merging ⏳

#973 [MIG] shopinvader_assortment: Migration to 14.0
  .pre-commit-config.yaml
  oca_dependencies.txt
  setup/shopinvader_assortment/odoo/addons/shopinvader_assortment
  setup/shopinvader_assortment/setup.py
  shopinvader_assortment/README.rst
  shopinvader_assortment/__manifest__.py
  shopinvader_assortment/demo/shopinvader_assortment_demo.xml
  shopinvader_assortment/models/shopinvader_backend.py
  shopinvader_assortment/readme/DESCRIPTION.rst
  shopinvader_assortment/static/description/index.html
  shopinvader_assortment/tests/test_product_auto_bind.py
  shopinvader_assortment/views/shopinvader_backend.xml
Labels: 14.0, bot is merging ⏳, migration

#974 [MIG] shopinvader_locomotive: Migration to 14.0
  .pre-commit-config.yaml
  requirements.txt
  setup/shopinvader_locomotive/odoo/addons/shopinvader_locomotive
  setup/shopinvader_locomotive/setup.py
  shopinvader/i18n/shopinvader.pot
  shopinvader/views/shopinvader_backend_view.xml
  shopinvader_locomotive/__manifest__.py
  shopinvader_locomotive/component/adapter.py
  shopinvader_locomotive/component/core.py
  shopinvader_locomotive/component/deleter.py
  shopinvader_locomotive/component/event_listeners.py
  shopinvader_locomotive/component/shopinvader_site_export_mapper.py
  shopinvader_locomotive/controllers/main.py
  shopinvader_locomotive/data/ir_cron.xml
  shopinvader_locomotive/data/queue_job_function_data.xml
  shopinvader_locomotive/demo/backend_demo.xml
  shopinvader_locomotive/models/__init__.py
  shopinvader_locomotive/models/locomotive_binding.py
  shopinvader_locomotive/models/product_filter.py
  shopinvader_locomotive/models/shopinvader_backend.py
  shopinvader_locomotive/tests/test_backend.py
  shopinvader_locomotive/tests/test_search_engine_site_export.py
  shopinvader_locomotive/tests/test_shopinvader_partner.py
  shopinvader_locomotive/views/product_filter_view.xml
  shopinvader_locomotive/views/shopinvader_backend_view.xml
Labels: 14.0, approved, bot is merging ⏳, migration

#981 [FIX] missing default code for product demo
  shopinvader/demo/product_product_demo.xml
Labels: bot is merging ⏳
