Repository shopinvader/odoo-shopinvader, pull requests merged in 2021-09, with the labels that each got.

#1092 14.0 fix shopinvader product template multi link
  shopinvader_product_template_multi_link/data/ir_exports_line.xml
  shopinvader_product_template_multi_link/models/shopinvader_product_link_mixin.py
  shopinvader_product_template_multi_link/tests/test_product.py
Labels: bot is merging ⏳

#1062 [14.0][ADD] shopinvader_product_order
  setup/shopinvader_product_order/odoo/addons/shopinvader_product_order
  setup/shopinvader_product_order/setup.py
  shopinvader_product_order/__init__.py
  shopinvader_product_order/__manifest__.py
  shopinvader_product_order/data/ir_export_product.xml
  shopinvader_product_order/models/__init__.py
  shopinvader_product_order/models/shopinvader_product.py
  shopinvader_product_order/readme/CONTRIBUTORS.rst
  shopinvader_product_order/readme/DESCRIPTION.rst
  shopinvader_product_order/views/shopinvader_product.xml
Labels: needs review, approved, bot is merging ⏳

#1099 shopinvader_locomotive: depend on shopinvader_auth_api_key
  shopinvader_locomotive/__manifest__.py
Labels: needs review, bot is merging ⏳

#1084 [14.0][IMP] shopinvader_invoice : Expose due date
  shopinvader_invoice/services/invoice.py
Labels: approved, ready to merge, bot is merging ⏳

#1089 [14.0][IMP] shopinvader_assortment: Add cron to automatically bind products
  shopinvader_assortment/__manifest__.py
  shopinvader_assortment/data/ir_cron.xml
  shopinvader_assortment/models/shopinvader_backend.py
  shopinvader_assortment/views/shopinvader_backend.xml
Labels: approved, ready to merge, bot is merging ⏳

#1072 [14.0][MIG] shopinvader_locomotive_guest_mode
  .pre-commit-config.yaml
  setup/shopinvader_locomotive_guest_mode/odoo/addons/shopinvader_locomotive_guest_mode
  setup/shopinvader_locomotive_guest_mode/setup.py
  shopinvader_customer_multi_user/tests/common.py
  shopinvader_customer_multi_user/tests/test_multi_user_token.py
  shopinvader_locomotive_guest_mode/__manifest__.py
  shopinvader_locomotive_guest_mode/tests/test_shopinvader_partner.py
Labels: needs review, approved, ready to merge, bot is merging ⏳, migration

#1043 [14.0][ADD] shopinvader_customer_multi_user_company_group
  setup/shopinvader_customer_multi_user_company_group/odoo/addons/shopinvader_customer_multi_user_company_group
  setup/shopinvader_customer_multi_user_company_group/setup.py
  shopinvader_customer_multi_user_company_group/__init__.py
  shopinvader_customer_multi_user_company_group/__manifest__.py
  shopinvader_customer_multi_user_company_group/models/__init__.py
  shopinvader_customer_multi_user_company_group/models/shopinvader_partner.py
  shopinvader_customer_multi_user_company_group/readme/CONTRIBUTORS.rst
  shopinvader_customer_multi_user_company_group/readme/DESCRIPTION.rst
  shopinvader_customer_multi_user_company_group/tests/__init__.py
  shopinvader_customer_multi_user_company_group/tests/test_multi_user_service_partner_domain.py
  shopinvader_customer_multi_user_company_group/views/shopinvader_partner.xml
Labels: bot is merging ⏳

#1113 [14.0] FIX shopinvader_customer_validate view
  shopinvader_customer_validate/views/partner_view.xml
Labels: bug, bot is merging ⏳, 14.0

#1118 [14.0][FIX] shopinvader_quotation: inherited product view
  shopinvader_quotation/views/product_view.xml
Labels: bot is merging ⏳

#1116 [14.0][FIX] shopinvader: no_partner_duplicate res.config.settings
  shopinvader/models/res_config_settings.py
  shopinvader/models/res_partner.py
  shopinvader/models/shopinvader_partner.py
  shopinvader/tests/test_res_partner.py
  shopinvader/tests/test_shopinvader_partner.py
Labels: approved, ready to merge, bot is merging ⏳

#1117 [13.0][FIX] shopinvader: no_partner_duplicate res.config.settings
  shopinvader/models/res_config_settings.py
  shopinvader/models/res_partner.py
  shopinvader/models/shopinvader_partner.py
  shopinvader/tests/test_res_partner.py
  shopinvader/tests/test_shopinvader_partner.py
Labels: bot is merging ⏳
