Repository shopinvader/odoo-shopinvader, pull requests merged in 2021-10, with the labels that each got.

#1122 [14.0][IMP] shopinvader: name in res.config.settings container
  shopinvader/views/res_config_settings.xml
Labels: bot is merging ⏳

#1115 [13.0][IMP] shopinvader: limit unique email constrain on res.partner to shopinvader users
  shopinvader/models/res_partner.py
  shopinvader/tests/test_res_partner.py
Labels: approved, ready to merge, bot is merging ⏳

#1127 [14.0][FIX] shopinvader: Stable sort for shopinvader.category
  shopinvader/models/shopinvader_category.py
Labels: approved, bot is merging ⏳

#1128 [FIX] 14.0 variant price computation if original_price_unit = 0
  shopinvader/models/shopinvader_variant.py
  shopinvader/tests/test_product.py
Labels: approved, bot is merging ⏳

#1124 [14.0][IMP] shopinvader: product.category view
  shopinvader/views/product_category_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1130 [14.0] [FIX] rename service context provider to avoid name clashes
  shopinvader_auth_api_key/components/service_context_provider.py
  shopinvader_auth_api_key/controllers/main.py
  shopinvader_auth_jwt/components/service_context_provider.py
  shopinvader_auth_jwt/controllers/main.py
Labels: approved, bot is merging ⏳

#1121 [14.0][IMP] shopinvader: product kanban view: add language
  shopinvader/views/shopinvader_product_view.xml
  shopinvader/views/shopinvader_variant_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1119 [14.0][IMP] shopinvader: product view
  shopinvader/views/product_view.xml
  shopinvader_quotation/views/product_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1106 [14.0] shopinvader_quotation: fix search validator
  shopinvader_quotation/services/quotation.py
Labels: bug, approved, bot is merging ⏳, 14.0

#1104 [14.0][IMP] shopinvader: Restore binding wizard on partner view
  shopinvader/wizards/shopinvader_partner_binding.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1094 [IMP] shopinvader_image: improve readme fragments
  shopinvader_image/readme/CONFIGURE.rst
  shopinvader_image/readme/DESCRIPTION.rst
  shopinvader_image/readme/USAGE.rst
Labels: bot is merging ⏳

#1090 [14.0][MIG] shopinvader_pos from 10.0
  setup/shopinvader_pos/odoo/addons/shopinvader_pos
  setup/shopinvader_pos/setup.py
  shopinvader_pos/README.rst
  shopinvader_pos/__init__.py
  shopinvader_pos/__manifest__.py
  shopinvader_pos/readme/CONTRIBUTORS.rst
  shopinvader_pos/readme/DESCRIPTION.rst
  shopinvader_pos/readme/USAGE.rst
  shopinvader_pos/services/__init__.py
  shopinvader_pos/services/shopinvader_pos.py
  shopinvader_pos/static/description/index.html
  shopinvader_pos/tests/__init__.py
  shopinvader_pos/tests/test_shopinvader_pos.py
Labels: needs review, approved, ready to merge, bot is merging ⏳, migration

#1085 [14.0][MIG] s_category_image_for_product
  .pre-commit-config.yaml
  setup/shopinvader_category_image_for_product/odoo/addons/shopinvader_category_image_for_product
  setup/shopinvader_category_image_for_product/setup.py
  shopinvader_category_image_for_product/__manifest__.py
  shopinvader_category_image_for_product/data/ir_export.xml
Labels: needs review, bot is merging ⏳, migration

#1131 [14.0][MIG] shopinvader_sale_packaging
  shopinvader_sale_packaging/__manifest__.py
  shopinvader_sale_packaging/models/shopinvader_variant.py
  shopinvader_sale_packaging/services/abstract_sale.py
  shopinvader_sale_packaging/services/cart.py
  shopinvader_sale_packaging/services/packaging_mixin.py
  shopinvader_sale_packaging/tests/__init__.py
  shopinvader_sale_packaging/tests/test_cart.py
  shopinvader_sale_packaging/tests/test_product_data.py
  shopinvader_sale_packaging/tests/test_sale.py
  shopinvader_sale_packaging_wishlist/services/wishlist.py
  shopinvader_sale_packaging_wishlist/tests/test_wishlist_packaging.py
Labels: bot is merging ⏳

#1081 [14.0][MIG] migrate shopinvader_product_stock_assortment
  .pre-commit-config.yaml
  setup/shopinvader_product_stock_assortment/odoo/addons/shopinvader_product_stock_assortment
  setup/shopinvader_product_stock_assortment/setup.py
  shopinvader_product_stock_assortment/__manifest__.py
  shopinvader_product_stock_assortment/models/shopinvader_backend.py
  shopinvader_product_stock_assortment/tests/test_product_auto_bind.py
Labels: bot is merging ⏳

#1123 [14.0][ADD] shopinvader_easy_binding
  setup/shopinvader_easy_binding/odoo/addons/shopinvader_easy_binding
  setup/shopinvader_easy_binding/setup.py
  shopinvader_easy_binding/__init__.py
  shopinvader_easy_binding/__manifest__.py
  shopinvader_easy_binding/demo/res_company.xml
  shopinvader_easy_binding/hooks.py
  shopinvader_easy_binding/models/__init__.py
  shopinvader_easy_binding/models/product_product.py
  shopinvader_easy_binding/models/product_template.py
  shopinvader_easy_binding/models/res_company.py
  shopinvader_easy_binding/models/res_config_settings.py
  shopinvader_easy_binding/models/shopinvader_company_backend_mixin.py
  shopinvader_easy_binding/readme/CONFIGURE.rst
  shopinvader_easy_binding/readme/CONTRIBUTORS.rst
  shopinvader_easy_binding/readme/DESCRIPTION.rst
  shopinvader_easy_binding/readme/ROADMAP.rst
  shopinvader_easy_binding/readme/USAGE.rst
  shopinvader_easy_binding/static/description/product_form.png
  shopinvader_easy_binding/tests/__init__.py
  shopinvader_easy_binding/tests/test_shopinvader_company_backend.py
  shopinvader_easy_binding/views/product_template.xml
  shopinvader_easy_binding/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳
