Repository shopinvader/odoo-shopinvader, pull requests merged in 2021-03, with the labels that each got.

#898 IMP shopin: backport test from 12.0
  shopinvader/tests/test_customer.py
Labels: approved, bot is merging ⏳

#887 [FW] 14.0 forward port 783 & 878
  shopinvader/data/ir_export_product.xml
  shopinvader/models/shopinvader_category.py
  shopinvader/models/shopinvader_product.py
  shopinvader/models/shopinvader_variant.py
  shopinvader/services/abstract_sale.py
  shopinvader/tests/common.py
  shopinvader/tests/test_cart_item.py
  shopinvader/tests/test_product.py
  shopinvader/views/shopinvader_variant_view.xml
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_delivery_carrier/services/delivery_carrier.py
  shopinvader_elasticsearch/tests/test_shopinvader_elasticsearch.py
  shopinvader_image/__init__.py
  shopinvader_image/services/__init__.py
  shopinvader_image/services/abstract_sale.py
  shopinvader_invoice/services/invoice.py
  shopinvader_locomotive/component/shopinvader_site_export_mapper.py
  shopinvader_product_stock/tests/test_product.py
  shopinvader_product_template_multi_link/tests/test_product.py
  shopinvader_quotation/services/__init__.py
  shopinvader_quotation/services/abstract_sale.py
  shopinvader_sale_packaging/services/abstract_sale.py
  shopinvader_sale_packaging/tests/test_cart.py
  shopinvader_sale_packaging/tests/test_sale.py
  shopinvader_sale_packaging_wishlist/services/wishlist.py
  shopinvader_sale_packaging_wishlist/tests/test_wishlist_packaging.py
  shopinvader_search_engine/models/shopinvader_variant.py
  shopinvader_wishlist/services/wishlist.py
  shopinvader_wishlist/tests/test_wishlist.py
Labels: approved, bot is merging ⏳, ready to merge

#912 s_customer_multi_user: fix test usage of MockRequest
  shopinvader_customer_multi_user/tests/test_multi_user_service_ctx.py
Labels: bot is merging ⏳

#880 [14.0] [MIG] shopinvader_multi_category
  .pre-commit-config.yaml
  setup/shopinvader_multi_category/odoo/addons/shopinvader_multi_category
  setup/shopinvader_multi_category/setup.py
  shopinvader_multi_category/__init__.py
  shopinvader_multi_category/__manifest__.py
  shopinvader_multi_category/models/__init__.py
  shopinvader_multi_category/models/shopinvader_product.py
  shopinvader_multi_category/tests/__init__.py
Labels: 14.0, approved, bot is merging ⏳, ready to merge

#724 [10.0][IMP] shopinvader_promotion_rule: let possibility to disable promotion rule by backend
  shopinvader_promotion_rule/__manifest__.py
  shopinvader_promotion_rule/models/__init__.py
  shopinvader_promotion_rule/models/sale_promotion_rule.py
  shopinvader_promotion_rule/models/shopinvader_backend.py
  shopinvader_promotion_rule/tests/test_cart.py
  shopinvader_promotion_rule/views/sale_promotion_rule.xml
Labels: 10.0, approved, bot is merging ⏳, enhancement, needs review, ready to merge

#909 shopinvader_algolia: preserve settings from index config
  shopinvader_algolia/models/se_index.py
  shopinvader_algolia/tests/test_export.py
Labels: 13.0, bot is merging ⏳, bug

#905 [10.0][FIX] shopinvader_membership: missing ID in search
  shopinvader_membership/services/membership_product.py
  shopinvader_membership/tests/test_membership_product_service.py
Labels: 10.0, approved, bot is merging ⏳, enhancement, needs review, ready to merge

#897 [14.0][FIX] shopinvader: make the base_pricelist and base_pricelist.currency_id fields defined in the tests usable globally
  shopinvader/tests/common.py
  shopinvader/tests/test_product.py
Labels: 14.0, approved, bot is merging ⏳, enhancement, needs review, ready to merge

#927 [IMP] add test to create shopinvader category from category
  shopinvader/tests/test_product.py
Labels: bot is merging ⏳

#929 [14.0][PORT] 928 from 13.0
  shopinvader/tests/test_product.py
Labels: bot is merging ⏳

#928 [13.0][PORT] 927 from 12.0
  shopinvader/tests/test_product.py
Labels: bot is merging ⏳

#446 [12.0][MIG][FW] shopinvader delivery instruction
  oca_dependencies.txt
  setup/shopinvader_delivery_instruction/odoo/addons/shopinvader_delivery_instruction
  setup/shopinvader_delivery_instruction/setup.py
  shopinvader_delivery_instruction/__init__.py
  shopinvader_delivery_instruction/__manifest__.py
  shopinvader_delivery_instruction/services/__init__.py
  shopinvader_delivery_instruction/services/abstract_sale.py
  shopinvader_delivery_instruction/services/cart.py
  shopinvader_delivery_instruction/tests/__init__.py
  shopinvader_delivery_instruction/tests/test_sale_order_picking_note.py
Labels: 12.0, approved, bot is merging ⏳, needs fixing, ready to merge

#682 [IMP] add a wizard for redirecting the product or the category manually
  shopinvader/__manifest__.py
  shopinvader/tests/__init__.py
  shopinvader/tests/test_redirection.py
  shopinvader/wizards/__init__.py
  shopinvader/wizards/shopinvader_redirection_wizard.py
  shopinvader/wizards/shopinvader_redirection_wizard.xml
Labels: 10.0, approved, bot is merging ⏳, needs review, ready to merge

#932 [14.0][PORT] 930 from 13.0
  .pre-commit-config.yaml
  shopinvader_delivery_instruction/__init__.py
  shopinvader_delivery_instruction/__manifest__.py
  shopinvader_delivery_instruction/services/__init__.py
  shopinvader_delivery_instruction/services/abstract_sale.py
  shopinvader_delivery_instruction/services/cart.py
  shopinvader_delivery_instruction/tests/__init__.py
  shopinvader_delivery_instruction/tests/test_sale_order_picking_note.py
Labels: bot is merging ⏳

#855 [MIG] 14.0 search_engine
  .pre-commit-config.yaml
  setup/shopinvader_search_engine/odoo/addons/shopinvader_search_engine
  setup/shopinvader_search_engine/setup.py
  shopinvader_search_engine/__manifest__.py
  shopinvader_search_engine/data/ir_export_product.xml
  shopinvader_search_engine/models/shopinvader_backend.py
  shopinvader_search_engine/models/shopinvader_category.py
  shopinvader_search_engine/models/shopinvader_variant.py
  shopinvader_search_engine/tests/test_delete_product.py
  shopinvader_search_engine/views/product_category_view.xml
  shopinvader_search_engine/views/product_view.xml
  shopinvader_search_engine/views/shopinvader_backend_view.xml
  test-requirements.txt
Labels: 14.0, approved, bot is merging ⏳, migration, needs review, ready to merge

#930 [13.0][PORT] 446 from 12.0
  setup/shopinvader_delivery_instruction/odoo/addons/shopinvader_delivery_instruction
  setup/shopinvader_delivery_instruction/setup.py
  shopinvader_delivery_instruction/__init__.py
  shopinvader_delivery_instruction/__manifest__.py
  shopinvader_delivery_instruction/services/__init__.py
  shopinvader_delivery_instruction/services/abstract_sale.py
  shopinvader_delivery_instruction/services/cart.py
  shopinvader_delivery_instruction/tests/__init__.py
  shopinvader_delivery_instruction/tests/test_sale_order_picking_note.py
Labels: bot is merging ⏳

#862 [MIG] shopinvader_cart_expiry: Migration to 14.0
  .pre-commit-config.yaml
  setup/shopinvader_cart_expiry/odoo/addons/shopinvader_cart_expiry
  setup/shopinvader_cart_expiry/setup.py
  shopinvader_cart_expiry/__manifest__.py
  shopinvader_cart_expiry/data/ir_cron.xml
  shopinvader_cart_expiry/data/queue_job_function_data.xml
  shopinvader_cart_expiry/models/sale_order.py
  shopinvader_cart_expiry/models/shopinvader_backend.py
  shopinvader_cart_expiry/tests/test_cart_expiry.py
  shopinvader_cart_expiry/views/shopinvader_backend.xml
Labels: 14.0, approved, bot is merging ⏳, migration, needs review, ready to merge

#729 [FIX] Services with empty description
  shopinvader/services/address.py
  shopinvader/services/cart.py
  shopinvader/services/customer.py
  shopinvader/services/invoice.py
  shopinvader/services/sale.py
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_lead/services/lead.py
Labels: 12.0, approved, bot is merging ⏳, ready to merge

#881 [14.0] [MIG] shopinvader_invoice
  .pre-commit-config.yaml
  setup/shopinvader_invoice/odoo/addons/shopinvader_invoice
  setup/shopinvader_invoice/setup.py
  shopinvader_invoice/__manifest__.py
  shopinvader_invoice/services/invoice.py
  shopinvader_invoice/tests/common.py
  shopinvader_invoice/tests/test_invoice_service.py
Labels: 14.0, approved, bot is merging ⏳, ready to merge

#872 [13.0][FIX] computing image must be done in sudo
  shopinvader_image/models/shopinvader_image_mixin.py
Labels: 13.0, bot is merging ⏳, enhancement

#866 [MIG] shopinvader_sale_profile: Migration to 14.0
  .pre-commit-config.yaml
  setup/shopinvader_sale_profile/odoo/addons/shopinvader_sale_profile
  setup/shopinvader_sale_profile/setup.py
  shopinvader_sale_profile/__manifest__.py
  shopinvader_sale_profile/demo/account_fiscal_position.xml
  shopinvader_sale_profile/demo/shopinvader_sale_profile.xml
  shopinvader_sale_profile/models/shopinvader_backend.py
  shopinvader_sale_profile/models/shopinvader_partner.py
  shopinvader_sale_profile/models/shopinvader_sale_profile.py
  shopinvader_sale_profile/security/shopinvader_sale_profile.xml
  shopinvader_sale_profile/tests/test_customer_service.py
  shopinvader_sale_profile/tests/test_shopinvader_backend_sale_profile.py
  shopinvader_sale_profile/tests/test_shopinvader_sale_profile.py
  shopinvader_sale_profile/views/res_partner.xml
  shopinvader_sale_profile/views/shopinvader_backend.xml
  shopinvader_sale_profile/views/shopinvader_partner.xml
Labels: 14.0, approved, bot is merging ⏳, ready to merge

#865 [MIG] shopinvader_product_variant_selector: Migration to 14.0
  .pre-commit-config.yaml
  setup/shopinvader_product_variant_selector/odoo/addons/shopinvader_product_variant_selector
  setup/shopinvader_product_variant_selector/setup.py
  shopinvader_product_variant_selector/__manifest__.py
  shopinvader_product_variant_selector/data/ir_export_product.xml
  shopinvader_product_variant_selector/demo/product_demo.xml
  shopinvader_product_variant_selector/models/shopinvader_variant.py
  shopinvader_product_variant_selector/tests/test_shopinvader_variant.py
Labels: 14.0, approved, bot is merging ⏳, ready to merge

#910 s_wishlist: fix variant lookup by lang
  shopinvader_wishlist/models/product_set.py
  shopinvader_wishlist/tests/test_product_set.py
  shopinvader_wishlist/views/product_set.xml
Labels: 13.0, approved, bot is merging ⏳, enhancement, needs review, ready to merge

#857 [MIG] 14.0 shopinvader_image
  .pre-commit-config.yaml
  setup/shopinvader_image/odoo/addons/shopinvader_image
  setup/shopinvader_image/setup.py
  shopinvader_image/__manifest__.py
  shopinvader_image/data/ir_export_category.xml
  shopinvader_image/data/ir_export_product.xml
  shopinvader_image/data/shopinvader_image_resize.xml
  shopinvader_image/demo/backend_demo.xml
  shopinvader_image/demo/product_image_relation_demo.xml
  shopinvader_image/demo/product_product_image_relation_demo.xml
  shopinvader_image/demo/storage_file_demo.xml
  shopinvader_image/demo/storage_image_demo.xml
  shopinvader_image/demo/storage_image_product_image_tag_demo.xml
  shopinvader_image/models/shopinvader_image_mixin.py
  shopinvader_image/tests/__init__.py
  shopinvader_image/tests/common.py
  shopinvader_image/tests/test_cart.py
  shopinvader_image/tests/test_getting_image.py
  shopinvader_image/tests/test_images.py
  shopinvader_image/views/shopinvader_backend_view.xml
  shopinvader_image/views/shopinvader_image_resize_view.xml
Labels: 14.0, approved, bot is merging ⏳, migration, needs review, ready to merge

#806 [10.0][IMP] shopinvader: Improve tests without tracking
  shopinvader/tests/common.py
Labels: 10.0, approved, bot is merging ⏳, ready to merge

#777 [12.0][IMP] shopinvader: Demo data with default code
  shopinvader/demo/product_product_demo.xml
Labels: 12.0, approved, bot is merging ⏳, enhancement, needs review

#732 [10.0][ADD] shopinvader Add the real level on the shopinvader.categor…
  shopinvader/data/ir_export_category.xml
  shopinvader/models/shopinvader_category.py
  shopinvader/tests/__init__.py
  shopinvader/tests/test_shopinvader_category.py
Labels: 10.0, approved, bot is merging ⏳, enhancement, needs review, ready to merge

#907 [ADD] 14.0 cancel and redraft sale endpoint
  shopinvader/services/sale.py
  shopinvader/tests/__init__.py
  shopinvader/tests/test_sale.py
  shopinvader/tests/test_sale_cancel.py
Labels: 14.0, approved, bot is merging ⏳, enhancement, needs review, ready to merge

#712 [10.0][IMP] shopinvader_guest_mode: Allow to bind a guest to real
  shopinvader_guest_mode/README.rst
  shopinvader_guest_mode/__init__.py
  shopinvader_guest_mode/__manifest__.py
  shopinvader_guest_mode/demo/partner_demo.xml
  shopinvader_guest_mode/readme/CONTRIBUTORS.rst
  shopinvader_guest_mode/readme/CREDITS.rst
  shopinvader_guest_mode/readme/DESCRIPTION.rst
  shopinvader_guest_mode/readme/USAGE.rst
  shopinvader_guest_mode/static/description/index.html
  shopinvader_guest_mode/tests/__init__.py
  shopinvader_guest_mode/tests/test_guest_binding.py
  shopinvader_guest_mode/wizards/__init__.py
  shopinvader_guest_mode/wizards/partner_binding_line.py
  shopinvader_guest_mode/wizards/partner_binding_wizard.py
  shopinvader_guest_mode/wizards/partner_binding_wizard.xml
Labels: 10.0, approved, bot is merging ⏳, enhancement, needs fixing, needs review, ready to merge

#864 [MIG] shopinvader_customer_multi_user: Migration to 14.0
  .pre-commit-config.yaml
  setup/shopinvader_customer_multi_user/odoo/addons/shopinvader_customer_multi_user
  setup/shopinvader_customer_multi_user/setup.py
  shopinvader_customer_multi_user/__manifest__.py
  shopinvader_customer_multi_user/migrations/13.0.1.1.0/pre-migrate.py
  shopinvader_customer_multi_user/migrations/13.0.1.2.0/post-migrate.py
  shopinvader_customer_multi_user/models/res_partner.py
  shopinvader_customer_multi_user/models/shopinvader_partner.py
  shopinvader_customer_multi_user/services/address.py
  shopinvader_customer_multi_user/services/customer.py
  shopinvader_customer_multi_user/services/service.py
  shopinvader_customer_multi_user/tests/test_multi_user_customer.py
  shopinvader_customer_multi_user/tests/test_multi_user_partner.py
  shopinvader_customer_multi_user/tests/test_multi_user_service_ctx.py
  shopinvader_customer_multi_user/tests/test_multi_user_service_partner_domain.py
  shopinvader_customer_multi_user/tests/test_multi_user_token.py
  shopinvader_customer_multi_user/views/partner_view.xml
  shopinvader_customer_multi_user/views/shopinvader_backend.xml
  shopinvader_customer_multi_user/views/shopinvader_partner_view.xml
Labels: 14.0, approved, bot is merging ⏳, ready to merge

#886 [13.0] Add shopinvader_product_template_multi_link_date_span
  setup/shopinvader_product_template_multi_link_date_span/odoo/addons/shopinvader_product_template_multi_link_date_span
  setup/shopinvader_product_template_multi_link_date_span/setup.py
  shopinvader_product_template_multi_link/models/shopinvader_product_link_mixin.py
  shopinvader_product_template_multi_link/tests/common.py
  shopinvader_product_template_multi_link/tests/test_product.py
  shopinvader_product_template_multi_link_date_span/README.rst
  shopinvader_product_template_multi_link_date_span/__init__.py
  shopinvader_product_template_multi_link_date_span/__manifest__.py
  shopinvader_product_template_multi_link_date_span/models/__init__.py
  shopinvader_product_template_multi_link_date_span/models/shopinvader_product_link_mixin.py
  shopinvader_product_template_multi_link_date_span/readme/CONTRIBUTORS.rst
  shopinvader_product_template_multi_link_date_span/readme/CREDITS.rst
  shopinvader_product_template_multi_link_date_span/readme/DESCRIPTION.rst
  shopinvader_product_template_multi_link_date_span/static/description/index.html
  shopinvader_product_template_multi_link_date_span/tests/__init__.py
  shopinvader_product_template_multi_link_date_span/tests/test_product.py
  shopinvader_product_variant_multi_link/tests/test_product.py
Labels: 13.0, bot is merging ⏳, needs review
