Repository shopinvader/odoo-shopinvader, pull requests merged in 2021-12, with the labels that each got.

#1182 [13.0][FIX] shopinvader: Sale Order UX
  shopinvader/views/sale_view.xml
Labels: approved, ready to merge, bot is merging ⏳, TODO: fwd-v14

#1164 [14.0][ADD] shopinvader_product_manufactured_for
  setup/shopinvader_product_manufactured_for/odoo/addons/shopinvader_product_manufactured_for
  setup/shopinvader_product_manufactured_for/setup.py
  shopinvader_product_manufactured_for/README.rst
  shopinvader_product_manufactured_for/__init__.py
  shopinvader_product_manufactured_for/__manifest__.py
  shopinvader_product_manufactured_for/data/ir_export_product.xml
  shopinvader_product_manufactured_for/models/__init__.py
  shopinvader_product_manufactured_for/models/shopinvader_product.py
  shopinvader_product_manufactured_for/models/shopinvader_variant.py
  shopinvader_product_manufactured_for/readme/CONTRIBUTORS.rst
  shopinvader_product_manufactured_for/readme/CREDITS.rst
  shopinvader_product_manufactured_for/readme/DESCRIPTION.rst
  shopinvader_product_manufactured_for/static/description/index.html
  shopinvader_product_manufactured_for/tests/__init__.py
  shopinvader_product_manufactured_for/tests/test_customer_special_product.py
Labels: needs fixing, approved, ready to merge, bot is merging ⏳, 14.0

#1151 [IMP] shopinvader: Add customer update method
  shopinvader/services/address.py
  shopinvader/services/customer.py
  shopinvader/tests/test_customer.py
Labels: approved, ready to merge, bot is merging ⏳

#1152 [14.0][IMP] shopinvader.partner form -- use sheet
  shopinvader/views/shopinvader_partner_view.xml
  shopinvader_customer_multi_user/views/shopinvader_partner_view.xml
  shopinvader_customer_validate/views/shopinvader_partner_view.xml
  shopinvader_sale_profile/views/shopinvader_partner.xml
Labels: approved, ready to merge, bot is merging ⏳

#1173 [REF][14.0] shopinvader_multi_cart: Use typology
  shopinvader_multi_cart/__init__.py
  shopinvader_multi_cart/__manifest__.py
  shopinvader_multi_cart/models/__init__.py
  shopinvader_multi_cart/models/sale_order.py
  shopinvader_multi_cart/readme/DESCRIPTION.rst
  shopinvader_multi_cart/services/__init__.py
  shopinvader_multi_cart/services/cart.py
  shopinvader_multi_cart/services/carts.py
  shopinvader_multi_cart/tests/test_carts.py
  shopinvader_multi_cart/views/sale_order.xml
Labels: bot is merging ⏳

#1196 [14.0][FIX] shopinvader: Sale Order UX
  shopinvader/views/sale_view.xml
  shopinvader/views/shopinvader_sale_view.xml
  shopinvader_quotation/views/sale_view.xml
Labels: bot is merging ⏳

#1188 [14.0][IMP] shopinvader_customer_multi_user: decouple allowed type fr…
  shopinvader_customer_multi_user/services/address.py
Labels: bot is merging ⏳

#1197 s_notification_default: fix validate notification
  shopinvader_customer_validate/__manifest__.py
  shopinvader_customer_validate/data/email_template.xml
  shopinvader_customer_validate/data/shopinvader_notification.xml
  shopinvader_customer_validate/readme/DESCRIPTION.rst
  shopinvader_customer_validate/templates/customer_address_email.xml
  shopinvader_customer_validate/templates/customer_profile_email.xml
  shopinvader_notification_default/data/email_template.xml
  shopinvader_notification_default/data/shopinvader_notification.xml
  shopinvader_notification_default/readme/DESCRIPTION.rst
  shopinvader_notification_default/templates/customer_address_email.xml
  shopinvader_notification_default/templates/customer_profile_email.xml
Labels: bug, approved, ready to merge, bot is merging ⏳, 14.0

#1201 [14.0][ADD] shopinvader_contact_address_default
  setup/shopinvader_contact_address_default/odoo/addons/shopinvader_contact_address_default
  setup/shopinvader_contact_address_default/setup.py
  shopinvader_contact_address_default/__init__.py
  shopinvader_contact_address_default/__manifest__.py
  shopinvader_contact_address_default/readme/CONTRIBUTORS.rst
  shopinvader_contact_address_default/readme/DESCRIPTION.rst
  shopinvader_contact_address_default/services/__init__.py
  shopinvader_contact_address_default/services/address.py
  shopinvader_contact_address_default/tests/__init__.py
  shopinvader_contact_address_default/tests/test_address.py
Labels: approved, ready to merge, bot is merging ⏳

#1203 cart: split create cart line
  shopinvader/services/cart.py
Labels: approved, bot is merging ⏳

#1158 [14.0][FIX] shopinvader_invoice number could be empty.
  shopinvader_invoice/services/invoice.py
  shopinvader_invoice/tests/test_invoice_service.py
Labels: approved, ready to merge, bot is merging ⏳

#1184 [14.0][ADD] shopinvader_product_stock_forecast 📦 📈
  setup/shopinvader_product_stock_forecast/odoo/addons/shopinvader_product_stock_forecast
  setup/shopinvader_product_stock_forecast/setup.py
  shopinvader_product_stock_forecast/__init__.py
  shopinvader_product_stock_forecast/__manifest__.py
  shopinvader_product_stock_forecast/models/__init__.py
  shopinvader_product_stock_forecast/models/shopinvader_backend.py
  shopinvader_product_stock_forecast/models/shopinvader_variant.py
  shopinvader_product_stock_forecast/readme/CONFIGURE.rst
  shopinvader_product_stock_forecast/readme/CONTRIBUTORS.rst
  shopinvader_product_stock_forecast/readme/DESCRIPTION.rst
  shopinvader_product_stock_forecast/readme/ROADMAP.rst
  shopinvader_product_stock_forecast/tests/__init__.py
  shopinvader_product_stock_forecast/tests/common.py
  shopinvader_product_stock_forecast/tests/test_product.py
  shopinvader_product_stock_forecast/views/shopinvader_backend.xml
Labels: bot is merging ⏳

#1198 [14.0] shopinvader_quotation : fixes and improvements
  shopinvader_quotation/models/sale_order.py
  shopinvader_quotation/readme/CONTRIBUTORS.rst
  shopinvader_quotation/readme/DESCRIPTION.rst
  shopinvader_quotation/services/quotation.py
  shopinvader_quotation/tests/test_quotation.py
Labels: bot is merging ⏳

#1174 [IMP] add name on sale order line
  shopinvader/services/abstract_sale.py
Labels: bot is merging ⏳

#1204 [13.0][IMP] shopinvader_sale_profile: Do not use fiscal position on sale profile computation when fpos are not configured
  shopinvader_sale_profile/models/shopinvader_partner.py
Labels: approved, bot is merging ⏳

#1206 shopinvader.variant._get_shop_data: bypass permission check
  shopinvader/models/shopinvader_variant.py
Labels: bug, approved, ready to merge, bot is merging ⏳, 14.0, TODO: bkp-v13

#1205 Fix product.price parser line must be in core
  shopinvader/data/ir_export_product.xml
  shopinvader_search_engine/__manifest__.py
  shopinvader_search_engine/data/ir_export_product.xml
Labels: bug, approved, ready to merge, bot is merging ⏳, 14.0, TODO: bkp-v13
