Repository shopinvader/odoo-shopinvader, pull requests merged in 2021-06, with the labels that each got.

#982 [13.0] s_wishlist: handle missing bindings gently
  shopinvader_customer_price_wishlist/services/wishlist.py
  shopinvader_customer_price_wishlist/tests/test_wishlist_price.py
  shopinvader_wishlist/models/product_set.py
  shopinvader_wishlist/services/wishlist.py
  shopinvader_wishlist/tests/test_product_set.py
  shopinvader_wishlist/tests/test_wishlist.py
Labels: 13.0, approved, bot is merging ⏳, enhancement, ready to merge

#984 [14.0] shopinvader: forward port all recent goodies from v13 (part 1)
  shopinvader/controllers/main.py
  shopinvader/models/shopinvader_variant.py
  shopinvader/services/abstract_sale.py
  shopinvader/services/address.py
  shopinvader/services/cart.py
  shopinvader/services/service.py
  shopinvader/tests/__init__.py
  shopinvader/tests/test_search.py
  shopinvader/views/shopinvader_variant_view.xml
  shopinvader/wizards/shopinvader_variant_binding_wizard.py
Labels: 14.0, bot is merging ⏳, enhancement, forwardport

#968 [14.0] shopinvader_search_engine: support lang agnostic indexes
  shopinvader_search_engine/data/ir_export_product.xml
  shopinvader_search_engine/models/se_index.py
  shopinvader_search_engine/models/shopinvader_backend.py
  shopinvader_search_engine/tests/__init__.py
  shopinvader_search_engine/tests/test_backend.py
  shopinvader_search_engine/views/shopinvader_backend_view.xml
Labels: 14.0, bot is merging ⏳, enhancement

#986 [14.0] shopinvader: forward port all recent goodies from v13 (part 2)
  shopinvader/data/queue_job_channel_data.xml
  shopinvader/data/queue_job_function_data.xml
  shopinvader/models/product_filter.py
  shopinvader/models/shopinvader_backend.py
  shopinvader/tests/common.py
  shopinvader/tests/test_backend.py
  shopinvader/tests/test_product.py
  shopinvader/tests/test_product_filter.py
  shopinvader/tests/test_shopinvader_variant_binding_wizard.py
  shopinvader/views/product_filter_view.xml
  shopinvader/wizards/shopinvader_variant_binding_wizard.py
  shopinvader/wizards/shopinvader_variant_binding_wizard.xml
  shopinvader_assortment/tests/test_product_auto_bind.py
Labels: 14.0, bot is merging ⏳, enhancement, forwardport

#976 [MIG] shopinvader_product_stock*: Migration to 14.0
  .pre-commit-config.yaml
  requirements.txt
  setup/shopinvader_product_stock/odoo/addons/shopinvader_product_stock
  setup/shopinvader_product_stock/setup.py
  setup/shopinvader_product_stock_state/odoo/addons/shopinvader_product_stock_state
  setup/shopinvader_product_stock_state/setup.py
  shopinvader_product_stock/__manifest__.py
  shopinvader_product_stock/data/ir_export_product.xml
  shopinvader_product_stock/data/queue_job_function_data.xml
  shopinvader_product_stock/models/product_product.py
  shopinvader_product_stock/models/shopinvader_backend.py
  shopinvader_product_stock/models/shopinvader_variant.py
  shopinvader_product_stock/models/stock_move.py
  shopinvader_product_stock/tests/common.py
  shopinvader_product_stock/tests/test_product.py
  shopinvader_product_stock/views/shopinvader_backend.xml
  shopinvader_product_stock_state/__manifest__.py
  shopinvader_product_stock_state/models/shopinvader_variant.py
  shopinvader_product_stock_state/tests/test_product.py
Labels: 14.0, bot is merging ⏳, migration

#990 [14.0][FIX] shopinvader: fix onchange() bug on unbind wizards
  shopinvader/readme/CONTRIBUTORS.rst
  shopinvader/wizards/shopinvader_category_unbinding_wizard.py
  shopinvader/wizards/shopinvader_variant_unbinding_wizard.py
  shopinvader/wizards/shopinvader_variant_unbinding_wizard.xml
Labels: bot is merging ⏳

#992 [13.0] s_wishlist: misc fixes
  shopinvader_wishlist/services/wishlist.py
  shopinvader_wishlist/tests/test_wishlist.py
Labels: approved, bot is merging ⏳, ready to merge

#996 [13.0] Add shopinvader_portal_mode
  setup/shopinvader_portal_mode/odoo/addons/shopinvader_portal_mode
  setup/shopinvader_portal_mode/setup.py
  shopinvader/models/shopinvader_backend.py
  shopinvader_portal_mode/README.rst
  shopinvader_portal_mode/__init__.py
  shopinvader_portal_mode/__manifest__.py
  shopinvader_portal_mode/models/__init__.py
  shopinvader_portal_mode/models/shopinvader_backend.py
  shopinvader_portal_mode/readme/CONTRIBUTORS.rst
  shopinvader_portal_mode/readme/CREDITS.rst
  shopinvader_portal_mode/readme/DESCRIPTION.rst
  shopinvader_portal_mode/services/__init__.py
  shopinvader_portal_mode/services/sale.py
  shopinvader_portal_mode/static/description/index.html
  shopinvader_portal_mode/tests/__init__.py
  shopinvader_portal_mode/tests/test_sale.py
  shopinvader_portal_mode/views/shopinvader_backend.xml
Labels: 13.0, approved, bot is merging ⏳, ready to merge
