Repository shopinvader/odoo-shopinvader, pull requests merged in 2021-11, with the labels that each got.

#1160 [14.0][FIX] shopinvader_search_engine: Unlinking of active records/bindings
  shopinvader_search_engine/models/shopinvader_se_binding.py
  shopinvader_search_engine/tests/test_delete_product.py
Labels: bot is merging ⏳

#1159 [14.0] shopinvader: fix compute_shopinvader_category
  shopinvader/models/shopinvader_product.py
Labels: bot is merging ⏳, 14.0

#1156 [14.0][IMP] shopinvader_delivery_carrier : code cleanup & small improvements 🧹
  shopinvader_delivery_carrier/models/sale.py
  shopinvader_delivery_carrier/services/abstract_sale.py
  shopinvader_delivery_carrier/services/cart.py
  shopinvader_delivery_carrier/services/delivery_carrier.py
  shopinvader_delivery_carrier/tests/test_carrier.py
Labels: approved, bot is merging ⏳

#1166 [13.0] Sync copier template
  .copier-answers.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: 13.0

#1165 [13.0] shopinvader: fix invoice domain
  shopinvader/services/invoice.py
  shopinvader_portal_mode/tests/__init__.py
  shopinvader_portal_mode/tests/common.py
  shopinvader_portal_mode/tests/test_invoice.py
  shopinvader_portal_mode/tests/test_sale.py
Labels: bug, approved, 13.0, bot is merging ⏳, TODO: fwd-v14

#1175 [FIX] default code should be not mandatory
  shopinvader/models/shopinvader_variant.py
Labels: bot is merging ⏳

#1169 [14.0][MIG] shopinvader_portal_mode
  setup/shopinvader_portal_mode/odoo/addons/shopinvader_portal_mode
  setup/shopinvader_portal_mode/setup.py
  shopinvader/models/shopinvader_backend.py
  shopinvader/services/invoice.py
  shopinvader_portal_mode/README.rst
  shopinvader_portal_mode/__init__.py
  shopinvader_portal_mode/__manifest__.py
  shopinvader_portal_mode/i18n/shopinvader_portal_mode.pot
  shopinvader_portal_mode/models/__init__.py
  shopinvader_portal_mode/models/shopinvader_backend.py
  shopinvader_portal_mode/readme/CONTRIBUTORS.rst
  shopinvader_portal_mode/readme/CREDITS.rst
  shopinvader_portal_mode/readme/DESCRIPTION.rst
  shopinvader_portal_mode/services/__init__.py
  shopinvader_portal_mode/services/sale.py
  shopinvader_portal_mode/static/description/index.html
  shopinvader_portal_mode/tests/__init__.py
  shopinvader_portal_mode/tests/common.py
  shopinvader_portal_mode/tests/test_invoice.py
  shopinvader_portal_mode/tests/test_sale.py
  shopinvader_portal_mode/views/shopinvader_backend.xml
Labels: approved, ready to merge, bot is merging ⏳, migration, 14.0

#1172 [IMP][14.0] shopinvader: Sales Order UX
  shopinvader/__manifest__.py
  shopinvader/models/shopinvader_backend.py
  shopinvader/views/sale_view.xml
  shopinvader/views/shopinvader_backend_view.xml
  shopinvader/views/shopinvader_menu.xml
  shopinvader/views/shopinvader_sale_view.xml
  shopinvader_quotation/views/sale_view.xml
Labels: bot is merging ⏳

#1177 [13.0][IMP] shopinvader: Sale Order UX
  shopinvader/__manifest__.py
  shopinvader/models/shopinvader_backend.py
  shopinvader/views/sale_view.xml
  shopinvader/views/shopinvader_backend_view.xml
  shopinvader/views/shopinvader_menu.xml
  shopinvader/views/shopinvader_sale_view.xml
  shopinvader_quotation/views/sale_view.xml
Labels: bot is merging ⏳

#1154 [ADD] shopinvader_product_brand_tag
  setup/shopinvader_product_brand_tag/odoo/addons/shopinvader_product_brand_tag
  setup/shopinvader_product_brand_tag/setup.py
  shopinvader_product_brand_tag/__init__.py
  shopinvader_product_brand_tag/__manifest__.py
  shopinvader_product_brand_tag/data/ir_export_product.xml
  shopinvader_product_brand_tag/data/ir_export_product_brand.xml
  shopinvader_product_brand_tag/models/__init__.py
  shopinvader_product_brand_tag/models/shopinvader_brand.py
  shopinvader_product_brand_tag/readme/CONTRIBUTORS.rst
  shopinvader_product_brand_tag/readme/DESCRIPTION.rst
Labels: approved, ready to merge, bot is merging ⏳

#1187 [13.0][IMP] shopinvader_customer_multi_user: decouple allowed type
  shopinvader_customer_multi_user/services/address.py
Labels: bot is merging ⏳

#1189 [FIX] shopinvader: easy expose model // swagger
  shopinvader/services/service.py
Labels: bot is merging ⏳
