Repository shopinvader/odoo-shopinvader, pull requests merged in 2021-07, with the labels that each got.

#861 [MIG] 14.0 product media
  .pre-commit-config.yaml
  setup/shopinvader_product_media/odoo/addons/shopinvader_product_media
  setup/shopinvader_product_media/setup.py
  shopinvader_product_media/__manifest__.py
  shopinvader_product_media/data/ir_product_export.xml
Labels: 14.0, approved, bot is merging ⏳, migration, needs review, ready to merge

#856 [MIG] 14.0 algolia
  .pre-commit-config.yaml
  setup/shopinvader_algolia/odoo/addons/shopinvader_algolia
  setup/shopinvader_algolia/setup.py
  shopinvader_algolia/__manifest__.py
  shopinvader_algolia/data/ir_export_product.xml
  shopinvader_algolia/demo/backend_demo.xml
  shopinvader_algolia/demo/product_demo.xml
  shopinvader_algolia/models/shopinvader_variant.py
  shopinvader_algolia/tests/cassettes/TestAlgoliaBackend.test_10_export_one_product.yaml
  shopinvader_algolia/tests/cassettes/TestAlgoliaBackend.test_20_export_all_products.yaml
  shopinvader_algolia/tests/cassettes/TestAlgoliaBackend.test_30_export_all_categories.yaml
  shopinvader_algolia/tests/test_export.py
  shopinvader_algolia/views/shopinvader_variant_view.xml
Labels: 14.0, approved, bot is merging ⏳, migration, needs review, ready to merge

#1010 [FWD][14.0] shopinvader: partner form quick edit form for invader partner
  shopinvader/models/shopinvader_partner.py
  shopinvader/views/partner_view.xml
  shopinvader/views/shopinvader_partner_view.xml
Labels: 14.0, approved, bot is merging ⏳

#1006 [14.0][ADD] shopinvader_sale_amount_by_group
  setup/shopinvader_sale_amount_by_group/odoo/addons/shopinvader_sale_amount_by_group
  setup/shopinvader_sale_amount_by_group/setup.py
  shopinvader_sale_amount_by_group/README.rst
  shopinvader_sale_amount_by_group/__init__.py
  shopinvader_sale_amount_by_group/__manifest__.py
  shopinvader_sale_amount_by_group/demo/account.xml
  shopinvader_sale_amount_by_group/readme/CONTRIBUTORS.rst
  shopinvader_sale_amount_by_group/readme/DESCRIPTION.rst
  shopinvader_sale_amount_by_group/services/__init__.py
  shopinvader_sale_amount_by_group/services/abstract_sale.py
  shopinvader_sale_amount_by_group/tests/__init__.py
  shopinvader_sale_amount_by_group/tests/test_cart.py
Labels: approved, bot is merging ⏳

#858 [MIG] 14.0 delivery carrier
  .pre-commit-config.yaml
  setup/shopinvader_delivery_carrier/odoo/addons/shopinvader_delivery_carrier
  setup/shopinvader_delivery_carrier/setup.py
  shopinvader_delivery_carrier/__manifest__.py
  shopinvader_delivery_carrier/controllers/main.py
  shopinvader_delivery_carrier/data/cart_step.xml
  shopinvader_delivery_carrier/demo/backend_demo.xml
  shopinvader_delivery_carrier/demo/mail_template.xml
  shopinvader_delivery_carrier/demo/shopinvader_notification.xml
  shopinvader_delivery_carrier/models/delivery_carrier.py
  shopinvader_delivery_carrier/models/sale.py
  shopinvader_delivery_carrier/models/stock_picking.py
  shopinvader_delivery_carrier/services/abstract_sale.py
  shopinvader_delivery_carrier/services/cart.py
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_delivery_carrier/services/delivery_carrier.py
  shopinvader_delivery_carrier/tests/common.py
  shopinvader_delivery_carrier/tests/test_carrier.py
  shopinvader_delivery_carrier/tests/test_delivery_carrier.py
  shopinvader_delivery_carrier/tests/test_delivery_service.py
  shopinvader_delivery_carrier/tests/test_notification.py
  shopinvader_delivery_carrier/tests/test_sale_service.py
  shopinvader_delivery_carrier/views/backend_view.xml
Labels: 14.0, approved, bot is merging ⏳, migration, needs review, ready to merge

#1004 [14.0][MIG] shopinvader_partner_firstname: Migration to 14.0
  .pre-commit-config.yaml
  setup/shopinvader_partner_firstname/odoo/addons/shopinvader_partner_firstname
  setup/shopinvader_partner_firstname/setup.py
  shopinvader_partner_firstname/__manifest__.py
  shopinvader_partner_firstname/readme/CONTRIBUTORS.rst
  shopinvader_partner_firstname/services/__init__.py
  shopinvader_partner_firstname/services/address.py
  shopinvader_partner_firstname/services/customer.py
  shopinvader_partner_firstname/tests/test_firstname.py
Labels: approved, bot is merging ⏳

#1014 [14.0][PORT] 634 from 10.0
  shopinvader/services/invoice.py
  shopinvader/tests/test_invoice.py
  shopinvader_delivery_carrier/services/delivery.py
  shopinvader_delivery_carrier/services/delivery_carrier.py
  shopinvader_delivery_carrier/tests/test_delivery_carrier.py
  shopinvader_invoice/tests/common.py
  shopinvader_invoice/tests/test_invoice_service.py
  shopinvader_lead/services/lead.py
  shopinvader_lead/tests/test_lead.py
Labels: approved, bot is merging ⏳

#1011 [FWD][14.0] Unify work context management
  shopinvader/components/access_info.py
  shopinvader/controllers/main.py
  shopinvader/services/customer.py
  shopinvader/services/partner_mixin.py
  shopinvader/services/service.py
  shopinvader/tests/__init__.py
  shopinvader/tests/common.py
  shopinvader/tests/test_cart.py
  shopinvader/tests/test_customer.py
  shopinvader/tests/test_partner_access_info.py
  shopinvader/tests/test_salesman_notification.py
  shopinvader/tests/test_utils.py
  shopinvader/utils.py
Labels: 14.0, approved, bot is merging ⏳

#1002 [14.0][ADD] shopinvader_sale_coupon
  setup/shopinvader_sale_coupon/odoo/addons/shopinvader_sale_coupon
  setup/shopinvader_sale_coupon/setup.py
  shopinvader_sale_coupon/README.rst
  shopinvader_sale_coupon/__init__.py
  shopinvader_sale_coupon/__manifest__.py
  shopinvader_sale_coupon/services/__init__.py
  shopinvader_sale_coupon/services/abstract_sale.py
  shopinvader_sale_coupon/services/cart.py
  shopinvader_sale_coupon/tests/__init__.py
  shopinvader_sale_coupon/tests/test_cart.py
Labels: approved, bot is merging ⏳

#1003 s_product_template_multi_link: fix indexed ID
  shopinvader_product_template_multi_link/models/shopinvader_product_link_mixin.py
  shopinvader_product_template_multi_link/tests/test_product.py
  shopinvader_product_variant_multi_link/tests/test_product.py
Labels: 13.0, bot is merging ⏳

#870 [14.0][mig] shopinvader_locomotive_algolia
  .pre-commit-config.yaml
  setup/shopinvader_locomotive_algolia/odoo/addons/shopinvader_locomotive_algolia
  setup/shopinvader_locomotive_algolia/setup.py
  shopinvader_locomotive_algolia/__manifest__.py
  shopinvader_locomotive_algolia/models/se_backend_algolia.py
Labels: 14.0, bot is merging ⏳

#972 [MIG] shopinvader_wishlist: Migration to 14.0
  .pre-commit-config.yaml
  setup/shopinvader_wishlist/odoo/addons/shopinvader_wishlist
  setup/shopinvader_wishlist/setup.py
  shopinvader_sale_packaging_wishlist/tests/test_wishlist_packaging.py
  shopinvader_wishlist/__init__.py
  shopinvader_wishlist/__manifest__.py
  shopinvader_wishlist/components/__init__.py
  shopinvader_wishlist/components/access_info.py
  shopinvader_wishlist/demo/product_set.xml
  shopinvader_wishlist/models/product_set.py
  shopinvader_wishlist/services/wishlist.py
  shopinvader_wishlist/tests/test_product_set.py
  shopinvader_wishlist/tests/test_wishlist.py
  shopinvader_wishlist/views/product_set.xml
  shopinvader_wishlist/wizard/product_set_add.xml
Labels: approved, bot is merging ⏳, ready to merge

#1019 [14.0][FIX] shopinvader_sale_coupon: Coupon parser for relational fields
  shopinvader_sale_coupon/services/abstract_sale.py
  shopinvader_sale_coupon/tests/test_cart.py
Labels: bot is merging ⏳

#1005 [MIG] shopinvader_quotation: Migration to 14.0
  .pre-commit-config.yaml
  setup/shopinvader_quotation/odoo/addons/shopinvader_quotation
  setup/shopinvader_quotation/setup.py
  shopinvader_quotation/__manifest__.py
  shopinvader_quotation/data/ir_export_product.xml
  shopinvader_quotation/demo/email_demo.xml
  shopinvader_quotation/demo/notification_demo.xml
  shopinvader_quotation/models/__init__.py
  shopinvader_quotation/models/product_template.py
  shopinvader_quotation/models/sale.py
  shopinvader_quotation/models/sale_order.py
  shopinvader_quotation/readme/CONTRIBUTORS.rst
  shopinvader_quotation/readme/DESCRIPTION.rst
  shopinvader_quotation/services/cart.py
  shopinvader_quotation/services/quotation.py
  shopinvader_quotation/tests/test_notification.py
  shopinvader_quotation/tests/test_quotation.py
  shopinvader_quotation/tests/test_quotation_download.py
  shopinvader_quotation/views/product_view.xml
  shopinvader_quotation/views/sale_view.xml
Labels: bot is merging ⏳

#975 [MIG] shopinvader_locomotive_wishlist: Migration to 14.0
  .pre-commit-config.yaml
  setup/shopinvader_locomotive_wishlist/odoo/addons/shopinvader_locomotive_wishlist
  setup/shopinvader_locomotive_wishlist/setup.py
  shopinvader_locomotive_wishlist/__manifest__.py
  shopinvader_locomotive_wishlist/components/event_listeners.py
  shopinvader_locomotive_wishlist/components/shopinvader_partner_export_mapper.py
  shopinvader_locomotive_wishlist/services/wishlist.py
  shopinvader_locomotive_wishlist/tests/test_shopinvader_partner.py
  shopinvader_locomotive_wishlist/tests/test_wishlist.py
Labels: 14.0, bot is merging ⏳, migration

#1025 [14.0] s_customer_multi_user: fwd ports from v13 + Add shopinvader_customer_multi_user_validate
  setup/shopinvader_customer_multi_user_validate/odoo/addons/shopinvader_customer_multi_user_validate
  setup/shopinvader_customer_multi_user_validate/setup.py
  shopinvader_customer_multi_user/__init__.py
  shopinvader_customer_multi_user/components/__init__.py
  shopinvader_customer_multi_user/components/access_info.py
  shopinvader_customer_multi_user/models/res_partner.py
  shopinvader_customer_multi_user/models/shopinvader_partner.py
  shopinvader_customer_multi_user/services/__init__.py
  shopinvader_customer_multi_user/services/address.py
  shopinvader_customer_multi_user/services/customer.py
  shopinvader_customer_multi_user/services/service.py
  shopinvader_customer_multi_user/services/user_management.py
  shopinvader_customer_multi_user/tests/__init__.py
  shopinvader_customer_multi_user/tests/common.py
  shopinvader_customer_multi_user/tests/test_multi_user_customer.py
  shopinvader_customer_multi_user/tests/test_multi_user_management.py
  shopinvader_customer_multi_user/tests/test_multi_user_partner.py
  shopinvader_customer_multi_user/tests/test_multi_user_service_ctx.py
  shopinvader_customer_multi_user/tests/test_multi_user_service_partner_domain.py
  shopinvader_customer_multi_user/tests/test_multi_user_token.py
  shopinvader_customer_multi_user/tests/test_partner_access_info.py
  shopinvader_customer_multi_user/views/partner_view.xml
  shopinvader_customer_multi_user/views/shopinvader_partner_view.xml
  shopinvader_customer_multi_user_validate/README.rst
  shopinvader_customer_multi_user_validate/__init__.py
  shopinvader_customer_multi_user_validate/__manifest__.py
  shopinvader_customer_multi_user_validate/readme/CONTRIBUTORS.rst
  shopinvader_customer_multi_user_validate/readme/CREDITS.rst
  shopinvader_customer_multi_user_validate/readme/DESCRIPTION.rst
  shopinvader_customer_multi_user_validate/services/__init__.py
  shopinvader_customer_multi_user_validate/services/user_management.py
  shopinvader_customer_validate/tests/test_partner_access_info.py
  shopinvader_customer_validate/views/partner_view.xml
Labels: bot is merging ⏳

#980 [MIG] shopinvader_customer_multi_user_wishlist: Migration to 14.0
  .pre-commit-config.yaml
  setup/shopinvader_customer_multi_user_wishlist/odoo/addons/shopinvader_customer_multi_user_wishlist
  setup/shopinvader_customer_multi_user_wishlist/setup.py
  shopinvader_customer_multi_user_wishlist/__manifest__.py
  shopinvader_customer_multi_user_wishlist/tests/test_wishlist.py
Labels: 14.0, bot is merging ⏳, migration

#871 [14.0][MIG] shopinvader_import_image
  .pre-commit-config.yaml
  requirements.txt
  setup/shopinvader_import_image/odoo/addons/shopinvader_import_image
  setup/shopinvader_import_image/setup.py
  shopinvader_import_image/__manifest__.py
  shopinvader_import_image/data/queue_job_function_data.xml
  shopinvader_import_image/i18n/shopinvader_import_image.pot
  shopinvader_import_image/models/import_image.py
  shopinvader_import_image/security/ir_model_access.xml
  shopinvader_import_image/tests/test_import_image.py
  shopinvader_import_image/views/import_product_image_view.xml
  shopinvader_import_image/views/report_html.xml
Labels: 14.0, approved, bot is merging ⏳, migration

#985 s_sale_by_packaging: adapt to packaging calc updates
  shopinvader_sale_packaging/__manifest__.py
  shopinvader_sale_packaging/migrations/13.0.2.4.0/post-migrate.py
  shopinvader_sale_packaging/models/shopinvader_variant.py
  shopinvader_sale_packaging/services/packaging_mixin.py
  shopinvader_sale_packaging/tests/test_product_data.py
Labels: 13.0, approved, bot is merging ⏳, enhancement

#997 [13.0][FIX] shopinvader: One main variant per shopinvader.product
  shopinvader/models/shopinvader_variant.py
  shopinvader/tests/test_product.py
Labels: TODO: fwd-v14, bot is merging ⏳

#936 [14.0][FIX] fix demo data
  shopinvader/demo/product_product_demo.xml
Labels: approved, bot is merging ⏳, ready to merge

#995 [14.0] cart.add_item: add hook for passing default vals for new cart
  shopinvader/services/cart.py
Labels: 14.0, approved, bot is merging ⏳, enhancement

#1020 [14.0][ADD] shopinvader_product_template_tags
  setup/shopinvader_product_template_tags/odoo/addons/shopinvader_product_template_tags
  setup/shopinvader_product_template_tags/setup.py
  shopinvader_product_template_tags/__init__.py
  shopinvader_product_template_tags/__manifest__.py
  shopinvader_product_template_tags/data/ir_export_product.xml
  shopinvader_product_template_tags/readme/CONTRIBUTORS.rst
  shopinvader_product_template_tags/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#1008 [13.0] Add shopinvader_delivery_state
  setup/shopinvader_delivery_state/odoo/addons/shopinvader_delivery_state
  setup/shopinvader_delivery_state/setup.py
  shopinvader/models/sale.py
  shopinvader_delivery_state/README.rst
  shopinvader_delivery_state/__init__.py
  shopinvader_delivery_state/__manifest__.py
  shopinvader_delivery_state/hooks.py
  shopinvader_delivery_state/models/__init__.py
  shopinvader_delivery_state/models/sale_order.py
  shopinvader_delivery_state/readme/CONTRIBUTORS.rst
  shopinvader_delivery_state/readme/CREDITS.rst
  shopinvader_delivery_state/readme/DESCRIPTION.rst
  shopinvader_delivery_state/tests/__init__.py
  shopinvader_delivery_state/tests/test_sale.py
Labels: TODO: fwd-v14, approved, bot is merging ⏳, ready to merge

#1016 [14.0][REF] clean up mix with id and object id fix issue #1000
  shopinvader/data/ir_export_category.xml
  shopinvader/data/ir_export_product.xml
  shopinvader/models/shopinvader_category.py
  shopinvader/readme/CHANGES.rst
  shopinvader/tests/test_cart_item.py
  shopinvader_algolia/tests/cassettes/TestAlgoliaBackend.test_10_export_one_product.yaml
  shopinvader_algolia/tests/cassettes/TestAlgoliaBackend.test_20_export_all_products.yaml
  shopinvader_algolia/tests/cassettes/TestAlgoliaBackend.test_30_export_all_categories.yaml
  shopinvader_elasticsearch/tests/cassettes/TestElasticsearchBackend.test_10_export_one_product.yaml
  shopinvader_elasticsearch/tests/cassettes/TestElasticsearchBackend.test_20_export_all_products.yaml
  shopinvader_elasticsearch/tests/cassettes/TestElasticsearchBackend.test_30_export_all_categories.yaml
  shopinvader_elasticsearch/tests/test_shopinvader_elasticsearch.py
  shopinvader_sale_packaging/tests/test_cart.py
Labels: 14.0, approved, bot is merging ⏳, ready to merge

#1032 [MIG] shopinvader_lead: Migration to 14.0
  .pre-commit-config.yaml
  setup/shopinvader_lead/odoo/addons/shopinvader_lead
  setup/shopinvader_lead/setup.py
  shopinvader_lead/__manifest__.py
  shopinvader_lead/demo/email_demo.xml
  shopinvader_lead/demo/notification_demo.xml
  shopinvader_lead/models/notification.py
  shopinvader_lead/readme/ROADMAP.rst
  shopinvader_lead/services/lead.py
  shopinvader_lead/tests/test_lead.py
Labels: approved, bot is merging ⏳

#868 [MIG] shopinvader_locomotive_sale_profile: Migration to 14.0
  .pre-commit-config.yaml
  setup/shopinvader_locomotive_sale_profile/odoo/addons/shopinvader_locomotive_sale_profile
  setup/shopinvader_locomotive_sale_profile/setup.py
  shopinvader_locomotive_sale_profile/__manifest__.py
  shopinvader_locomotive_sale_profile/tests/test_shopinvader_partner.py
Labels: 14.0, approved, bot is merging ⏳, migration, needs review, ready to merge

#1024 [ADD][14.0] shopinvader_product_price_tax
  setup/shopinvader_product_price_tax/odoo/addons/shopinvader_product_price_tax
  setup/shopinvader_product_price_tax/setup.py
  shopinvader/models/shopinvader_variant.py
  shopinvader/tests/test_product.py
  shopinvader_product_price_tax/__init__.py
  shopinvader_product_price_tax/__manifest__.py
  shopinvader_product_price_tax/models/__init__.py
  shopinvader_product_price_tax/models/shopinvader_variant.py
  shopinvader_product_price_tax/readme/CONTRIBUTORS.rst
  shopinvader_product_price_tax/readme/DESCRIPTION.rst
  shopinvader_product_price_tax/tests/__init__.py
  shopinvader_product_price_tax/tests/test_product.py
  shopinvader_sale_profile/models/shopinvader_variant.py
Labels: 14.0, approved, bot is merging ⏳

#1027 [14.0] [FIX] fix url redirection
  base_url/models/abstract_url.py
  base_url/tests/test_abstract_url.py
  shopinvader/models/product_template.py
  shopinvader/tests/common.py
  shopinvader/tests/test_product.py
  shopinvader/tests/test_shopinvader_category.py
Labels: 14.0, TODO: bkp-v13, bot is merging ⏳

#1034 [14.0][ADD] shopinvader_multi_cart
  setup/shopinvader_multi_cart/odoo/addons/shopinvader_multi_cart
  setup/shopinvader_multi_cart/setup.py
  shopinvader_multi_cart/__init__.py
  shopinvader_multi_cart/__manifest__.py
  shopinvader_multi_cart/readme/CONTRIBUTORS.rst
  shopinvader_multi_cart/readme/DESCRIPTION.rst
  shopinvader_multi_cart/services/__init__.py
  shopinvader_multi_cart/services/carts.py
  shopinvader_multi_cart/tests/__init__.py
  shopinvader_multi_cart/tests/test_carts.py
Labels: 14.0, approved, bot is merging ⏳

#1035 shopinvader_customer_validate: fix validator lookup
  shopinvader/models/shopinvader_backend.py
  shopinvader_customer_validate/models/shopinvader_backend.py
Labels: bot is merging ⏳, bug

#1028 [13.0] s_sale_packaging: fix pkg data prepare
  shopinvader_sale_packaging/models/shopinvader_variant.py
Labels: 13.0, approved, bot is merging ⏳

#1001 [14.0] Add shopinvader_product_brand
  setup/shopinvader_product_brand/odoo/addons/shopinvader_product_brand
  setup/shopinvader_product_brand/setup.py
  shopinvader/models/shopinvader_binding.py
  shopinvader/models/shopinvader_category.py
  shopinvader/models/shopinvader_variant.py
  shopinvader_product_brand/__init__.py
  shopinvader_product_brand/__manifest__.py
  shopinvader_product_brand/data/ir_export_brand.xml
  shopinvader_product_brand/data/ir_export_product.xml
  shopinvader_product_brand/models/__init__.py
  shopinvader_product_brand/models/product_brand.py
  shopinvader_product_brand/models/shopinvader_brand.py
  shopinvader_product_brand/models/shopinvader_product.py
  shopinvader_product_brand/readme/CONTRIBUTORS.rst
  shopinvader_product_brand/readme/DESCRIPTION.rst
  shopinvader_product_brand/security/ir.model.access.csv
  shopinvader_product_brand/tests/__init__.py
  shopinvader_product_brand/tests/test_brand.py
  shopinvader_product_brand/views/product_brand_view.xml
  shopinvader_product_brand/views/shopinvader_brand_view.xml
  shopinvader_search_engine/models/__init__.py
  shopinvader_search_engine/models/shopinvader_category.py
  shopinvader_search_engine/models/shopinvader_se_binding.py
  shopinvader_search_engine/models/shopinvader_variant.py
Labels: 14.0, approved, bot is merging ⏳, ready to merge

#1039 [14.0] s_product_brand: add bind all btn + counter
  shopinvader_product_brand/__manifest__.py
  shopinvader_product_brand/models/__init__.py
  shopinvader_product_brand/models/shopinvader_backend.py
  shopinvader_product_brand/readme/CONTRIBUTORS.rst
  shopinvader_product_brand/views/shopinvader_backend_view.xml
  shopinvader_product_brand/views/shopinvader_brand_view.xml
Labels: bot is merging ⏳

#1040 14.0 bump saerch engine
  shopinvader/__manifest__.py
  shopinvader_search_engine/__manifest__.py
Labels: bot is merging ⏳

#1038 [14.0][IMP] shopinvader_customer_multi_user : Address sharing policy
  shopinvader_customer_multi_user/models/res_partner.py
  shopinvader_customer_multi_user/models/shopinvader_partner.py
  shopinvader_customer_multi_user/services/address.py
  shopinvader_customer_multi_user/services/customer.py
  shopinvader_customer_multi_user/tests/test_multi_user_service_partner_domain.py
  shopinvader_customer_multi_user/views/partner_view.xml
Labels: bot is merging ⏳

#1051 [14.0] [FIX] shopinvader_auth_api_key: Fix openapi doc generation
  shopinvader_auth_api_key/services/service.py
Labels: bot is merging ⏳
