Repository shopinvader/odoo-shopinvader, pull requests merged in 2022-09, with the labels that each got.

#1096 [13.0][MIG] shopinvader_product_attribute_set
  setup/shopinvader_product_attribute_set/odoo/addons/shopinvader_product_attribute_set
  setup/shopinvader_product_attribute_set/setup.py
  shopinvader_product_attribute_set/README.rst
  shopinvader_product_attribute_set/__init__.py
  shopinvader_product_attribute_set/__manifest__.py
  shopinvader_product_attribute_set/data/ir_export_product.xml
  shopinvader_product_attribute_set/demo/product_filter.xml
  shopinvader_product_attribute_set/i18n/shopinvader_product_attribute_set.pot
  shopinvader_product_attribute_set/models/__init__.py
  shopinvader_product_attribute_set/models/attribute_attribute.py
  shopinvader_product_attribute_set/models/product_filter.py
  shopinvader_product_attribute_set/models/shopinvader_variant.py
  shopinvader_product_attribute_set/readme/CONTRIBUTORS.rst
  shopinvader_product_attribute_set/readme/DESCRIPTION.rst
  shopinvader_product_attribute_set/static/description/index.html
  shopinvader_product_attribute_set/tests/__init__.py
  shopinvader_product_attribute_set/tests/test_product.py
  shopinvader_product_attribute_set/views/product_filter_view.xml
Labels: bot is merging ⏳

#1317 [14.0][FIX] Fix pylint
  .pre-commit-config.yaml
  shopinvader/models/product_category.py
  shopinvader/models/shopinvader_backend.py
  shopinvader/models/shopinvader_product.py
  shopinvader/tests/test_address.py
  shopinvader/tests/test_product.py
  shopinvader/tests/test_shopinvader_variant_seo_title.py
  shopinvader/wizards/shopinvader_variant_binding_wizard.py
  shopinvader_auth_api_key/tests/test_controller.py
  shopinvader_backend_image_proxy/tests/test_shopinvader_backend.py
  shopinvader_delivery_instruction/README.rst
  shopinvader_delivery_instruction/readme/CONTRIBUTORS.rst
  shopinvader_delivery_instruction/readme/CREDITS.rst
  shopinvader_delivery_instruction/readme/DESCRIPTION.rst
  shopinvader_delivery_instruction/static/description/index.html
  shopinvader_image/demo/product_image_relation_demo.xml
  shopinvader_image/demo/storage_file_demo.xml
  shopinvader_image/demo/storage_image_demo.xml
  shopinvader_locomotive/component/exporter.py
  shopinvader_locomotive/tests/common.py
  shopinvader_locomotive/tests/test_backend.py
  shopinvader_locomotive/tests/test_shopinvader_partner.py
  shopinvader_locomotive_guest_mode/tests/test_shopinvader_partner.py
  shopinvader_locomotive_sale_profile/tests/test_shopinvader_partner.py
  shopinvader_locomotive_wishlist/tests/test_shopinvader_partner.py
  shopinvader_multi_cart/tests/test_carts.py
  shopinvader_partner_vat/tests/test_check_vat.py
  shopinvader_product_stock/tests/test_product.py
  shopinvader_product_stock_assortment/README.rst
  shopinvader_product_stock_assortment/readme/CONTRIBUTORS.rst
  shopinvader_product_stock_assortment/readme/CREDITS.rst
  shopinvader_product_stock_assortment/readme/DESCRIPTION.rst
  shopinvader_product_stock_assortment/static/description/index.html
  shopinvader_product_video_link/README.rst
  shopinvader_product_video_link/readme/CONTRIBUTORS.rst
  shopinvader_product_video_link/readme/CREDITS.rst
  shopinvader_product_video_link/readme/DESCRIPTION.rst
  shopinvader_product_video_link/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#1304 [14.0][IMP] shopinvader_(search_engine): Improve ux
  shopinvader/views/shopinvader_backend_view.xml
  shopinvader_search_engine/views/shopinvader_backend_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1305 [14][FIX] shopinvader_portal_mode: prevent carts in search domain
  shopinvader_portal_mode/services/sale.py
Labels: approved, ready to merge, bot is merging ⏳

#1283 [14.0][IMP] shopinvader_elasticsearch: Don't replace the search engine backend
  shopinvader_elasticsearch/demo/backend_demo.xml
  shopinvader_elasticsearch/tests/test_settings.py
  shopinvader_elasticsearch/tests/test_shopinvader_elasticsearch.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#1274 [14.0][FIX] shopinvader: Don't do onchanges with sudo
  shopinvader/services/cart.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1243 [14.0] [IMP] shopinvader: Make WEBSITE_UNIQUE_KEY optional in case of single backend
  shopinvader/components/service_context_provider.py
  shopinvader/models/shopinvader_backend.py
Labels: approved, ready to merge, bot is merging ⏳

#1163 [14.0][FIX] shopinvader_delivery_carrier fix availability
  shopinvader_delivery_carrier/models/delivery_carrier.py
  shopinvader_delivery_carrier/models/sale.py
  shopinvader_delivery_carrier/services/cart.py
  shopinvader_delivery_carrier/services/delivery_carrier.py
  shopinvader_delivery_carrier/tests/test_carrier.py
  shopinvader_delivery_carrier/tests/test_delivery_carrier.py
Labels: needs fixing, bot is merging ⏳, 14.0

#1316 [14.0][IMP] shopinvader: add index on company
  shopinvader/models/shopinvader_binding.py
Labels: approved, ready to merge, bot is merging ⏳
