Repository shopinvader/odoo-shopinvader, pull requests merged in 2022-11, with the labels that each got.

#1286 shopinvader_quotation: add validity_date in json
  shopinvader_quotation/services/quotation.py
Labels: help wanted, approved, ready to merge, bot is merging ⏳

#1290 [14.0][UPD] shopinvader partner binding: dedicated res.groups
  shopinvader/migrations/14.0.5.14.1/post-migrate.py
  shopinvader/security/ir.model.access.csv
  shopinvader/security/shopinvader_security.xml
  shopinvader/wizards/shopinvader_partner_binding.xml
Labels: approved, ready to merge, bot is merging ⏳

#1333 shopinvader_locomotive_reset_password: fix reseting password
  shopinvader_locomotive_reset_password/models/partner.py
Labels: bot is merging ⏳
