Repository shopinvader/odoo-shopinvader, pull requests merged in 2022-04, with the labels that each got.

#1266 [14.0][FWD] shopinvader_wishlist and related modules fix/imp from 13.0
  shopinvader_customer_multi_user_wishlist/__init__.py
  shopinvader_customer_multi_user_wishlist/components/__init__.py
  shopinvader_customer_multi_user_wishlist/components/access_info.py
  shopinvader_customer_multi_user_wishlist/services/wishlist.py
  shopinvader_customer_multi_user_wishlist/tests/test_wishlist.py
  shopinvader_customer_price_wishlist/services/wishlist.py
  shopinvader_customer_price_wishlist/tests/test_wishlist_price.py
  shopinvader_wishlist/models/product_set.py
  shopinvader_wishlist/services/wishlist.py
  shopinvader_wishlist/tests/test_product_set.py
  shopinvader_wishlist/tests/test_wishlist.py
Labels: approved, bot is merging ⏳, forwardport, 14.0

#1265 [14.0][FIX] Fix sequence when adding an item
  shopinvader/services/cart.py
  shopinvader/tests/test_cart_item.py
Labels: approved, ready to merge, bot is merging ⏳

#1269 [14.0] [FIX] shopinvader: Force partner load in work ctx at customer creation
  shopinvader/services/customer.py
Labels: bot is merging ⏳

#1263 [FIX] shopinvader -> notifications (refactor account.invoice -> account.move)
  shopinvader/models/shopinvader_notification.py
Labels: approved, ready to merge, bot is merging ⏳

#1236 [14.0][ADD] `shopinvader_sale_automatic_workflow` : Use sale automatic workflows for Shopinvader orders 🤖
  setup/shopinvader_sale_automatic_workflow/odoo/addons/shopinvader_sale_automatic_workflow
  setup/shopinvader_sale_automatic_workflow/setup.py
  shopinvader_sale_automatic_workflow/__init__.py
  shopinvader_sale_automatic_workflow/__manifest__.py
  shopinvader_sale_automatic_workflow/models/__init__.py
  shopinvader_sale_automatic_workflow/models/shopinvader_backend.py
  shopinvader_sale_automatic_workflow/readme/CONTRIBUTORS.rst
  shopinvader_sale_automatic_workflow/readme/DESCRIPTION.rst
  shopinvader_sale_automatic_workflow/services/__init__.py
  shopinvader_sale_automatic_workflow/services/cart.py
  shopinvader_sale_automatic_workflow/tests/__init__.py
  shopinvader_sale_automatic_workflow/tests/test_automatic_workflow.py
  shopinvader_sale_automatic_workflow/views/shopinvader_backend.xml
Labels: approved, ready to merge, bot is merging ⏳

#1262 [14.0][IMP] shopinvader: accept country iso code to create/update addresses
  shopinvader/services/address.py
  shopinvader/tests/test_address.py
Labels: approved, ready to merge, bot is merging ⏳

#1202 [IMP] add shopinvader_product_video
  shopinvader_product_video_link/__init__.py
  shopinvader_product_video_link/__manifest__.py
  shopinvader_product_video_link/data/ir_export_category.xml
  shopinvader_product_video_link/data/ir_export_product.xml
Labels: approved, ready to merge, bot is merging ⏳

#1246 [14.0] shopinvader: add notebook to variant view
  shopinvader/views/shopinvader_variant_view.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳, 14.0

#1277 [14.0] Simplify usage w/out Locomotive
  shopinvader/demo/backend_demo.xml
  shopinvader/models/shopinvader_backend.py
  shopinvader/models/shopinvader_variant.py
  shopinvader/views/shopinvader_backend_view.xml
  shopinvader_auth_api_key/views/shopinvader_backend_view.xml
  shopinvader_auth_jwt/views/shopinvader_backend.xml
  shopinvader_locomotive/models/shopinvader_backend.py
  shopinvader_locomotive/views/shopinvader_backend_view.xml
  shopinvader_locomotive_reset_password/views/shopinvader_backend.xml
Labels: approved, ready to merge, bot is merging ⏳

#1279 [14.0][IMP] shopinvader_assortment: Don't activate cron by default
  shopinvader_assortment/data/ir_cron.xml
Labels: approved, bot is merging ⏳

#1256 [14.0][IMP] Set partner on lead if user is logged
  shopinvader_lead/services/lead.py
  shopinvader_lead/tests/test_lead.py
Labels: approved, bot is merging ⏳

#1261 [14.0][ADD] shopinvader_customer_activity
  setup/shopinvader_customer_activity/odoo/addons/shopinvader_customer_activity
  setup/shopinvader_customer_activity/setup.py
  shopinvader_customer_activity/__init__.py
  shopinvader_customer_activity/__manifest__.py
  shopinvader_customer_activity/models/__init__.py
  shopinvader_customer_activity/models/shopinvader_partner.py
  shopinvader_customer_activity/readme/CONTRIBUTORS.rst
  shopinvader_customer_activity/readme/DESCRIPTION.rst
  shopinvader_customer_activity/readme/ROADMAP.rst
  shopinvader_customer_activity/services/__init__.py
  shopinvader_customer_activity/services/service.py
  shopinvader_customer_activity/tests/__init__.py
  shopinvader_customer_activity/tests/test_service.py
  shopinvader_customer_activity/views/res_partner.xml
  shopinvader_customer_activity/views/shopinvader_partner.xml
Labels: approved, ready to merge, bot is merging ⏳
