Repository shopinvader/odoo-shopinvader, pull requests merged in 2022-01, with the labels that each got.

#1200 [14.0][ADD] shopinvader_product_stock_forecast_expiry
  setup/shopinvader_product_stock_forecast_expiry/odoo/addons/shopinvader_product_stock_forecast_expiry
  setup/shopinvader_product_stock_forecast_expiry/setup.py
  shopinvader_product_stock_forecast_expiry/__init__.py
  shopinvader_product_stock_forecast_expiry/__manifest__.py
  shopinvader_product_stock_forecast_expiry/models/__init__.py
  shopinvader_product_stock_forecast_expiry/models/shopinvader_backend.py
  shopinvader_product_stock_forecast_expiry/models/shopinvader_variant.py
  shopinvader_product_stock_forecast_expiry/readme/CONFIGURE.rst
  shopinvader_product_stock_forecast_expiry/readme/CONTRIBUTORS.rst
  shopinvader_product_stock_forecast_expiry/readme/DESCRIPTION.rst
  shopinvader_product_stock_forecast_expiry/tests/__init__.py
  shopinvader_product_stock_forecast_expiry/tests/test_product.py
  shopinvader_product_stock_forecast_expiry/views/shopinvader_backend.xml
Labels: approved, ready to merge, bot is merging ⏳

#1216 [14.0][FIX] duplicate labels
  shopinvader/models/shopinvader_variant.py
Labels: approved, bot is merging ⏳

#1214 [13.0][FIX] shopinvader_product_stock: Syncronize stock only on active bindings
  shopinvader_product_stock/models/product_product.py
Labels: approved, bot is merging ⏳

#1220 [14.0][FIX] s_customer_validate: fix access right issues when using actions
  shopinvader_customer_validate/models/res_partner.py
  shopinvader_customer_validate/models/shopinvader_partner.py
Labels: bot is merging ⏳

#1218 [14.0][FIX] shopinvader_product_stock: Syncronize stock only on active bindings
  shopinvader_product_stock/models/product_product.py
Labels: approved, bot is merging ⏳

#1217 [14.0][IMP] shopinvader_sale_coupon: Add valid coupons to customer info
  shopinvader_sale_coupon/services/__init__.py
  shopinvader_sale_coupon/services/customer.py
  shopinvader_sale_coupon/tests/test_customer.py
Labels: bot is merging ⏳
