Repository shopinvader/odoo-shopinvader, pull requests merged in 2022-02, with the labels that each got.

#1222 [14.0][IMP] shopinvader: `_get_price`: add `date` kwarg
  shopinvader/models/shopinvader_variant.py
  shopinvader_product_price_tax/models/shopinvader_variant.py
Labels: approved, bot is merging ⏳

#1224 [FIX] shopinvader: adding products to a confirmed cart
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
Labels: approved, bot is merging ⏳

#1190 [13.0][IMP] shopinvader: add website field in address service
  shopinvader/services/address.py
Labels: approved, ready to merge, bot is merging ⏳

#1161 [14.0][IMP] shopinvader_guest_mode: disable welcome message for guest
  shopinvader_guest_mode/services/__init__.py
  shopinvader_guest_mode/services/partner_mixin.py
  shopinvader_guest_mode/tests/__init__.py
  shopinvader_guest_mode/tests/test_notification.py
Labels: bot is merging ⏳

#913 [10.0][ADD] shopinvader_membership: add the membership_id (product_id)
  requirements.txt
  setup/shopinvader_import_image/setup.py
  shopinvader_import_image/__manifest__.py
  shopinvader_membership/services/membership.py
  shopinvader_membership/tests/test_membership_service.py
  shopinvader_product_template_multi_link/models/shopinvader_product.py
  shopinvader_product_template_multi_link/tests/test_product.py
Labels: needs review, approved, 10.0, ready to merge, bot is merging ⏳

#838 [10.0][FIX] shopinvader: the pricelist shouldn't be updated during sign-in
  shopinvader/services/customer.py
  shopinvader/tests/test_cart.py
Labels: 10.0

#774 [10.0][FIX] Multi company: some fields computed as sudo
  shopinvader/__manifest__.py
  shopinvader/demo/res_users.xml
  shopinvader/models/shopinvader_partner.py
  shopinvader/tests/test_shopinvader_partner.py
  shopinvader_sale_profile/models/shopinvader_partner.py
  shopinvader_sale_profile/tests/test_shopinvader_partner.py
Labels: enhancement, needs review, 10.0

#743 [10.0][IMP] shopinvader: Use partner active state when bind
  shopinvader/tests/test_shopinvader_partner_binding.py
  shopinvader/wizards/shopinvader_partner_binding_line.py
Labels: enhancement, needs review, 10.0

#1213 [14.0][FIX] shopinvader_auth_jwt: accept array of aud
  shopinvader_auth_jwt/components/service_context_provider.py
  shopinvader_auth_jwt/models/shopinvader_backend.py
Labels: bot is merging ⏳

#1167 [14.0][FIX] shopinvader compute_main_product
  shopinvader/models/shopinvader_variant.py
  shopinvader/tests/test_product.py
Labels: approved, ready to merge, bot is merging ⏳

#1228 [14.0][TESTS] shopinvader*: assertEquals => assertEqual
  shopinvader/tests/test_customer.py
  shopinvader_cart_expiry/tests/test_cart_expiry.py
  shopinvader_delivery_instruction/tests/test_sale_order_picking_note.py
  shopinvader_membership/tests/test_membership_service.py
  shopinvader_promotion_rule/tests/test_cart.py
Labels: bot is merging ⏳

#1232 s_customer_price: align w/ objectID refactoring
  shopinvader_customer_price/services/customer_price.py
  shopinvader_customer_price/tests/test_customer_price.py
Labels: approved, bot is merging ⏳, 14.0

#1235 shopinvader: make cart._prepare_cart_item flexible
  shopinvader/services/cart.py
Labels: enhancement, approved, bot is merging ⏳, 14.0

#1195 [IMP] shopinvader_sale_coupon: Add tax included reward amount
  shopinvader_sale_coupon/__init__.py
  shopinvader_sale_coupon/models/__init__.py
  shopinvader_sale_coupon/models/sale_order.py
  shopinvader_sale_coupon/services/abstract_sale.py
  shopinvader_sale_coupon/tests/test_cart.py
Labels: bot is merging ⏳

#1170 [IMP] make the code more inheritable
  shopinvader/services/cart.py
Labels: approved, ready to merge, bot is merging ⏳

#1219 [14.0] ADD todo to stop using shopinvader.partner model
  shopinvader/utils.py
Labels: bot is merging ⏳

#1153 [14.0][FIX+IMP] shopinvader_sale_profile
  shopinvader_sale_profile/models/shopinvader_backend.py
  shopinvader_sale_profile/models/shopinvader_partner.py
  shopinvader_sale_profile/models/shopinvader_sale_profile.py
  shopinvader_sale_profile/models/shopinvader_variant.py
Labels: approved, ready to merge, bot is merging ⏳
