Repository shopinvader/odoo-shopinvader, pull requests merged in 2022-03, with the labels that each got.

#1242 [14.0][FIX] shopinvader: fix '_post' signature
  shopinvader/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1226 [14.0][IMP] shopinvader_customer_multi_user(_company_group)
  shopinvader_customer_multi_user/tests/common.py
  shopinvader_customer_multi_user/tests/test_multi_user_management.py
  shopinvader_customer_multi_user/tests/test_multi_user_partner.py
  shopinvader_customer_multi_user/tests/test_multi_user_service_partner_domain.py
  shopinvader_customer_multi_user/tests/test_multi_user_token.py
  shopinvader_customer_multi_user/tests/test_partner_access_info.py
  shopinvader_customer_multi_user_company_group/__manifest__.py
  shopinvader_customer_multi_user_company_group/models/__init__.py
  shopinvader_customer_multi_user_company_group/models/shopinvader_backend.py
  shopinvader_customer_multi_user_company_group/models/shopinvader_partner.py
  shopinvader_customer_multi_user_company_group/tests/__init__.py
  shopinvader_customer_multi_user_company_group/tests/common.py
  shopinvader_customer_multi_user_company_group/tests/test_multi_user_service_partner_domain.py
  shopinvader_customer_multi_user_company_group/views/shopinvader_backend.xml
Labels: approved, ready to merge, bot is merging ⏳

#1254 shopinvader_customer_price: fix parser
  shopinvader_customer_price/services/customer_price.py
  shopinvader_customer_price/tests/test_customer_price.py
Labels: bot is merging ⏳, 14.0

#1023 [14.0][MIG] shopinvader_delivery_instruction from 13.0
  .pre-commit-config.yaml
  oca_dependencies.txt
  setup/shopinvader_delivery_instruction/odoo/addons/shopinvader_delivery_instruction
  setup/shopinvader_delivery_instruction/setup.py
  shopinvader_delivery_instruction/__manifest__.py
  shopinvader_delivery_instruction/services/abstract_sale.py
  shopinvader_delivery_instruction/services/cart.py
  shopinvader_delivery_instruction/tests/test_sale_order_picking_note.py
Labels: needs fixing, bot is merging ⏳, 14.0
