Repository shopinvader/odoo-shopinvader, pull requests merged in 2023-06, with the labels that each got.

#1063 [14.0][MIG] shopinvader_delivery_carrier_category_keep_carrier from 10.0
  setup/shopinvader_delivery_carrier_category_keep_carrier/odoo/addons/shopinvader_delivery_carrier_category_keep_carrier
  setup/shopinvader_delivery_carrier_category_keep_carrier/setup.py
  shopinvader_delivery_carrier_category_keep_carrier/README.rst
  shopinvader_delivery_carrier_category_keep_carrier/__init__.py
  shopinvader_delivery_carrier_category_keep_carrier/__manifest__.py
  shopinvader_delivery_carrier_category_keep_carrier/models/__init__.py
  shopinvader_delivery_carrier_category_keep_carrier/models/delivery_carrier_category.py
  shopinvader_delivery_carrier_category_keep_carrier/readme/CONTRIBUTORS.rst
  shopinvader_delivery_carrier_category_keep_carrier/readme/DESCRIPTION.rst
  shopinvader_delivery_carrier_category_keep_carrier/readme/INSTALL.rst
  shopinvader_delivery_carrier_category_keep_carrier/readme/USAGE.rst
  shopinvader_delivery_carrier_category_keep_carrier/services/__init__.py
  shopinvader_delivery_carrier_category_keep_carrier/services/cart.py
  shopinvader_delivery_carrier_category_keep_carrier/static/description/icon.png
  shopinvader_delivery_carrier_category_keep_carrier/static/description/index.html
  shopinvader_delivery_carrier_category_keep_carrier/tests/__init__.py
  shopinvader_delivery_carrier_category_keep_carrier/tests/test_carrier.py
  shopinvader_delivery_carrier_category_keep_carrier/views/delivery_carrier_category.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳, migration, add module

#1147 [14.0][IMP] shopinvader_locomotive: add id for country's states
  shopinvader_locomotive/component/shopinvader_site_export_mapper.py
  shopinvader_locomotive/tests/test_backend.py
Labels: bot is merging ⏳

#1185 [IMP] In quotations menu, do not display carts
  shopinvader/views/sale_view.xml
Labels: bot is merging ⏳

#1234 [FIX] Do not send standard sale confirmation email
  shopinvader/models/sale.py
Labels: bot is merging ⏳

#1109 [14.0][ADD] shopinvader_mass_mailing_company_newsletter
  setup/shopinvader_mass_mailing_company_newsletter/odoo/addons/shopinvader_mass_mailing_company_newsletter
  setup/shopinvader_mass_mailing_company_newsletter/setup.py
  shopinvader_mass_mailing_company_newsletter/__init__.py
  shopinvader_mass_mailing_company_newsletter/__manifest__.py
  shopinvader_mass_mailing_company_newsletter/readme/CONTRIBUTORS.rst
  shopinvader_mass_mailing_company_newsletter/readme/DESCRIPTION.rst
  shopinvader_mass_mailing_company_newsletter/services/__init__.py
  shopinvader_mass_mailing_company_newsletter/services/address.py
  shopinvader_mass_mailing_company_newsletter/tests/__init__.py
  shopinvader_mass_mailing_company_newsletter/tests/test_mass_mailing_company_newsletter.py
Labels: bot is merging ⏳, add module

#1076 [14.0][ADD] adds shopinvader_sale_price_update
  setup/shopinvader_sale_update_price/odoo/addons/shopinvader_sale_update_price
  setup/shopinvader_sale_update_price/setup.py
  shopinvader_sale_update_price/README.rst
  shopinvader_sale_update_price/__init__.py
  shopinvader_sale_update_price/__manifest__.py
  shopinvader_sale_update_price/models/__init__.py
  shopinvader_sale_update_price/models/sale_order.py
  shopinvader_sale_update_price/models/shopinvader_backend.py
  shopinvader_sale_update_price/readme/CONTRIBUTORS.rst
  shopinvader_sale_update_price/readme/DESCRIPTION.rst
  shopinvader_sale_update_price/readme/USAGE.rst
  shopinvader_sale_update_price/static/description/icon.png
  shopinvader_sale_update_price/tests/__init__.py
  shopinvader_sale_update_price/tests/test_shopinvader_sale_price_update.py
  shopinvader_sale_update_price/views/shopinvader_backend.xml
Labels: needs fixing, bot is merging ⏳, add module

#1179 [IMP] shopinvader_sale_coupon: Add remove_coupon route to remove a coupon from code
  shopinvader_sale_coupon/services/cart.py
  shopinvader_sale_coupon/tests/test_cart.py
Labels: bot is merging ⏳

#1129 [14.0][ADD] shopinvader_sale_order_report_without_price
  setup/shopinvader_sale_order_report_without_price/odoo/addons/shopinvader_sale_order_report_without_price
  setup/shopinvader_sale_order_report_without_price/setup.py
  shopinvader_sale_order_report_without_price/README.rst
  shopinvader_sale_order_report_without_price/__init__.py
  shopinvader_sale_order_report_without_price/__manifest__.py
  shopinvader_sale_order_report_without_price/readme/CONTRIBUTORS.rst
  shopinvader_sale_order_report_without_price/readme/DESCRIPTION.rst
  shopinvader_sale_order_report_without_price/readme/USAGE.rst
  shopinvader_sale_order_report_without_price/services/__init__.py
  shopinvader_sale_order_report_without_price/services/sale.py
  shopinvader_sale_order_report_without_price/static/description/index.html
  shopinvader_sale_order_report_without_price/tests/__init__.py
  shopinvader_sale_order_report_without_price/tests/test_sale_download.py
Labels: bot is merging ⏳, add module

#1149 [14.0][FWP] Make difference between update done by customer and done by Odoo's interface
  shopinvader/models/__init__.py
  shopinvader/models/sale.py
  shopinvader/models/track_external_mixin.py
  shopinvader/services/cart.py
  shopinvader/services/service.py
  shopinvader/tests/common.py
  shopinvader/tests/test_cart.py
  shopinvader/tests/test_cart_item.py
  shopinvader_cart_expiry/__manifest__.py
  shopinvader_cart_expiry/migrations/14.0.1.0.1/post-migrate.py
  shopinvader_cart_expiry/models/shopinvader_backend.py
  shopinvader_cart_expiry/tests/test_cart_expiry.py
  shopinvader_pending_cart_reminder/models/sale_order.py
  shopinvader_pending_cart_reminder/tests/test_sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1086 [MIG][14.0] shopinvader_customer_autobind: Migration from 10.0
  setup/shopinvader_customer_autobind/odoo/addons/shopinvader_customer_autobind
  setup/shopinvader_customer_autobind/setup.py
  shopinvader/models/shopinvader_partner.py
  shopinvader/tests/test_shopinvader_partner.py
  shopinvader_customer_autobind/README.rst
  shopinvader_customer_autobind/__init__.py
  shopinvader_customer_autobind/__manifest__.py
  shopinvader_customer_autobind/components/__init__.py
  shopinvader_customer_autobind/components/res_partner_listener.py
  shopinvader_customer_autobind/demo/mail_template.xml
  shopinvader_customer_autobind/models/__init__.py
  shopinvader_customer_autobind/models/shopinvader_backend.py
  shopinvader_customer_autobind/readme/CONTRIBUTORS.rst
  shopinvader_customer_autobind/readme/DESCRIPTION.rst
  shopinvader_customer_autobind/readme/USAGE.rst
  shopinvader_customer_autobind/static/description/icon.png
  shopinvader_customer_autobind/static/description/index.html
  shopinvader_customer_autobind/tests/__init__.py
  shopinvader_customer_autobind/tests/test_partner_autobind.py
  shopinvader_customer_autobind/views/shopinvader_backend.xml
Labels: needs review, bot is merging ⏳, migration, add module, change

#1064 [14.0][MIG] shopinvader_promotion_rule from 13.0
  .pre-commit-config.yaml
  setup/shopinvader_promotion_rule/odoo/addons/shopinvader_promotion_rule
  setup/shopinvader_promotion_rule/setup.py
  shopinvader_promotion_rule/__manifest__.py
  shopinvader_promotion_rule/data/cart_step.xml
  shopinvader_promotion_rule/models/__init__.py
  shopinvader_promotion_rule/models/sale_order.py
  shopinvader_promotion_rule/services/__init__.py
  shopinvader_promotion_rule/services/abstract_sale_service.py
  shopinvader_promotion_rule/services/cart.py
  shopinvader_promotion_rule/tests/test_cart.py
Labels: needs review, bot is merging ⏳, migration, add module

#1199 [14.0][ADD] shopinvader_quotation_portal_mode
  setup/shopinvader_quotation_portal_mode/odoo/addons/shopinvader_quotation_portal_mode
  setup/shopinvader_quotation_portal_mode/setup.py
  shopinvader_quotation_portal_mode/README.rst
  shopinvader_quotation_portal_mode/__init__.py
  shopinvader_quotation_portal_mode/__manifest__.py
  shopinvader_quotation_portal_mode/readme/CONTRIBUTORS.rst
  shopinvader_quotation_portal_mode/readme/DESCRIPTION.rst
  shopinvader_quotation_portal_mode/services/__init__.py
  shopinvader_quotation_portal_mode/services/quotation.py
  shopinvader_quotation_portal_mode/tests/__init__.py
  shopinvader_quotation_portal_mode/tests/test_quotations.py
Labels: bot is merging ⏳

#1270 [14.0][IMP] shopinvader_sale_profile: Add tests for cart creation
  shopinvader_sale_profile/tests/__init__.py
  shopinvader_sale_profile/tests/test_shopinvader_cart.py
Labels: enhancement, needs review, bot is merging ⏳

#1309 [14.0][PORT] 623 from 12.0
  shopinvader/services/abstract_sale.py
  shopinvader/tests/test_cart.py
Labels: bot is merging ⏳, change

#1343 [FIX] 14.0 _add_item: consistent return value
  shopinvader/services/cart.py
Labels: bot is merging ⏳

#1341 shopinvader_delivery_carrier: do not create empty cart
  shopinvader_delivery_carrier/services/delivery_carrier.py
Labels: bot is merging ⏳

#1048 [14.0][MIG] shopinvader_validation_token_guest from v10.0
  setup/shopinvader_validation_token_guest/odoo/addons/shopinvader_validation_token_guest
  setup/shopinvader_validation_token_guest/setup.py
  shopinvader_validation_token/models/shopinvader_security_token.py
  shopinvader_validation_token/services/customer_service.py
  shopinvader_validation_token/tests/common.py
  shopinvader_validation_token/tests/test_customer_service.py
  shopinvader_validation_token_guest/README.rst
  shopinvader_validation_token_guest/__init__.py
  shopinvader_validation_token_guest/__manifest__.py
  shopinvader_validation_token_guest/models/__init__.py
  shopinvader_validation_token_guest/models/shopinvader_notification.py
  shopinvader_validation_token_guest/models/shopinvader_security_token.py
  shopinvader_validation_token_guest/readme/CONFIGURE.rst
  shopinvader_validation_token_guest/readme/CONTRIBUTORS.rst
  shopinvader_validation_token_guest/readme/DESCRIPTION.rst
  shopinvader_validation_token_guest/static/description/index.html
  shopinvader_validation_token_guest/tests/__init__.py
  shopinvader_validation_token_guest/tests/test_guest_service.py
Labels: needs review, bot is merging ⏳, migration, add module

#1281 [14.0] [FIX] shopinvader: don't create cart on search
  shopinvader/services/cart.py
  shopinvader/tests/test_cart.py
Labels: approved, bot is merging ⏳, change

#1310 [14.0][IMP] shopinvader_product_media: Add description to export lines
  shopinvader_product_media/data/ir_product_export.xml
Labels: bot is merging ⏳

#1328 [14.0] [IMP] `shopinvader_customer_multi_user_company_group`: Split records and address policies
  shopinvader_customer_multi_user_company_group/__manifest__.py
  shopinvader_customer_multi_user_company_group/migrations/14.0.2.0.0/post-migrate.py
  shopinvader_customer_multi_user_company_group/models/shopinvader_backend.py
  shopinvader_customer_multi_user_company_group/models/shopinvader_partner.py
  shopinvader_customer_multi_user_company_group/tests/test_multi_user_service_partner_domain.py
  shopinvader_customer_multi_user_company_group/views/shopinvader_backend.xml
Labels: bot is merging ⏳

#1315 [14.0] shoinvader_customer_validate: improve address validate wizard
  shopinvader_customer_validate/models/res_partner.py
  shopinvader_customer_validate/tests/__init__.py
  shopinvader_customer_validate/tests/test_address_validation.py
  shopinvader_customer_validate/tests/test_notification.py
  shopinvader_customer_validate/wizards/shopinvader_address_validate.py
  shopinvader_customer_validate/wizards/shopinvader_address_validate.xml
Labels: bot is merging ⏳

#1360 [16.0] [MIG] sale_cart
  requirements.txt
  sale_cart/README.rst
  sale_cart/__init__.py
  sale_cart/__manifest__.py
  sale_cart/hooks.py
  sale_cart/i18n/fr.po
  sale_cart/models/__init__.py
  sale_cart/models/sale_order.py
  sale_cart/readme/CONTRIBUTORS.rst
  sale_cart/readme/DESCRIPTION.rst
  sale_cart/tests/__init__.py
  sale_cart/tests/test_sale_cart.py
  sale_cart/views/sale_order.xml
  setup/sale_cart/odoo/addons/sale_cart
  setup/sale_cart/setup.py
Labels: bot is merging ⏳

#1331 Add shopinvader_locomotive_impersonate
  setup/shopinvader_locomotive_impersonate/odoo/addons/shopinvader_locomotive_impersonate
  setup/shopinvader_locomotive_impersonate/setup.py
  shopinvader_locomotive_impersonate/__init__.py
  shopinvader_locomotive_impersonate/__manifest__.py
  shopinvader_locomotive_impersonate/models/__init__.py
  shopinvader_locomotive_impersonate/models/shopinvader_partner.py
  shopinvader_locomotive_impersonate/readme/CONTRIBUTORS.rst
  shopinvader_locomotive_impersonate/readme/DESCRIPTION.rst
  shopinvader_locomotive_impersonate/security/res_groups.xml
  shopinvader_locomotive_impersonate/services/__init__.py
  shopinvader_locomotive_impersonate/services/customer.py
  shopinvader_locomotive_impersonate/tests/__init__.py
  shopinvader_locomotive_impersonate/tests/test_impersonate.py
  shopinvader_locomotive_impersonate/views/res_partner_view.xml
  shopinvader_locomotive_impersonate/views/shopinvader_partner_view.xml
Labels: approved, ready to merge, bot is merging ⏳, add module

#978 [14.0] Add shopinvader_product_seasonality
  setup/shopinvader_locomotive_product_seasonality/odoo/addons/shopinvader_locomotive_product_seasonality
  setup/shopinvader_locomotive_product_seasonality/setup.py
  setup/shopinvader_product_seasonality/odoo/addons/shopinvader_product_seasonality
  setup/shopinvader_product_seasonality/setup.py
  setup/shopinvader_product_seasonality_search_engine/odoo/addons/shopinvader_product_seasonality_search_engine
  setup/shopinvader_product_seasonality_search_engine/setup.py
  shopinvader/models/shopinvader_backend.py
  shopinvader_locomotive_product_seasonality/README.rst
  shopinvader_locomotive_product_seasonality/__init__.py
  shopinvader_locomotive_product_seasonality/__manifest__.py
  shopinvader_locomotive_product_seasonality/components/__init__.py
  shopinvader_locomotive_product_seasonality/components/shopinvader_site_export_mapper.py
  shopinvader_locomotive_product_seasonality/readme/CONTRIBUTORS.rst
  shopinvader_locomotive_product_seasonality/readme/DESCRIPTION.rst
  shopinvader_locomotive_product_seasonality/tests/__init__.py
  shopinvader_locomotive_product_seasonality/tests/test_site_settings.py
  shopinvader_product_seasonality/README.rst
  shopinvader_product_seasonality/__init__.py
  shopinvader_product_seasonality/__manifest__.py
  shopinvader_product_seasonality/components/__init__.py
  shopinvader_product_seasonality/components/seasonal_config_line_event_listener.py
  shopinvader_product_seasonality/data/ir_export_product_seasonality.xml
  shopinvader_product_seasonality/data/queue_job_channel_data.xml
  shopinvader_product_seasonality/data/queue_job_function_data.xml
  shopinvader_product_seasonality/models/__init__.py
  shopinvader_product_seasonality/models/seasonal_config_line.py
  shopinvader_product_seasonality/models/shopinvader_backend.py
  shopinvader_product_seasonality/models/shopinvader_seasonal_config_line.py
  shopinvader_product_seasonality/readme/CONTRIBUTORS.rst
  shopinvader_product_seasonality/readme/DESCRIPTION.rst
  shopinvader_product_seasonality/security/ir.model.access.csv
  shopinvader_product_seasonality/services/__init__.py
  shopinvader_product_seasonality/services/customer.py
  shopinvader_product_seasonality/tests/__init__.py
  shopinvader_product_seasonality/tests/test_customer.py
  shopinvader_product_seasonality/tests/test_prod_seasonality.py
  shopinvader_product_seasonality/views/seasonal_config_line.xml
  shopinvader_product_seasonality/views/shopinvader_backend.xml
  shopinvader_product_seasonality/views/shopinvader_seasonal_config.xml
  shopinvader_product_seasonality_search_engine/README.rst
  shopinvader_product_seasonality_search_engine/__init__.py
  shopinvader_product_seasonality_search_engine/__manifest__.py
  shopinvader_product_seasonality_search_engine/components/__init__.py
  shopinvader_product_seasonality_search_engine/components/seasonal_config_line_event_listener.py
  shopinvader_product_seasonality_search_engine/models/__init__.py
  shopinvader_product_seasonality_search_engine/models/seasonal_config_line.py
  shopinvader_product_seasonality_search_engine/models/shopinvader_seasonal_config_line.py
  shopinvader_product_seasonality_search_engine/readme/CONTRIBUTORS.rst
  shopinvader_product_seasonality_search_engine/readme/DESCRIPTION.rst
  shopinvader_product_seasonality_search_engine/tests/__init__.py
  shopinvader_product_seasonality_search_engine/tests/test_prod_seasonality.py
  shopinvader_product_seasonality_search_engine/views/shopinvader_seasonal_config.xml
Labels: approved, ready to merge, bot is merging ⏳, 14.0, add module, change

#1345 [14.0][IMP] shopinvader: allow lang override from client on customer endpoint
  shopinvader/services/customer.py
Labels: bot is merging ⏳, change

#1366 [16.0][ADD] shopinvader_anonymous_partner, shopinvader_fastapi_auth_jwt
  setup/shopinvader_anonymous_partner/odoo/addons/shopinvader_anonymous_partner
  setup/shopinvader_anonymous_partner/setup.py
  setup/shopinvader_fastapi_auth_jwt/odoo/addons/shopinvader_fastapi_auth_jwt
  setup/shopinvader_fastapi_auth_jwt/setup.py
  shopinvader_anonymous_partner/README.rst
  shopinvader_anonymous_partner/__init__.py
  shopinvader_anonymous_partner/__manifest__.py
  shopinvader_anonymous_partner/models/__init__.py
  shopinvader_anonymous_partner/models/res_partner.py
  shopinvader_anonymous_partner/readme/DESCRIPTION.rst
  shopinvader_anonymous_partner/readme/ROADMAP.rst
  shopinvader_anonymous_partner/readme/USAGE.rst
  shopinvader_anonymous_partner/tests/__init__.py
  shopinvader_anonymous_partner/tests/test_anonymous_partner.py
  shopinvader_fastapi_auth_jwt/README.rst
  shopinvader_fastapi_auth_jwt/__init__.py
  shopinvader_fastapi_auth_jwt/__manifest__.py
  shopinvader_fastapi_auth_jwt/dependencies.py
  shopinvader_fastapi_auth_jwt/readme/DESCRIPTION.rst
  shopinvader_fastapi_auth_jwt/readme/USAGE.rst
  shopinvader_fastapi_auth_jwt/tests/__init__.py
  shopinvader_fastapi_auth_jwt/tests/test_auth_jwt_or_anonymous.py
  test-requirements.txt
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1379 [14.0] ci: test with python 3.8
  .github/workflows/test.yml
Labels: approved
