Repository shopinvader/odoo-shopinvader, pull requests merged in 2023-04, with the labels that each got.

#1348 [14.0] shopinvader: do not copy backend.website_unique_key
  shopinvader/models/shopinvader_backend.py
Labels: bot is merging ⏳

#1225 [14.0][MIG] shopinvader_delivery_state
  setup/shopinvader_delivery_state/odoo/addons/shopinvader_delivery_state
  setup/shopinvader_delivery_state/setup.py
  shopinvader/models/sale.py
  shopinvader_delivery_state/README.rst
  shopinvader_delivery_state/__init__.py
  shopinvader_delivery_state/__manifest__.py
  shopinvader_delivery_state/hooks.py
  shopinvader_delivery_state/i18n/shopinvader_delivery_state.pot
  shopinvader_delivery_state/models/__init__.py
  shopinvader_delivery_state/models/sale_order.py
  shopinvader_delivery_state/readme/CONTRIBUTORS.rst
  shopinvader_delivery_state/readme/CREDITS.rst
  shopinvader_delivery_state/readme/DESCRIPTION.rst
  shopinvader_delivery_state/static/description/index.html
  shopinvader_delivery_state/tests/__init__.py
  shopinvader_delivery_state/tests/test_sale.py
  shopinvader_quotation/models/sale_order.py
Labels: approved, bot is merging ⏳

#1292 [14.0] shopinvader_image: allow skipping CDN URL
  shopinvader_image/models/shopinvader_backend.py
  shopinvader_image/models/shopinvader_image_mixin.py
  shopinvader_image/tests/test_images.py
  shopinvader_image/views/shopinvader_backend_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1351 [14.0] shopinvader_search_engine: add filter for to_be_checked state
  shopinvader_search_engine/views/shopinvader_variant_view.xml
Labels: bot is merging ⏳

#1336 [14.0] [IMP] `_prepare_cart`: prioritize values in `cart_params` over the ones in the backend settings
  shopinvader/services/cart.py
  shopinvader_sale_automatic_workflow/services/cart.py
Labels: approved, ready to merge, bot is merging ⏳

#1337 [14.0] [IMP] `shopinvader`: add a `shopinvader_options` group in the partner form
  shopinvader/views/partner_view.xml
  shopinvader_customer_multi_user/views/partner_view.xml
  shopinvader_customer_validate/views/partner_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1335 [14.0] [IMP] `shopinvader`: bump icon style
  shopinvader/static/description/icon.png
  shopinvader/static/description/icon.svg
Labels: approved, ready to merge, bot is merging ⏳

#1353 [IMP] base_url : add index
  base_url/models/url_url.py
Labels: approved, ready to merge, bot is merging ⏳
