Repository shopinvader/odoo-shopinvader, pull requests merged in 2024-03, with the labels that each got.

#1507 [REF] shopinvader_product: Remove price
  shopinvader_product/README.rst
  shopinvader_product/models/product_product.py
  shopinvader_product/readme/DESCRIPTION.rst
  shopinvader_product/schemas/__init__.py
  shopinvader_product/schemas/product.py
  shopinvader_product/static/description/index.html
  shopinvader_product/utils.py
  shopinvader_search_engine/tests/test_product_binding.py
Labels: approved, ready to merge, bot is merging ⏳

#1519 [16.0][FIX] CI
  shopinvader_api_wishlist/README.rst
  shopinvader_api_wishlist/__manifest__.py
  shopinvader_api_wishlist/dependencies.py
  shopinvader_api_wishlist/security/acl_sale_product_set_wizard.xml
  shopinvader_api_wishlist/static/description/index.html
  shopinvader_api_wishlist/wizard/__init__.py
  shopinvader_api_wishlist/wizard/sale_product_set_wizard.py
  shopinvader_product_stock_assortment/__manifest__.py
  shopinvader_restapi/tests/test_invoice.py
  shopinvader_restapi/tests/test_sale.py
  shopinvader_wishlist/services/wishlist.py
  shopinvader_wishlist/wizard/__init__.py
  shopinvader_wishlist/wizard/sale_product_set_wizard.py
Labels: approved, bot is merging ⏳

#1416 [16.0][ADD] shopinvader_restapi_sale_packaging: extracted from shopinvader_sale_packaging
  .pre-commit-config.yaml
  setup/shopinvader_restapi_sale_packaging/odoo/addons/shopinvader_restapi_sale_packaging
  setup/shopinvader_restapi_sale_packaging/setup.py
  shopinvader_restapi_sale_packaging/README.rst
  shopinvader_restapi_sale_packaging/__init__.py
  shopinvader_restapi_sale_packaging/__manifest__.py
  shopinvader_restapi_sale_packaging/readme/CONTRIBUTORS.rst
  shopinvader_restapi_sale_packaging/readme/CREDITS.rst
  shopinvader_restapi_sale_packaging/readme/DESCRIPTION.rst
  shopinvader_restapi_sale_packaging/services/__init__.py
  shopinvader_restapi_sale_packaging/services/abstract_sale.py
  shopinvader_restapi_sale_packaging/services/cart.py
  shopinvader_restapi_sale_packaging/services/packaging_mixin.py
  shopinvader_restapi_sale_packaging/tests/__init__.py
  shopinvader_restapi_sale_packaging/tests/common.py
  shopinvader_restapi_sale_packaging/tests/test_cart.py
  shopinvader_restapi_sale_packaging/tests/test_sale.py
  shopinvader_sale_packaging/README.rst
  shopinvader_sale_packaging/__manifest__.py
  shopinvader_sale_packaging/data/ir_export_product.xml
  shopinvader_sale_packaging/i18n/shopinvader_sale_packaging.pot
  shopinvader_sale_packaging/models/__init__.py
  shopinvader_sale_packaging/models/product_packaging.py
  shopinvader_sale_packaging/models/product_packaging_type.py
  shopinvader_sale_packaging/models/shopinvader_variant.py
  shopinvader_sale_packaging/readme/CONTRIBUTORS.rst
  shopinvader_sale_packaging/readme/DESCRIPTION.rst
  shopinvader_sale_packaging/static/description/index.html
  shopinvader_sale_packaging/tests/test_product_data.py
  shopinvader_sale_packaging/views/product_packaging.xml
  shopinvader_sale_packaging/views/product_packaging_type.xml
Labels: approved, ready to merge, bot is merging ⏳

#1443 shopinvader_api_address: support partial update
  shopinvader_api_address/schemas.py
Labels: bot is merging ⏳

#1482 [16.0][ADD] shopinvader_api_signin_jwt
  setup/shopinvader_api_signin_jwt/odoo/addons/shopinvader_api_signin_jwt
  setup/shopinvader_api_signin_jwt/setup.py
  shopinvader_api_signin_jwt/README.rst
  shopinvader_api_signin_jwt/__init__.py
  shopinvader_api_signin_jwt/__manifest__.py
  shopinvader_api_signin_jwt/readme/CONTRIBUTORS.rst
  shopinvader_api_signin_jwt/readme/DESCRIPTION.rst
  shopinvader_api_signin_jwt/readme/ROADMAP.rst
  shopinvader_api_signin_jwt/routers/__init__.py
  shopinvader_api_signin_jwt/routers/signin.py
  shopinvader_api_signin_jwt/security/acl_res_partner.xml
  shopinvader_api_signin_jwt/security/res_groups.xml
  shopinvader_api_signin_jwt/static/description/index.html
  shopinvader_api_signin_jwt/tests/__init__.py
  shopinvader_api_signin_jwt/tests/test_signin.py
Labels: bot is merging ⏳

#1505 [16.0][IMP] Shopinvader address: add mobile
  shopinvader_api_address/schemas.py
  shopinvader_schema_address/schemas.py
Labels: bot is merging ⏳
