Repository shopinvader/odoo-shopinvader, pull requests merged in 2024-06, with the labels that each got.

#1525 [16.0][ADD] shopinvader_api_lead: FastAPI service for creating CRM leads
  setup/shopinvader_api_lead/odoo/addons/shopinvader_api_lead
  setup/shopinvader_api_lead/setup.py
  shopinvader_api_lead/README.rst
  shopinvader_api_lead/__init__.py
  shopinvader_api_lead/__manifest__.py
  shopinvader_api_lead/readme/CONTRIBUTORS.rst
  shopinvader_api_lead/readme/DESCRIPTION.rst
  shopinvader_api_lead/routers/__init__.py
  shopinvader_api_lead/routers/lead.py
  shopinvader_api_lead/schemas/__init__.py
  shopinvader_api_lead/schemas/lead.py
  shopinvader_api_lead/security/acl_crm_lead.xml
  shopinvader_api_lead/security/groups.xml
  shopinvader_api_lead/static/description/index.html
  shopinvader_api_lead/tests/__init__.py
  shopinvader_api_lead/tests/test_post_lead.py
Labels: approved, bot is merging ⏳

#1548 [16.0][IMP] shopinvader_restapi tests: ensure unique fiscal position
  shopinvader_restapi/tests/test_cart.py
Labels: bot is merging ⏳

#1524 [16.0][IMP] shopinvader_product: main variant: add hooks
  shopinvader/models/shopinvader_variant.py
  shopinvader_product/models/product_product.py
Labels: bot is merging ⏳

#1541 [16.0][ADD] shopinvader_search_engine_update_pricelist
  setup/shopinvader_search_engine_update_pricelist/odoo/addons/shopinvader_search_engine_update_pricelist
  setup/shopinvader_search_engine_update_pricelist/setup.py
  shopinvader_search_engine_update_pricelist/README.rst
  shopinvader_search_engine_update_pricelist/__init__.py
  shopinvader_search_engine_update_pricelist/__manifest__.py
  shopinvader_search_engine_update_pricelist/models/__init__.py
  shopinvader_search_engine_update_pricelist/models/product_pricelist.py
  shopinvader_search_engine_update_pricelist/readme/CONTEXT.md
  shopinvader_search_engine_update_pricelist/readme/CONTRIBUTORS.md
  shopinvader_search_engine_update_pricelist/readme/DESCRIPTION.md
  shopinvader_search_engine_update_pricelist/static/description/index.html
  shopinvader_search_engine_update_pricelist/tests/__init__.py
  shopinvader_search_engine_update_pricelist/tests/common.py
  shopinvader_search_engine_update_pricelist/tests/test_update.py
Labels: approved, ready to merge, bot is merging ⏳

#1503 [16.0][IMP] shopinvader_schema_sale: sale_line qty rounding
  shopinvader_schema_sale/schemas/sale_line.py
Labels: approved, bot is merging ⏳

#1523 [16.0][IMP] shopinvader signin jwt anonymous cart
  shopinvader_anonymous_partner/models/res_partner.py
  shopinvader_anonymous_partner/tests/test_anonymous_partner.py
  shopinvader_api_signin_jwt/README.rst
  shopinvader_api_signin_jwt/__manifest__.py
  shopinvader_api_signin_jwt/readme/DESCRIPTION.rst
  shopinvader_api_signin_jwt/readme/ROADMAP.rst
  shopinvader_api_signin_jwt/routers/signin.py
  shopinvader_api_signin_jwt/security/acl_res_partner.xml
  shopinvader_api_signin_jwt/static/description/index.html
  shopinvader_api_signin_jwt/tests/test_signin.py
  shopinvader_sale_cart/models/sale_order.py
  shopinvader_sale_cart/tests/__init__.py
  shopinvader_sale_cart/tests/test_sale_cart.py
Labels: bot is merging ⏳

#1438 [16.0] [IMP] Shopinvader res.partner: opt in
  shopinvader/models/res_partner.py
Labels: approved, bot is merging ⏳

#1498 [16.0][ADD] shopinvader_search_engine_product_multi_price
  setup/shopinvader_search_engine_product_multi_price/odoo/addons/shopinvader_search_engine_product_multi_price
  setup/shopinvader_search_engine_product_multi_price/setup.py
  shopinvader_search_engine_product_multi_price/README.rst
  shopinvader_search_engine_product_multi_price/__init__.py
  shopinvader_search_engine_product_multi_price/__manifest__.py
  shopinvader_search_engine_product_multi_price/models/__init__.py
  shopinvader_search_engine_product_multi_price/models/product_product.py
  shopinvader_search_engine_product_multi_price/models/se_backend.py
  shopinvader_search_engine_product_multi_price/models/se_index.py
  shopinvader_search_engine_product_multi_price/readme/CONTRIBUTORS.rst
  shopinvader_search_engine_product_multi_price/readme/DESCRIPTION.rst
  shopinvader_search_engine_product_multi_price/readme/USAGE.rst
  shopinvader_search_engine_product_multi_price/schemas/__init__.py
  shopinvader_search_engine_product_multi_price/schemas/product.py
  shopinvader_search_engine_product_multi_price/static/description/index.html
  shopinvader_search_engine_product_multi_price/tests/__init__.py
  shopinvader_search_engine_product_multi_price/tests/test_product_binding.py
  shopinvader_search_engine_product_multi_price/views/se_backend.xml
  shopinvader_search_engine_product_multi_price/views/se_index.xml
Labels: approved, bot is merging ⏳

#1489 16.0 report improve
  shopinvader_api_sale/README.rst
  shopinvader_api_sale/__manifest__.py
  shopinvader_api_sale/routers/sales.py
  shopinvader_api_sale/static/description/index.html
Labels: bot is merging ⏳

#1555 [16.0][ADD] shopinvader_api_settings
  setup/shopinvader_api_settings/odoo/addons/shopinvader_api_settings
  setup/shopinvader_api_settings/setup.py
  shopinvader_api_settings/README.rst
  shopinvader_api_settings/__init__.py
  shopinvader_api_settings/__manifest__.py
  shopinvader_api_settings/readme/CONTRIBUTORS.rst
  shopinvader_api_settings/readme/DESCRIPTION.rst
  shopinvader_api_settings/routers/__init__.py
  shopinvader_api_settings/routers/settings.py
  shopinvader_api_settings/schemas/__init__.py
  shopinvader_api_settings/schemas/country.py
  shopinvader_api_settings/schemas/partner_title.py
  shopinvader_api_settings/schemas/settings.py
  shopinvader_api_settings/static/description/index.html
  shopinvader_api_settings/tests/__init__.py
  shopinvader_api_settings/tests/common.py
  shopinvader_api_settings/tests/test_shopinvader_settings_api.py
Labels: approved, bot is merging ⏳

#1554 [16.0][IMP] shopinvader_api_signin_jwt documentation
  shopinvader_api_signin_jwt/readme/DESCRIPTION.rst
  shopinvader_api_signin_jwt/readme/INSTALL.rst
Labels: approved, bot is merging ⏳

#1558 [16.0][FIX] shopinvader_api_sale_loyalty: Don't extend existing router
  shopinvader_api_sale_loyalty/README.rst
  shopinvader_api_sale_loyalty/readme/USAGE.rst
  shopinvader_api_sale_loyalty/routers/__init__.py
  shopinvader_api_sale_loyalty/routers/cart.py
  shopinvader_api_sale_loyalty/static/description/index.html
  shopinvader_api_sale_loyalty/tests/test_apply_coupon_or_reward.py
Labels: bot is merging ⏳

#1557 [16.0][ADD] shopinvader_api_settings: added lang
  shopinvader_api_settings/routers/settings.py
  shopinvader_api_settings/schemas/__init__.py
  shopinvader_api_settings/schemas/lang.py
  shopinvader_api_settings/schemas/settings.py
  shopinvader_api_settings/tests/common.py
  shopinvader_api_settings/tests/test_shopinvader_settings_api.py
Labels: bot is merging ⏳

#1542 [16.0][IMP] shopinvader_product_sale_packaging: extend ProductPackaging schema
  shopinvader_product_sale_packaging/README.rst
  shopinvader_product_sale_packaging/readme/CONTRIBUTORS.rst
  shopinvader_product_sale_packaging/schemas/product_packaging.py
  shopinvader_product_sale_packaging/static/description/index.html
  shopinvader_product_sale_packaging/tests/__init__.py
  shopinvader_product_sale_packaging/tests/test_product_data.py
  shopinvader_product_sale_packaging/tests/test_product_packaging_schema.py
Labels: bot is merging ⏳
