Repository shopinvader/odoo-shopinvader, pull requests merged in 2024-12, with the labels that each got.

#1559 [16.0][IMP] shopinvader_api_customer: add a hook to get customer values before update
  shopinvader_api_customer/routers/customer.py
Labels: bot is merging ⏳

#1364 [16.0][ADD] shopinvader_v2_app_demo
  setup/shopinvader_v2_app_demo/odoo/addons/shopinvader_v2_app_demo
  setup/shopinvader_v2_app_demo/setup.py
  shopinvader_v2_app_demo/README.rst
  shopinvader_v2_app_demo/__init__.py
  shopinvader_v2_app_demo/__manifest__.py
  shopinvader_v2_app_demo/demo/auth_jwt_validator.xml
  shopinvader_v2_app_demo/demo/fastapi_endpoint.xml
  shopinvader_v2_app_demo/demo/fs_storage.xml
  shopinvader_v2_app_demo/demo/res_groups.xml
  shopinvader_v2_app_demo/demo/res_users.xml
  shopinvader_v2_app_demo/demo/se_backend.xml
  shopinvader_v2_app_demo/demo/se_image_field_thumbnail_size.xml
  shopinvader_v2_app_demo/demo/se_index.xml
  shopinvader_v2_app_demo/demo/se_index_config.xml
  shopinvader_v2_app_demo/models/__init__.py
  shopinvader_v2_app_demo/models/fastapi_endpoint.py
  shopinvader_v2_app_demo/readme/CONTRIBUTORS.rst
  shopinvader_v2_app_demo/readme/DESCRIPTION.rst
  shopinvader_v2_app_demo/readme/HISTORY.rst
  shopinvader_v2_app_demo/static/description/icon.png
  shopinvader_v2_app_demo/static/description/index.html
  shopinvader_v2_app_demo/views/fastapi_endpoint.xml
  test-requirements.txt
Labels: bot is merging ⏳

#1571 [16.0][ADD] shopinvader_api_cart: cart helper: Add hooks [FIXED]
  shopinvader_api_cart/routers/cart.py
Labels: approved, bot is merging ⏳

#1543 [16.0][IMP] shopinvader_api_sale_loyalty: do not update rewards when reading a sale
  shopinvader_api_sale_loyalty/schemas/sale.py
Labels: approved, ready to merge, bot is merging ⏳
