Repository shopinvader/odoo-shopinvader, pull requests merged in 2025-05, with the labels that each got.

#1575 [16.0] [IMP] shopinvader_api_cart: Make cart transaction grouping extendable
  shopinvader_api_cart/routers/cart.py
  shopinvader_sale_cart/models/sale_order.py
  shopinvader_sale_cart/models/sale_order_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1553 [ADD][16.0] address shipping note #1374
  setup/shopinvader_address_shipping_note/odoo/addons/shopinvader_address_shipping_note
  setup/shopinvader_address_shipping_note/setup.py
  setup/shopinvader_api_address_shipping_note/odoo/addons/shopinvader_api_address_shipping_note
  setup/shopinvader_api_address_shipping_note/setup.py
  shopinvader_address_shipping_note/README.rst
  shopinvader_address_shipping_note/__init__.py
  shopinvader_address_shipping_note/__manifest__.py
  shopinvader_address_shipping_note/models/__init__.py
  shopinvader_address_shipping_note/models/res_partner.py
  shopinvader_address_shipping_note/readme/CONTEXT.rst
  shopinvader_address_shipping_note/readme/CONTRIBUTORS.rst
  shopinvader_address_shipping_note/readme/DESCRIPTION.rst
  shopinvader_address_shipping_note/static/description/index.html
  shopinvader_address_shipping_note/views/res_partner.xml
  shopinvader_api_address_shipping_note/README.rst
  shopinvader_api_address_shipping_note/__init__.py
  shopinvader_api_address_shipping_note/__manifest__.py
  shopinvader_api_address_shipping_note/readme/CONTRIBUTORS.rst
  shopinvader_api_address_shipping_note/readme/DESCRIPTION.rst
  shopinvader_api_address_shipping_note/schemas.py
  shopinvader_api_address_shipping_note/static/description/index.html
  shopinvader_api_address_shipping_note/tests/__init__.py
  shopinvader_api_address_shipping_note/tests/test_shopinvader_api_address_shipping_note.py
Labels: bot is merging ⏳

#1589 [16.0] [ADD] shopinvader_api_invoice
  setup/shopinvader_api_invoice/odoo/addons/shopinvader_api_invoice
  setup/shopinvader_api_invoice/setup.py
  setup/shopinvader_api_security_invoice/odoo/addons/shopinvader_api_security_invoice
  setup/shopinvader_api_security_invoice/setup.py
  setup/shopinvader_schema_invoice/odoo/addons/shopinvader_schema_invoice
  setup/shopinvader_schema_invoice/setup.py
  shopinvader_api_invoice/README.rst
  shopinvader_api_invoice/__init__.py
  shopinvader_api_invoice/__manifest__.py
  shopinvader_api_invoice/readme/CONTRIBUTORS.rst
  shopinvader_api_invoice/readme/DESCRIPTION.rst
  shopinvader_api_invoice/routers/__init__.py
  shopinvader_api_invoice/routers/invoice.py
  shopinvader_api_invoice/tests/__init__.py
  shopinvader_api_invoice/tests/test_invoice_api.py
  shopinvader_api_security_invoice/README.rst
  shopinvader_api_security_invoice/__init__.py
  shopinvader_api_security_invoice/__manifest__.py
  shopinvader_api_security_invoice/readme/CONTRIBUTORS.rst
  shopinvader_api_security_invoice/readme/DESCRIPTION.rst
  shopinvader_api_security_invoice/security/acl_product_product.xml
  shopinvader_api_security_invoice/security/acl_product_template.xml
  shopinvader_api_security_invoice/security/acl_uom_uom.xml
  shopinvader_api_security_invoice/security/groups.xml
  shopinvader_api_security_invoice/security/rule+acl_account_move.xml
  shopinvader_api_security_invoice/security/rule+acl_account_move_line.xml
  shopinvader_schema_invoice/README.rst
  shopinvader_schema_invoice/__init__.py
  shopinvader_schema_invoice/__manifest__.py
  shopinvader_schema_invoice/readme/CONTRIBUTORS.rst
  shopinvader_schema_invoice/readme/DESCRIPTION.rst
  shopinvader_schema_invoice/schemas/__init__.py
  shopinvader_schema_invoice/schemas/amount.py
  shopinvader_schema_invoice/schemas/invoice.py
  shopinvader_schema_invoice/tests/__init__.py
  shopinvader_schema_invoice/tests/common.py
  shopinvader_schema_invoice/tests/test_invoice_schema.py
Labels: bot is merging ⏳

#1590 [16.0] [ADD] shopinvader_api_cart_options
  setup/shopinvader_api_cart_options/odoo/addons/shopinvader_api_cart_options
  setup/shopinvader_api_cart_options/setup.py
  shopinvader_api_cart_options/README.rst
  shopinvader_api_cart_options/__init__.py
  shopinvader_api_cart_options/__manifest__.py
  shopinvader_api_cart_options/helper.py
  shopinvader_api_cart_options/readme/CONTRIBUTORS.md
  shopinvader_api_cart_options/readme/DESCRIPTION.md
  shopinvader_api_cart_options/readme/USAGE.md
  shopinvader_api_cart_options/schemas.py
  shopinvader_api_cart_options/static/description/index.html
  shopinvader_api_cart_options/test.py
  shopinvader_api_cart_options/tests/__init__.py
  shopinvader_api_cart_options/tests/models.py
  shopinvader_api_cart_options/tests/schemas.py
  shopinvader_api_cart_options/tests/test_shopinvader_api_cart_options.py
Labels: bot is merging ⏳

#1573 [16.0] [ADD] shopinvader_api_quotation
  sale_quotation/README.rst
  sale_quotation/__init__.py
  sale_quotation/__manifest__.py
  sale_quotation/models/__init__.py
  sale_quotation/models/product_product.py
  sale_quotation/models/product_template.py
  sale_quotation/models/sale_order.py
  sale_quotation/readme/CONTRIBUTORS.rst
  sale_quotation/readme/DESCRIPTION.rst
  sale_quotation/static/description/index.html
  sale_quotation/static/description/product.png
  sale_quotation/static/description/quotation.png
  sale_quotation/tests/__init__.py
  sale_quotation/tests/test_product.py
  sale_quotation/tests/test_quotation.py
  sale_quotation/views/product_view.xml
  sale_quotation/views/sale_view.xml
  setup/sale_quotation/odoo/addons/sale_quotation
  setup/sale_quotation/setup.py
  setup/shopinvader_api_quotation/odoo/addons/shopinvader_api_quotation
  setup/shopinvader_api_quotation/setup.py
  shopinvader_api_quotation/README.rst
  shopinvader_api_quotation/__init__.py
  shopinvader_api_quotation/__manifest__.py
  shopinvader_api_quotation/models/__init__.py
  shopinvader_api_quotation/models/sale_order.py
  shopinvader_api_quotation/readme/CONTRIBUTORS.rst
  shopinvader_api_quotation/readme/CREDITS.rst
  shopinvader_api_quotation/readme/DESCRIPTION.rst
  shopinvader_api_quotation/readme/USAGE.rst
  shopinvader_api_quotation/routers/__init__.py
  shopinvader_api_quotation/routers/cart.py
  shopinvader_api_quotation/routers/quotation.py
  shopinvader_api_quotation/schemas/__init__.py
  shopinvader_api_quotation/schemas/sale.py
  shopinvader_api_quotation/static/description/index.html
  shopinvader_api_quotation/tests/__init__.py
  shopinvader_api_quotation/tests/test_shopinvader_api_quotation.py
  shopinvader_quotation/__manifest__.py
  shopinvader_quotation/models/__init__.py
  shopinvader_quotation/models/product_template.py
  shopinvader_quotation/models/sale_order.py
  shopinvader_quotation/services/cart.py
  shopinvader_quotation/views/product_view.xml
  shopinvader_quotation/views/sale_view.xml
Labels: merged 🎉
