Repository shopinvader/odoo-shopinvader, pull requests merged in 2025-04, with the labels that each got.

#1582 [16.0][IMP] shopinvader_product: Avoid translated attribute name
  shopinvader_product/models/tools.py
Labels: approved, bot is merging ⏳

#1561 [16.0][IMP] shopinvader_schema_address: add field res_partner.company_type on Address Schema
  shopinvader_schema_address/schemas.py
Labels: approved, ready to merge, bot is merging ⏳

#1574 [16.0] [REF] shopinvader_api_cart, shopinvader_api_address: Cart and Address hooks
  shopinvader_address/models/res_partner.py
  shopinvader_api_address/routers/address_service.py
  shopinvader_api_cart/routers/cart.py
  shopinvader_api_cart/schemas/cart.py
  shopinvader_api_cart_step/__init__.py
  shopinvader_api_cart_step/helper.py
  shopinvader_api_cart_step/schemas/cart.py
Labels: approved, ready to merge, bot is merging ⏳

#1569 [16.0][IMP] Add partner title in address api schemas
  shopinvader_api_address/schemas.py
  shopinvader_api_address/tests/test_shopinvader_address_api.py
  shopinvader_schema_address/schemas.py
Labels: bot is merging ⏳

#1529 [14.0][IMP] shopinvader_variant: main product: add hooks
  shopinvader/models/shopinvader_variant.py
Labels: approved, ready to merge
